### ISSUE TITLE
Issue with Blood Magic Mod and Aether II (1.6.4)

### ISSUE THREAD

**Issue by Elecrost** [gildedgames/aether-issues#252]
So I entered the Aether, and tried to craft skyroot sticks... But when I did, all that was created was 4 Void Sigils.   I'm assuming this is some sort of ID conflict.  I checked the recipes of MANY other items and while doing this noticed that most of the Holystone, Gravitite, and Zanite items as well as many others were missing completely from my NEI menu and all of the crafting recipes to create them ended up creating Blood Magic items.  

EDIT: This is an ID conflict.  I'll list the items with similar IDs.  Blood Magic items on the left, Aether 
items on the right.

LavaSigil + AechorPetal - 17005
LavaCrystal + AetherMusicDisc - 17003
SacrificialDagger + AmbrosiumShard - 17009
MasterBloodOrb + CloudParachute - 17038
ReinforcedSlate + DartShooter - 17008
ImbuedSlate + DiamondGloves - 17055
BoundShovel + FlamingSword - 17031
WaterSigil + GoldenAmber - 17004
BlankSpell + GoldenCloudParachute - 17039
DemonicTelepositionFocus + GoldenGloves - 17054
DemonBloodShard + GoldenPendant - 17048
MundaneLengtheningCatalyst + GoldenRing - 17045
AirScribeTool + GravititeAxe - 17023
Crepitous + GravititeBoots - 17065
Sanctus + GravititeChestplate - 17063
Incendium + GravititeGloves - 17061
Magicales + GravititeHelmet - 17062
Aether + GravititeLeggings - 17064
DuskScribeTool + GravititePickaxe - 17015
DivinationSigin + GravititeShovel - 17019
SigilOfHaste + GravititeSword - 17027
WeakBloodShard + HammerOfNotch - 17036
BoundHelmet + HolySword - 17032
FireScribeTool + HolyStoneAxe - 17021
AirSigil + HolyStonePickaxe - 17013
ItemBloodRuneBlock + HolystoneShovel - 17017
MagicianBloodOrb + HolystoneSword - 17025
EnergyBazooka + InvisibilityCloak - 17082
SigilOfHolding + IronBubble - 17028
ReinforcedTelepositionFocus + IronGloves - 17053
GreaterLengtheningCatalyst + IronPendant - 17047
GreaterPowerCatalyst + IronRing - 17044
EnergyBlaster + Key - 17001
EnhancedTelepositionFocus + LeatherGloves - 17052
BoundLeggings + LightningKnife - 17034
EnergySword + MoaEgg - 17002
SigilOfMagnetism + NeptuneBoots - 17080
FocusBloodBlast + NeptuneGloves - 17076
FocusGravityWell + NeptuneHelmet - 17077
SanguineHelmet + ObsidianBoots - 17075
StandardFillingAgent + ObsidianChestplate - 17073
WeakFillingAgent + ObsidianHelmet - 17072
EnhancedFillingAgent + ObsidianLeggings - 17074
WeakBindingAgent + PhoenixBoots - 17070
Aquasalus + PhoenixChestplate - 17068
Crystallos + PhoenixGloves - 17066
Terrae + PhoenixHelmet - 17067 
Tennebrae + PhoenixLeggings - 17069
BoundPickaxe + PigSlayer - 17029
ItemSigilOfSuppression + RedCape - 17085
ItemKeyOfDiablo + RegenerationStone - 17081
StandardBindingAgent + ShardOfLife - 17041
WaterScribeTool + SkyrootAxe - 17020
ApprenticeBloodOrb + SkyrootBucket - 17011
DaggerOfSacrifice + SkyrootPickaxe - 17012
DemonPlacer + SkyrootShovel - 17016
VoidSigil + SkyrootStick - 17006
WeakActivationCrystal + SkyrootSword - 17024
TelepositionFocusItemID + SwetCape - 17051
MundanePowerCatalyst + ValkyrieCape - 17042
AveragePowerCatalyst + ValkyrieLance - 17043
BoundAxe + VampireBlade - 17030
WeakBloodOrb + VictoryMedal - 17000
BaseAlchemyComponents + WhiteCape - 17084
BloodBooks + YellowCape - 17086
EarthScribeTool + ZaniteAxe - 17022
SimpleCatalyst + ZaniteBoots - 17060
CreativeFiller + ZaniteChestplate - 17058
BucketLife + ZaniteGemstone - 17010
DemonicSlate + ZaniteGloves - 17056
SigilOfTheBridge + ZaniteHelmet - 17057
ArchmageBloodOrb + ZanitePendant - 17049
SigilOfTheFastMiner + ZanitePickaxe - 17014
AverageLengtheningCatalyst + ZaniteRing - 17046
ArmourInhibitor + ZaniteShovel - 17018
SigilOfElementalAffinity + ZaniteSword - 17026

**Comment by the-djdj** [comment]
I've recently run into this issue creating a modpack for 1.6.4, and if you still haven't solved it, or if anybody is browsing this page with a similar issue, here is the solution:
- Navigate to `<minecraft directory/config/`, and open `AWayOfTime.cfg` (Blood Magic's configuration file)
- In the items section, simply change the leading 17... of all the ID's to 18..., e.g. 17085 becomes 18085
  [AWWayofTime.cfg.txt](https://github.com/gildedgames/aether-issues/files/268371/AWWayofTime.cfg.txt)
