### ISSUE TITLE
Aether Portal glitches out when looking through Quicksoil glass

### ISSUE THREAD

**Issue by TheFallenOneGOTH** [gildedgames/aether-issues#347]
![glitchy aether portal](https://cloud.githubusercontent.com/assets/8735509/5564345/210fbcc2-8e86-11e4-9ab2-7b6f79434691.png)
To trigger a glitch, create an Aether portal and place some Quicksoil Glass to look through. The image above should be the result.

**Comment by xJonL** [comment]
This is a bug with opacity in Vanilla 1.6, this kind of issue was fixed in the 1.7+ releases.

Thanks for your bug report, keep an eye out for more.  :heart_eyes:
