### ISSUE TITLE
Weird Slider boss

### ISSUE THREAD

**Issue by typervader** [gildedgames/aether-issues#353]
The slider boss acts werid, it moves early fast and can break the blocks in its room. It also has werid movement and doesn't move like it should. It also doesnt spawn minions if it still supposed to. I also had one were there were 2 of them in on room. They are really hard to fight, but also too easy. This has gone on for serveal patches and needs to be looked at.

**Comment by medsal15** [comment]
You're wrong: it's not "werid" but "weird"

**Comment by typervader** [comment]
Im sorry, I don't worry about spelling much when I type, and I am not good at it.

**Comment by xJonL** [comment]
Does this happen in every dungeon?

**Comment by typervader** [comment]
The werid boss yes. The one that had 2 in it though, it was strange. They opened up the dungeon and it was like a big empty room with the dungeon in it, while all the others werent. The sliders are always weird however.

**Comment by xJonL** [comment]
Did you experience this on Multiplayer or Singleplayer?

**Comment by Collin1971** [comment]
Are you sure you aren't comparing the Slider to the the _Slider Host Mimic_? The Slider doesn't spawn minions unlike the Slider Host Mimic, and intentionally destroys blocks now.

**Comment by xJonL** [comment]
@Collin1971 The Slider used to spawn sentries.
