### ISSUE TITLE
Aetherii + mine mine no mi = aether portal not working

### ISSUE THREAD

**Issue by GildartsClive** [gildedgames/aether-issues#359]
so i have Aether 2 installed and mine mine no mi mod. the mods load just fine but the portal doesn't work. i dont know if it is Aether 2 or Mine Mine No Mi mod that is the problem. just thought the aether team would like to know.

**Comment by Brenwwe** [comment]
Hey @GildartsClive we are currently not looking at mod compatibility while in alpha as we would like to spend more time fixing bugs and adding content however we will look at greater mod intergration and compatibility down the track.
