### ISSUE TITLE
Thaumic tinkerer and Aether do not get along well.

### ISSUE THREAD

**Issue by roket333** [gildedgames/aether-issues#360]
---- Minecraft Crash Report ----
// There are four lights!

Time: 2/14/15 11:01 PM
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at net.aetherteam.aether.player.PlayerAether.wearingArmour(PlayerAether.java:723)
	at net.aetherteam.aether.player.PlayerAether.wearingNeptuneArmour(PlayerAether.java:734)
	at net.aetherteam.aether.player.abilities.AbilityArmor.onLivingAttack(AbilityArmor.java:182)
	at net.aetherteam.aether.player.PlayerAether.onLivingAttack(PlayerAether.java:460)
	at com.gildedgames.util.player.common.PlayerEventHandler.onLivingAttack(PlayerEventHandler.java:46)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_193_PlayerEventHandler_onLivingAttack_LivingAttackEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at net.minecraftforge.common.ForgeHooks.onLivingAttack(ForgeHooks.java:292)
	at net.minecraft.entity.player.EntityPlayer.func_70097_a(EntityPlayer.java:978)
	at net.minecraft.enchantment.EnchantmentThorns.func_151367_b(SourceFile:47)
	at net.minecraft.enchantment.EnchantmentHelper$HurtIterator.func_77493_a(EnchantmentHelper.java:490)
	at net.minecraft.enchantment.EnchantmentHelper.func_77518_a(EnchantmentHelper.java:155)
	at net.minecraft.enchantment.EnchantmentHelper.func_77516_a(EnchantmentHelper.java:170)
	at net.minecraft.enchantment.EnchantmentHelper.func_151384_a(EnchantmentHelper.java:205)
	at net.minecraft.entity.player.EntityPlayer.func_71059_n(EntityPlayer.java:1263)
	at thaumic.tinkerer.common.block.tile.tablet.TileAnimationTablet.swingHit(TileAnimationTablet.java:165)
	at thaumic.tinkerer.common.block.tile.tablet.TileAnimationTablet.func_145845_h(TileAnimationTablet.java:114)
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.aetherteam.aether.player.PlayerAether.wearingArmour(PlayerAether.java:723)
	at net.aetherteam.aether.player.PlayerAether.wearingNeptuneArmour(PlayerAether.java:734)
	at net.aetherteam.aether.player.abilities.AbilityArmor.onLivingAttack(AbilityArmor.java:182)
	at net.aetherteam.aether.player.PlayerAether.onLivingAttack(PlayerAether.java:460)
	at com.gildedgames.util.player.common.PlayerEventHandler.onLivingAttack(PlayerEventHandler.java:46)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_193_PlayerEventHandler_onLivingAttack_LivingAttackEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at net.minecraftforge.common.ForgeHooks.onLivingAttack(ForgeHooks.java:292)
	at net.minecraft.entity.player.EntityPlayer.func_70097_a(EntityPlayer.java:978)
	at net.minecraft.enchantment.EnchantmentThorns.func_151367_b(SourceFile:47)
	at net.minecraft.enchantment.EnchantmentHelper$HurtIterator.func_77493_a(EnchantmentHelper.java:490)
	at net.minecraft.enchantment.EnchantmentHelper.func_77518_a(EnchantmentHelper.java:155)
	at net.minecraft.enchantment.EnchantmentHelper.func_77516_a(EnchantmentHelper.java:170)
	at net.minecraft.enchantment.EnchantmentHelper.func_151384_a(EnchantmentHelper.java:205)
	at net.minecraft.entity.player.EntityPlayer.func_71059_n(EntityPlayer.java:1263)
	at thaumic.tinkerer.common.block.tile.tablet.TileAnimationTablet.swingHit(TileAnimationTablet.java:165)
	at thaumic.tinkerer.common.block.tile.tablet.TileAnimationTablet.func_145845_h(TileAnimationTablet.java:114)

-- Block entity being ticked --
Details:
	Name: ttinkerer:animationTablet // thaumic.tinkerer.common.block.tile.tablet.TileAnimationTablet
	Block type: ID #955 (tile.animationTablet // thaumic.tinkerer.common.block.BlockAnimationTablet)
	Block data value: 3 / 0x3 / 0b0011
	Block location: World: (-772,56,1230), Chunk: (at 12,3,14 in -49,76; contains blocks -784,0,1216 to -769,255,1231), Region: (-2,2; contains chunks -64,64 to -33,95, blocks -1024,0,1024 to -513,255,1535)
	Actual block type: ID #955 (tile.animationTablet // thaumic.tinkerer.common.block.BlockAnimationTablet)
	Actual block data value: 3 / 0x3 / 0b0011
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)

-- Affected level --
Details:
	Level name: New World
	All players: 1 total; [EntityPlayerMP['roket333'/1, l='New World', x=-771.86, y=56.00, z=1232.17]]
	Chunk stats: ServerChunkCache: 652 Drop: 0
	Level seed: 1102738057905988514
	Level generator: ID 01 - flat, ver 0. Features enabled: true
	Level generator options: 2;7,3x1,52x24;2;
	Level spawn location: World: (-746,4,1251), Chunk: (at 6,0,3 in -47,78; contains blocks -752,0,1248 to -737,255,1263), Region: (-2,2; contains chunks -64,64 to -33,95, blocks -1024,0,1024 to -513,255,1535)
	Level time: 19892 game time, 19892 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 46367 (now: false), thunder time: 13889 (now: true)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.7.0_71, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 818632296 bytes (780 MB) / 2524446720 bytes (2407 MB) up to 9544663040 bytes (9102 MB)
	JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx10G
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.85.1286 Minecraft Forge 10.13.2.1286 48 mods loaded, 48 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	FML{7.10.85.1286} [Forge Mod Loader] (forge-1.7.10-10.13.2.1286.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Forge{10.13.2.1286} [Minecraft Forge] (forge-1.7.10-10.13.2.1286.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	<CoFH ASM>{000} [CoFH ASM Data Initialization] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ivtoolkit{1.0} [IvToolkit] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	minecraftloader{0.1} [MinecraftLoader] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ThaumicTinkerer-preloader{0.1} [Thaumic Tinkerer Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	TooManyItems{1.7.10} [TooManyItems] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	OpenModsCore{@VERSION@} [OpenModsCore] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	mod_ThreadedLighting{1.7.10-1.0} [Threaded Lighting] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	gilded-games-util{1.7.10-1.0} [Gilded Games Utility] (gilded-games-util-1.7.10-1.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	lucky{5.1.0} [Lucky Block] ([1-7-10]_Lucky_Block_v5-1-0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	mod_LargeSign{1.2} [Large Sign] ([1.7.10-10.13.2.1230]Large Sign-1.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	aether{Alpha 1.7.10-1.0} [Aether II] (aether (4).jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BiblioCraft{1.9.1} [BiblioCraft] (BiblioCraft[v1.9.1][MC1.7.10].jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	CoFHCore{1.7.10R3.0.0B6} [CoFH Core] (CoFHCore-[1.7.10]3.0.0B6-32 (2).jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	redgear_core{2.1.5} [Red Gear Core] (RedGearCore-1.7.10-2.1.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	redgear_brewcraft{1.2.2} [Brewcraft] (Brewcraft-1.7.10-1.2.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	CarpentersBlocks{3.2.7 DEV R4} [Carpenter's Blocks] (Carpenter's Blocks v3.2.7 DEV R4 - MC 1.7.10.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ctabs{1.1} [CTabs] (CTabs-1.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	dynamictanks{1.0} [Dynamic Liquid Tanks 2.1] (dynamictanks-1.1.03.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	EasyCrafting{1.7.10-2.0.1.16} [Easy Crafting] (EasyCrafting-1.7.10-2.0.1.16.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	eplus{1.7.2-2.0.4} [Enchanting Plus] (EnchantingPlus-1.7.2-2.0.4 (1).jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	EnderIO{1.7.10-2.0.7.219} [Ender IO] (EnderIO-1.7.10-2.0.7.219.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ForgeMultipart{1.1.0.306} [Forge Multipart] (ForgeMultipart-1.7.10-1.1.0.306-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ExtraUtilities{1.1.0k} [Extra Utilities] (extrautilities-1.1.0k.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	McMultipart{1.1.0.306} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.1.0.306-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	JumpPad++{2.2.1} [JumpPad++] (JumpPads_R22-1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	liquidpotions{1.7.10-A1.0.6} [liquidpotions] (LiquidPotions-1.7.10-A1.0.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Mantle{1.7.10-0.3.1.jenkins180} [Mantle] (Mantle-mc1.7.10-0.3.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	mcicraft{1.0.5c} [MCICraft] (mcicraft_core-1.0.5c_MC-1.7.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	mcicraft_farming{1.0.5c} [MCICraft Farming] (mcicraft_farming-1.0.5c_MC-1.7.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	mcicraft_machines{1.0.5c} [MCICraft Machines] (mcicraft_machines-1.0.5c_MC-1.7.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	mcicraft_redstone{1.0.5c} [MCICraft Redstone] (mcicraft_redstone-1.0.5c_MC-1.7.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	is_mtc{1.5B} [Mine Trading Cards] (Mine Trading Cards-1.5B.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	minepainter{0.2.6} [MinePainter] (minepainter-0.2.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Natura{2.2.0} [Natura] (natura-1.7.10-2.2.0-b1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	OpenMods{0.6} [OpenMods] (OpenModsLib-1.7.10-0.6-snapshot-224.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	OpenBlocks{1.3} [OpenBlocks] (OpenBlocks-1.7.10-1.3-snapshot-434.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	primitivemobs{1.0} [Primitive Mobs] (primitivemobs-1.0-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ShowDurability2{1.3.0} [ShowDurability2] (ShowDurability2-1.7.10-1.4.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	sonicmod{1.4.0 MC1.7.10} [Sonic the Hedgehog Mod] (Sonic the Hedgehog Mod 1.7.10 V1.4.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Thaumcraft{4.2.3.2} [Thaumcraft] (Thaumcraft-1.7.10-4.2.3.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ThaumicTinkerer{unspecified} [Thaumic Tinkerer] (ThaumicTinkerer-2.5-1.7.10-162.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	camping{2.1} [The Camping Mod 2] (TheCampingMod_2.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	yegamolchattels{1.1} [Ye Gamol Chattels] (YeGamolChattels-1.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ForgeMicroblock{1.1.0.306} [Forge Microblocks] (ForgeMultipart-1.7.10-1.1.0.306-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Mantle Environment: Environment healthy.
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 1 / 8; [EntityPlayerMP['roket333'/1, l='New World', x=-771.86, y=56.00, z=1232.17]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by BenLarge1** [comment]
Hey, it looks like Thaumic Tinkerer and Aether have conflicting enchantments. You can change the enchantment id in the Thaumic Tinkerer config files and it should work?

**Comment by roket333** [comment]
Looks more like TT does not know what to do with thorns on that type of armor.

**Comment by roket333** [comment]
Or .rather, Aether does not know what to do when Thorns is on the armor and it is attacked like that.

**Comment by Collin1971** [comment]
Yeah, seems to be us at fault. I'll take a look.

**Comment by Brenwwe** [comment]
@roket333 We had looked into this issue and have not been able to reproduce this enchanting Aether armor or tools with the Osmotic Enchanter and fighting mobs. Can you please provide us with a rundown of how to reproduce the issue.

**Comment by roket333** [comment]
This from febuary and I enchanted a Lightning Sword with a Thaumic Tinkerer
enchantment with the level 255 via TMI and hit a mob then the world was
corrupted. I have not tested if this is still the case.

On Wed, Aug 5, 2015 at 12:06 AM, Brendan <notifications@github.com> wrote:

> @roket333 <https://github.com/roket333> We had looked into this issue and
> have not been able to reproduce this enchanting Aether armor or tools with
> the Osmotic Enchanter and fighting mobs. Can you please provide us with a
> rundown of how to reproduce the issue.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gildedgames/aether-issues/issues/360#issuecomment-127896380>
> .
>



-- 
http://signaturecraft.us/signatures/eJwrs9OLcnNzEtNLkpMK0kt4ipCE3BIz03MzNFLzs-FSBkbG3OFpCbmKrjlF5UUpRYXKxhxBZfmFWUWp3IZmZqCsQGXAQDJYh4C.png

**Comment by Zsashas** [comment]
What enchantment did you put on the sword? Dispersed/Focused Strikes, Vampirism, Wrath, etc? My guess is the mob had thorns on its armor, and tried to reflect whatever you did back to you.
