### ISSUE TITLE
Accessories do not show

### ISSUE THREAD

**Issue by Pepperx3** [gildedgames/aether-issues#362]
When wearing a full set of valkyrie the wings do not show on the player, along with gloves and Mouse Ear Cap.

**Comment by xJonL** [comment]
I've tested this on the latest build on singleplayer. Could you explain further how this issue is occuring? Is this on your client side? Can you see the renders on multiplayer?

**Comment by xJonL** [comment]
Figure out the issue, this is a multiplayer issue of renders on players
