### ISSUE TITLE
Conflicting dimension IDs with no config option

### ISSUE THREAD

**Issue by Sunconure11** [gildedgames/aether-issues#366]
The dimension ID for the Aether conflicts with one of my mods, and there is no option to change the ID.

http://pastebin.com/wdjnzd2k

Also, if the mod has any biomes or enchantments, I think we need a config to change their IDs too.

**Comment by Madchin** [comment]
Can confirm, identical Dimensional ID Conflict on my client

**Comment by warezit** [comment]
I can also confirm that changing the Dimension ID for the CompactMachines mod DOES fix this problem, but it break the links to all the Compact Machines.

Upon using the PSD (Personal Shrinking Device) to enter a previoulsy existing Compact Machine, you are transported to the Aether II Dimension.

**Comment by Collin1971** [comment]
This issue has not been fixed @xJonL.

**Comment by warezit** [comment]
Yes they occur. I can confirm this.

Crash log from Compact Machines DIM ID conflict here:
http://pastebin.com/D6xGELL9

**Comment by Collin1971** [comment]
That appears to be a dimension ID conflict, not an enchantment or biome ID conflict. :p

**Comment by warezit** [comment]
@Collin1971  That IS what I have already stated.

**Comment by Collin1971** [comment]
Oh! My bad. I appear to have gotten yours and @Sunconure11's conversations mixed up. Sorry about that.

I'll add a config option for the dimension ID. :)

**Comment by warezit** [comment]
@Collin1971 No worries!

Awesome! Thank you!

**Comment by Collin1971** [comment]
Okay, it's been added. :)

**Comment by warezit** [comment]
@Collin1971 Man, you're good! I'll give it a shot!

**Comment by warezit** [comment]
Side note/quick question... @Collin1971 I am not running the Aether II launcher (I am manually installing the Aether II mod).

Is this config update/change reflected in AEII v 1.1 (currently available here: http://www.aetherii.com/downloads )?

**Comment by warezit** [comment]
Nevermind - I see your post here: https://github.com/gildedgames/aether-issues/issues/394

**Comment by Collin1971** [comment]
Haha, sorry! Forgot to add that little note!
