### ISSUE TITLE
Crashing the server for 2 Reasons

### ISSUE THREAD

**Issue by CraftlandSoul** [gildedgames/aether-issues#368]
Hei there,

first thanks for the 1.7.10 Update. If possible we would require a bit help with our problem. Our Modpack http://technicpack.net/modpack/edit/564514/page works fine with the Aether 2 expcept in two ways. During entering the dimension the client closes and you have to reconnect to the server to be in the Aether then. As long as we do not attempt to leave a dungeon you entered before the server is ok but of course you would like to leave and that crashes the whole server.

Although there might be issues with the dimension ID´s of the End and the Twilight i assume.

Thanks and hei be welcome to talk to us old folks if it pleases you somehow. Welcome on our server.

**Comment by CraftlandSoul** [comment]
http://www.aetherii.com/forums/m/18024753/viewthread/19552629-aether-ii-1710-confirmed-our-modlist-modcompatibility

**Comment by xJonL** [comment]
Could you give us some crash logs?

**Comment by CraftlandSoul** [comment]
Yeah Jon,

i ll look into it tomorrow, its 2 am as my excuse. If it helps you guys you can even get root access to the mirrored server.

Grüße

Peter Mueller

**Comment by xJonL** [comment]
We don't really need access, just some crash logs. :yum:

**Comment by CraftlandSoul** [comment]
Sure, welcome. Brenwwe has access to the root server already and took some of the logs. I thought you already got some, just tell me if you need more. Another problem i am dealing with at the moment is massive performance drop since the aether integration.

Best regards

Peter Mueller

**Comment by CraftlandSoul** [comment]
We removed the Aether temporarly cause of crashing every time now, when we entered it. I provide the latest logs and the version of the modpack via link. I hope it helps. Anyways you can of course count on our help, we are Aetherfans since 2011.

Crashlogs over the whole period running the Aether II inside the Epsilon Packversion:
https://www.dropbox.com/sh/l1lex47qqu7r6mm/AADQaQ9rjqwnOvvFED_1_EBQa?dl=0

Link to Epsilon:
http://misuterra.eu/download/sundown/Epsilon/modpack.zip

**Comment by Collin1971** [comment]
These crashlogs are corresponding to the Achievement bug which has been fixed in the upcoming release.

**Comment by CraftlandSoul** [comment]
thanks Collin, excited to reintegrate the Aether
