### ISSUE TITLE
Achievement Screen overriden

### ISSUE THREAD

**Issue by williewillus** [gildedgames/aether-issues#371]
The Aether seems to completely overwrite the Achievements pane with its own interface such that when clicking the "Minecraft" button to switch mods, a new instance if the GUI is made and Aether achievements are loaded. This prevents achievements added the normal way from other mods from being shown; now only MC and Aether achievements can be viewed (but others can be achieved but not viewed)

**Comment by Chrisknyfe** [comment]
I have also reproduced this bug with:
Forge for 1.7.10 10.13.2.1291 (1.7.10-Recommended)
gilded-games-util-1.7.10-1.5.jar
Aether II 1.7.10-1.0
twilightforest-1.7.10-2.3.3.jar

Twilight forest achievements cannot be seen, only the achievements for Minecraft and Aether can be seen.

**Comment by 115kino** [comment]
There is a semi permanent fix that I have made for the next patch of the Aether. This shouldn't be an issue next patch

**Comment by iFerrer00** [comment]
I hate this bug! I think it's for the interface of the Aether II achievement screen, but i'm not sure... Please, fix it soon...
