### ISSUE TITLE
Aether is having trouble getting a list of usernames on LAN when adding a party member.

### ISSUE THREAD

**Issue by roket333** [gildedgames/aether-issues#373]
---- Minecraft Crash Report ----
// On the bright side, I bought you a teddy bear!

Time: 2/15/15 12:33 PM
Description: Rendering screen

java.lang.NullPointerException: Rendering screen
	at net.aetherteam.aether.player.PlayerAether.getUsername(PlayerAether.java:1320)
	at net.aetherteam.aether.client.gui.notifications.GuiPlayerRequestSlot.drawPlayerSlot(GuiPlayerRequestSlot.java:81)
	at net.aetherteam.aether.client.gui.notifications.GuiRequestPlayer.func_73863_a(GuiRequestPlayer.java:301)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1061)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:989)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.aetherteam.aether.player.PlayerAether.getUsername(PlayerAether.java:1320)
	at net.aetherteam.aether.client.gui.notifications.GuiPlayerRequestSlot.drawPlayerSlot(GuiPlayerRequestSlot.java:81)
	at net.aetherteam.aether.client.gui.notifications.GuiRequestPlayer.func_73863_a(GuiRequestPlayer.java:301)

-- Screen render details --
Details:
	Screen name: net.aetherteam.aether.client.gui.notifications.GuiRequestPlayer
	Mouse location: Scaled: (492, 252). Absolute: (985, 490)
	Screen size: Scaled: (960, 498). Absolute: (1920, 996). Scale factor of 2

-- Affected level --
Details:
	Level name: MpServer
	All players: 2 total; [EntityClientPlayerMP['roket333'/225759, l='MpServer', x=218.86, y=64.62, z=163.11], EntityOtherPlayerMP['bob_rose'/5389, l='MpServer', x=219.86, y=63.00, z=202.37]]
	Chunk stats: MultiplayerChunkCache: 841, 841
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (236,64,240), Chunk: (at 12,4,0 in 14,15; contains blocks 224,0,240 to 239,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 44185 game time, 26846 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 66 total; [EntityBat['Bat'/222158, l='MpServer', x=293.50, y=18.92, z=235.59], EntityZombie['Zombie'/223466, l='MpServer', x=273.50, y=11.00, z=207.50], EntityCreeper['Creeper'/223467, l='MpServer', x=273.50, y=11.00, z=209.50], EntityClientPlayerMP['roket333'/225759, l='MpServer', x=218.86, y=64.62, z=163.11], EntityBat['Bat'/222157, l='MpServer', x=294.63, y=25.64, z=213.97], EntityCreeper['Creeper'/225489, l='MpServer', x=227.50, y=29.00, z=115.50], EntityCreeper['Creeper'/225490, l='MpServer', x=229.50, y=29.00, z=116.50], EntitySkeleton['Skeleton'/225491, l='MpServer', x=232.50, y=30.00, z=120.09], EntityOtherPlayerMP['bob_rose'/5389, l='MpServer', x=219.86, y=63.00, z=202.37], EntityCreeper['Creeper'/225890, l='MpServer', x=208.50, y=33.00, z=144.50], EntitySquid['Squid'/220494, l='MpServer', x=222.25, y=49.31, z=108.53], EntityCreeper['Creeper'/226315, l='MpServer', x=284.94, y=11.00, z=97.41], EntityCreeper['Creeper'/225889, l='MpServer', x=209.50, y=33.00, z=145.50], EntityEnderman['Enderman'/222720, l='MpServer', x=262.69, y=48.00, z=115.31], EntityZombie['Zombie'/221028, l='MpServer', x=167.50, y=17.00, z=232.50], EntitySkeleton['Skeleton'/223838, l='MpServer', x=192.50, y=16.00, z=235.50], EntityCreeper['Creeper'/223839, l='MpServer', x=190.50, y=16.00, z=237.50], EntitySpider['Spider'/224253, l='MpServer', x=139.09, y=25.00, z=132.91], EntityCreeper['Creeper'/216258, l='MpServer', x=220.50, y=14.00, z=242.50], EntitySquid['Squid'/220656, l='MpServer', x=228.69, y=57.34, z=115.63], EntitySquid['Squid'/220666, l='MpServer', x=188.53, y=52.03, z=135.38], EntitySquid['Squid'/220664, l='MpServer', x=204.33, y=49.36, z=140.77], EntityBat['Bat'/226135, l='MpServer', x=267.13, y=41.10, z=87.25], EntityZombie['Zombie'/227097, l='MpServer', x=277.50, y=49.00, z=169.84], EntityZombie['Zombie'/227096, l='MpServer', x=276.50, y=48.00, z=174.50], EntityBat['Bat'/226347, l='MpServer', x=188.43, y=12.01, z=241.10], EntitySkeleton['Skeleton'/219909, l='MpServer', x=230.50, y=19.00, z=154.50], EntitySquid['Squid'/220648, l='MpServer', x=236.25, y=57.38, z=120.16], EntitySquid['Squid'/220653, l='MpServer', x=239.50, y=54.00, z=115.75], EntitySkeleton['Skeleton'/215754, l='MpServer', x=259.50, y=32.00, z=227.56], EntitySquid['Squid'/220572, l='MpServer', x=190.50, y=48.34, z=151.03], EntitySquid['Squid'/220575, l='MpServer', x=194.44, y=47.22, z=147.59], EntitySkeleton['Skeleton'/226388, l='MpServer', x=274.50, y=21.00, z=94.50], EntitySpider['Spider'/219215, l='MpServer', x=271.00, y=37.00, z=88.34], EntitySpider['Spider'/224495, l='MpServer', x=160.50, y=37.00, z=185.50], EntityZombie['Zombie'/228559, l='MpServer', x=156.50, y=29.00, z=240.50], EntitySquid['Squid'/220570, l='MpServer', x=191.38, y=46.00, z=147.25], EntitySquid['Squid'/220571, l='MpServer', x=189.28, y=47.34, z=153.09], EntityBat['Bat'/221832, l='MpServer', x=254.03, y=36.10, z=89.50], EntityBat['Bat'/221837, l='MpServer', x=233.75, y=20.73, z=151.84], EntityZombie['Zombie'/224620, l='MpServer', x=256.66, y=52.00, z=168.50], EntitySkeleton['Skeleton'/214663, l='MpServer', x=271.50, y=44.00, z=117.50], EntityCreeper['Creeper'/222717, l='MpServer', x=258.94, y=48.00, z=116.50], EntityZombie['Zombie'/227902, l='MpServer', x=142.50, y=27.00, z=148.50], EntityZombie['Zombie'/227901, l='MpServer', x=145.50, y=27.00, z=148.50], EntityCreeper['Creeper'/218933, l='MpServer', x=264.50, y=26.00, z=92.50], EntityZombie['Zombie'/217706, l='MpServer', x=243.91, y=14.00, z=178.41], EntityEnderman['Enderman'/222719, l='MpServer', x=263.41, y=48.00, z=117.69], EntityCreeper['Creeper'/227900, l='MpServer', x=141.50, y=27.00, z=147.50], EntitySkeleton['Skeleton'/221883, l='MpServer', x=157.38, y=54.00, z=171.50], EntitySheep['Sheep'/5250, l='MpServer', x=143.91, y=63.00, z=218.47], EntitySheep['Sheep'/5251, l='MpServer', x=146.69, y=63.00, z=219.69], EntitySheep['Sheep'/5252, l='MpServer', x=152.88, y=64.00, z=218.09], EntityZombie['Zombie'/225950, l='MpServer', x=139.50, y=35.00, z=188.50], EntityBat['Bat'/221574, l='MpServer', x=217.31, y=25.84, z=163.93], EntityZombie['Zombie'/220944, l='MpServer', x=298.50, y=45.00, z=214.50], EntityCreeper['Creeper'/228584, l='MpServer', x=267.50, y=34.00, z=220.50], EntityZombie['Zombie'/225005, l='MpServer', x=259.50, y=26.00, z=118.50], EntityZombie['Zombie'/221878, l='MpServer', x=281.41, y=32.00, z=114.69], EntitySheep['Sheep'/5262, l='MpServer', x=199.50, y=70.00, z=234.22], EntitySheep['Sheep'/5263, l='MpServer', x=199.50, y=71.00, z=235.81], EntitySheep['Sheep'/5265, l='MpServer', x=193.38, y=70.00, z=237.53], EntitySheep['Sheep'/5264, l='MpServer', x=199.50, y=70.00, z=232.50], EntityOtherPlayerMP['bob_rose'/5389, l='MpServer', x=219.86, y=63.00, z=202.37], EntityBat['Bat'/222132, l='MpServer', x=275.06, y=49.05, z=175.09], EntityCreeper['Creeper'/220449, l='MpServer', x=255.31, y=51.00, z=167.53]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2432)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:909)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.7.0_71, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 440934808 bytes (420 MB) / 2118123520 bytes (2020 MB) up to 9544663040 bytes (9102 MB)
	JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx10G
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.85.1286 Minecraft Forge 10.13.2.1286 8 mods loaded, 8 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	FML{7.10.85.1286} [Forge Mod Loader] (forge-1.7.10-10.13.2.1286.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Forge{10.13.2.1286} [Minecraft Forge] (forge-1.7.10-10.13.2.1286.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	TooManyItems{1.7.10} [TooManyItems] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	mod_ThreadedLighting{1.7.10-1.0} [Threaded Lighting] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	gilded-games-util{1.7.10-1.0} [Gilded Games Utility] (gilded-games-util-1.7.10-1.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	aether{Alpha 1.7.10-1.0} [Aether II] (aether (4).jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Mantle Environment: Environment healthy.
	Launched Version: 1.7.10-Forge10.13.2.1286
	LWJGL: 2.9.1
	OpenGL: GeForce GTX 560 Ti/PCIe/SSE2 GL version 4.5.0 NVIDIA 347.25, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by 115kino** [comment]
This is already fixed in the next patch.
