### ISSUE TITLE
Clientside Crash when passing through portal into Aether on a server

### ISSUE THREAD

**Issue by GrinningMoon** [gildedgames/aether-issues#374]
My client crashes when I attempt to pass into the Aether dimension from the Overworld. This is on a pure 1291 Forge Server (for testing, I'd like it to run on Cauldron but what're you going do) using only the 1.7.10 Aether mod and gilded-games-util-1.7.10-1.5 mod. The server is a fresh install, and the client is only using the above mods as well. As I enter the dimension, the screen displays the dimension for a split second and then either displays "Internal Server Error" or crashes the client with "Ticking Player".

Here is the FML log from the server. The good stuff is around line 3467.
http://pastebin.com/YxHrd5y5

**Comment by roket333** [comment]
what's Cauldron?

**Comment by KamranMackey** [comment]
A server based on Bukkit and Forge, which is no longer developed.

**Comment by GrinningMoon** [comment]
Cauldron is a server software that implements both Bukkit and Forge. It was formally MCPC+ and is deprecated. Again though, this test was done with a pure Forge server install. I was only pointing that I still use Cauldron. Something like this shouldn't happen on a basic, pure Forge server installation.

**Comment by Maokuma** [comment]
Similar error using an dedicated McMyAdmin with a forge 1291 server with no bukkit plugins and vanilla whitelist.
It gives: java.lang.NoSuchMethodError: net.aetherteam.aether.client.gui.achievements.AchievementSoundHandler.playSoundfor(Lnet/minecraft/stats/Achievement;)V
And a few onEntityLiving/onEntityUpdate thread/ERROR
On re-log Aether works fine and going back to overworld works fine. Also on the client, going to Aether works great.

**Comment by xJonL** [comment]
You are crashing because our achievement system is borked on asap, we've fixed it in the next upcoming patch.
