### ISSUE TITLE
Aechor Plants and Carrion Sprouts generate again in the world after relogging in Singleplayer

### ISSUE THREAD

**Issue by aeryk17aj** [gildedgames/aether-issues#375]

**Comment by 115kino** [comment]
Please elaborate more on this. Are they duplicating? Are they falling back in place?

**Comment by aeryk17aj** [comment]
It's in a way duplicating. 

One time I logged into my world and an Aechor Plant was suddenly right beside me.
I tried clearing the plants and sprouts in about a 2x2 chunk area, relogged, and they were there again but not in the exact same spots.

**Comment by xJonL** [comment]
This is the way we've designed it.  The mods will respawn after a bit, but they may be designed poorly if they respawn right after relogging.
