### ISSUE TITLE
Valkyrie Lance hates being enchanted

### ISSUE THREAD

**Issue by roket333** [gildedgames/aether-issues#376]
Enchanting a Valkyrie lance then hitting some mod causes it to apparently spawn an invalid particle.

**Comment by xJonL** [comment]
Enchanting on an altar or did you mean enchanting with an enchantment table/book/anvil?

**Comment by roket333** [comment]
using TMI to enchant. It works fine with everything else though.

On Mon, Feb 16, 2015 at 5:57 PM, Jon <notifications@github.com> wrote:

> Enchanting on an altar or did you mean enchanting with an enchantment
> table/book/anvil?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gildedgames/aether-issues/issues/376#issuecomment-74600814>
> .
>



-- 
http://signaturecraft.us/signatures/eJwrs9OLcnNzEtNLkpMK0kt4ipCE3BIz03MzNFLzs-FSBkbG3OFpCbmKrjlF5UUpRYXKxhxBZfmFWUWp3IZmZqCsQGXAQDJYh4C.png
