### ISSUE TITLE
NEI Crash 

### ISSUE THREAD

**Issue by Mattabase** [gildedgames/aether-issues#377]
When you hit U with new on item you crash. 

http://goo.gl/HydkWj

**Comment by Mattabase** [comment]
CodeChickenCore-1.7.10-1.0.4.35-universal

NotEnoughItems-1.7.10-1.0.4.83-universal

And 

CodeChickenCore-1.7.10-1.0.4.29-universal

NotEnoughItems-1.7.10-1.0.3.74-universal

Both still crash. 

The crash goes away when I remove the AetherII

**Comment by xJonL** [comment]
Do you have any other mods installed besides Aether II, NEI and CodechickenCore?

**Comment by HEmile** [comment]
NEI crash happens here: https://github.com/Chicken-Bones/NotEnoughItems/blob/1.7/src/codechicken/nei/recipe/ShapelessRecipeHandler.java#L49

**Comment by Mattabase** [comment]
I can print a full mod list if needed.

**Comment by xJonL** [comment]
Sure, I'd love that. Also provide a crash log.

**Comment by williewillus** [comment]
I have had this crash. The faulty mods are libsandstone and reliquary.

**Comment by Mattabase** [comment]
Looks like removing Libsandstone and Reliquary did fix the issue.
