### ISSUE TITLE
Client Crashes whenever attempting to use party system

### ISSUE THREAD

**Issue by l3CY** [gildedgames/aether-issues#378]
Immediately after a player creates a party, any player attempting to view the party list is immediately shown an blank blue screen with a centred dirt block image, and is then quickly followed by a crash. 

The screen shown before crash
http://i40.photobucket.com/albums/e230/SlightlyVisible/Aether_Crash_zpsbnn1idet.png 

Crash Report generated using OpenEye
http://openeye.openmods.info/crashes/5a83d29e6065a7750ae3763e257ddd84

Edit: Paragraph below is no longer relevant; Aether crashes standalone. 
Aside from Aether's two files, the only other mods installed were NotEnoughItems, Codechicken Core(used by NEI), and of course OpenEye for crash report generation.  I realize that you aren't interested in working on mod compatibility yet but, given the popularity or NEI, I highly highly suggest you work out it's compatibility ASAP.  NEI is as essential to modded minecraft as SKYUI is to skyrim.  Many users simply won't not play without it.

**Comment by l3CY** [comment]
I managed to replicate the issue again using JUST Aether's two files. and OpenEye(Crash reporter)
http://openeye.openmods.info/crashes/9aafd79d50fbac2c506e1cd75068d0b4

**Comment by Jaitsu** [comment]
Yup, getting the same thing. Is there a command for adding party members without using the GUI to bypass this until it's fixed?

**Comment by 115kino** [comment]
This will be fixed in the next patch of the aether
