### ISSUE TITLE
Strange Tinker's Construct interactions

### ISSUE THREAD

**Issue by Jaitsu** [gildedgames/aether-issues#381]
There seems to be at least a handful of strange interactions between the new Aether II for 1.7.10 and Tinker's Construct. On my server (and in SP, upon testing):

Traveler's Boots' "step-up" function doesn't work

If they have ANY heart canisters, players are treated as though they have 20 (3 full health bars: red-orange-yellow) if they move to another dimension, such as using a Nether Portal or Mystcraft's /tpx. These hearts can't be removed without wiping the player's file, even if Aether is removed.

There may be more, but we haven't had long to test.

**Comment by conetopia** [comment]
Aether with Tinker's ? interesting. would like to check it out sometime.

**Comment by Zackorion15** [comment]
just posting to confirm the weirdness, in my SP world i had 15 total heart containers, but my character now seems to have 440 max health.

**Comment by Collin1971** [comment]
Even though this issue came before the mentioned issues below, it'd be easier to separate this issue into two separate issues.

The heart canister issue can be found here: #459, and the step assist issue here: #452.
