### ISSUE TITLE
Kick Upon Entering Aether SMP

### ISSUE THREAD

**Issue by Amaxter** [gildedgames/aether-issues#382]
Upon entering the Aether on a multiplay server players are kicked with an Internal Server Error and have to rely to get back in. Going back through the portal is fine though.

**Comment by xJonL** [comment]
Is the server running Cauldron? Basically Cauldron is a Forge server running Bukkit

**Comment by GrinningMoon** [comment]
I have the same issue. This happens on both a Cauldron 1.7.10 (build 1236) server, and on a pure Forge 1.7.10 (build 1291) server. I've tried only installing the Aether and util mods. The Forge server was built from scratch. My client only used the same Aether and util mods to connect.

**Comment by xJonL** [comment]
Tested this on a Forge 1291 server running Aether II 1.7.10 release build
https://gist.github.com/xJonL/15b98b6431f0bc007598

**Comment by Yelenn44** [comment]
Same crash for me. With forge. No other mods installed.

**Comment by Maokuma** [comment]
Similar error using an dedicated McMyAdmin with a forge 1291 server with no bukkit plugins and vanilla whitelist.
It gives: java.lang.NoSuchMethodError: net.aetherteam.aether.client.gui.achievements.AchievementSoundHandler.playSoundfor(Lnet/minecraft/stats/Achievement;)V
And a few onEntityLiving/onEntityUpdate thread/ERROR
On re-log Aether works fine and going back to overworld works fine. Also with the client only, going to Aether works great.

**Comment by xJonL** [comment]
Thanks for the crash reports, guys. We've fixed this in the next patch coming soon. ;)

**Comment by Yelenn44** [comment]
THanks. :D

**Comment by roket333** [comment]
In the mean ti me, make a warp to the aether of set your spawn i n the aether. It worked for me.
