### ISSUE TITLE
Entities registered as Minecraft entities

### ISSUE THREAD

**Issue by Adaptivity** [gildedgames/aether-issues#385]
They should be registered as mod-entities(Aether II entities). This will prevent possible entity IDs conflicts.

**Comment by roket333** [comment]
like how when I install the Sonic the Hedgehog mod there is Amys, Shadows and Silvers everywhere.

**Comment by Collin1971** [comment]
Thanks for that helpful insight! I'll look into it. :)

**Comment by therule2010** [comment]
@roket333 I had something similar happen when I installed the treeores mod, all of the mobs were tree ore bosses XD

**Comment by Collin1971** [comment]
We're going to pushing this issue back for Aether 1.8. Changing how entities are registered would cause all Aether entities in old worlds to be nuked, and we really don't want that for a bugfix release.

**Comment by Adaptivity** [comment]
If new releases for 1.7.10 are planned, check this [issue](https://github.com/MinecraftForge/MinecraftForge/issues/1880). You are actually can convert to mod entities in 1.7.10 and add a fallback *EntityList.stringToClassMapping.put(<oldName>, YourEntity.class*. So entities in old worlds won't disappear.

**Comment by 115kino** [comment]
This has FINALLY been fixed in 1.5 along with many other fixes. :3
