### ISSUE TITLE
Achievements between mods problem

### ISSUE THREAD

**Issue by Zaltora** [gildedgames/aether-issues#386]
When we play with aether II and others mods, achievement button show only  "minecraft" and "the aether II" achievements, others mods are hided like "hardcore ender expansion" or "twilight forest".

my mod list => the aether II, thaumcraft, twilight forest, HEE, Optifine, redstone paste, craftguide ;
forge 10.13.2.1291 ;

**Comment by xJonL** [comment]
Duplicate of:
https://github.com/gildedgames/aether-issues/issues/371
