### ISSUE TITLE
"Internal server error" when I try to enter in any server.

### ISSUE THREAD

**Issue by iFerrer00** [gildedgames/aether-issues#388]
I have 108 mods installed (including Aether II, for sure), I try to enter to any Minecraft server but when I connect it automatically disconnect me of the server, I lose the connection and it says "Internal server error". How I said, this happends in any server, I tried 3 different servers, and I can't get into anyone.

**Comment by xJonL** [comment]
If you're running Aether II 1.7.10 and you're trying to connect to a server on the cloud, be advised that some of those servers do have all the mods you have. Also Aether's compatibility with some mods is a bit broken right now. Can you even make a singleplayer world?

**Comment by iFerrer00** [comment]
Sure I can, and it works perfectly (excepting the achievements bug).
And no, I'm not trying to connect to a server on the cloud, I'm trying to connect to a vanilla Minecraft server, and it says the same error everytime I try to connect. This happens with ANY server.

A curious thing! When I try to connect to an Aether II server on the cloud i can't, but this time it says: "Mod rejections [FMLMod:TConstruct{1.7.10-1.8.2.build857}]

It can be that Tinker's Construct mod is not compatible with Aether II?

**Comment by roket333** [comment]
anything is possible!

On Mon, Feb 16, 2015 at 11:48 PM, iFerrer00 <notifications@github.com>
wrote:

> Sure I can, and it works perfectly (excepting the achievements bug).
> And no, I'm not trying to connect to a server on the cloud, I'm trying to
> connect to a vanilla Minecraft server, and it says the same error everytime
> I try to connect. This happens with ANY server.
>
> A curious thing! When I try to connect to an Aether II server on the cloud
> i can't, but this time it says: "Mod rejections
> [FMLMod:TConstruct{1.7.10-1.8.2.build857}]
>
> It can be that Tinker's Construct mod is not compatible with Aether II?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gildedgames/aether-issues/issues/388#issuecomment-74624492>
> .
>



-- 
http://signaturecraft.us/signatures/eJwrs9OLcnNzEtNLkpMK0kt4ipCE3BIz03MzNFLzs-FSBkbG3OFpCbmKrjlF5UUpRYXKxhxBZfmFWUWp3IZmZqCsQGXAQDJYh4C.png

**Comment by Collin1971** [comment]
TConstruct is probably required on the server you're connecting to, too. Most cloud servers only have the Aether II installed with some Bukkit/Forge/Cauldron plugins.
