### ISSUE TITLE
Crash client with "Morph" mods

### ISSUE THREAD

**Issue by quienti** [gildedgames/aether-issues#391]
http://pastebin.com/7948Yamh

One of the players on my server turned into another player
Now, he can't connect on this server

**Comment by Robijnvogel** [comment]
Morph caused my client to crash when I morphed into an Aether II bird.
This is not the same symptom, but it may very well be related to this issue.

http://pastebin.com/td9hcxed

By the way, to give your player access to the server again, you could try and find out which his player unique files are. He will probably lose his morphs and his inventory, but hey! that is always better than nothing. 
Alternatively, you could try to boot up the server once without morph installed and let "the player" connect to it without morph installed. After this add morph again and it may have solved your problem.

**Comment by 115kino** [comment]
Should FINALLY be fixed in 1.5 :)
