### ISSUE TITLE
Request: Configurable ids for things like Dimensions, Biomes, Enchantments

### ISSUE THREAD

**Issue by BBoldt** [gildedgames/aether-issues#394]
It's important to be able to change these things to avoid conflicts. 

While it is possible to work around Aether II by changing the ids of other things that conflict, that isn't optimal as eventually we're going to run into another mod that doesn't have those ids configurable.

**Comment by Collin1971** [comment]
I've added it to the config. Here's what it looks like in the config for the next release.

```
"dimension ids" {
    I:"Aether Dimension ID"=3
    I:"Dungeon Dimension ID"=4
}
"biome ids" {
    I:"Aether Biome ID"=237
}
"potion ids" {
    I:"High Steps Potion ID"=26
    I:"Slowfall Potion ID"=25
}
```

**Comment by BBoldt** [comment]
Fantastic!

Thanks @Collin1971
