### ISSUE TITLE
Opening Invite Member for Parties causing Client Side Crash

### ISSUE THREAD

**Issue by Icebelly** [gildedgames/aether-issues#396]
Basically as stated in the title. Opening the menu causes a dirt block in the middle of the screen to appear surrounded by black for several seconds before the client simply just crashes.

Client side glitch only. Only seems to happen when being the one to invite other people.

Also seems to result in not actually being in your party upon rejoining.

Crash log below:

---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 2/17/15 4:06 PM
Description: Rendering screen

java.lang.NullPointerException: Rendering screen
	at net.aetherteam.aether.player.PlayerAether.getUsername(PlayerAether.java:1320)
	at net.aetherteam.aether.client.gui.notifications.GuiPlayerRequestSlot.drawPlayerSlot(GuiPlayerRequestSlot.java:81)
	at net.aetherteam.aether.client.gui.notifications.GuiRequestPlayer.func_73863_a(GuiRequestPlayer.java:301)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1061)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:990)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.aetherteam.aether.player.PlayerAether.getUsername(PlayerAether.java:1320)
	at net.aetherteam.aether.client.gui.notifications.GuiPlayerRequestSlot.drawPlayerSlot(GuiPlayerRequestSlot.java:81)
	at net.aetherteam.aether.client.gui.notifications.GuiRequestPlayer.func_73863_a(GuiRequestPlayer.java:301)

-- Screen render details --
Details:
	Screen name: net.aetherteam.aether.client.gui.notifications.GuiRequestPlayer
	Mouse location: Scaled: (413, 272). Absolute: (826, 486)
	Screen size: Scaled: (840, 516). Absolute: (1680, 1031). Scale factor of 2

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [GCEntityClientPlayerMP['Icebelly'/171518, l='MpServer', x=-940.76, y=161.62, z=-761.30]]
	Chunk stats: MultiplayerChunkCache: 441, 441
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-115,64,240), Chunk: (at 13,4,0 in -8,15; contains blocks -128,0,240 to -113,255,255), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 11763403 game time, 264265 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 112 total; [EntityCreeper['Creeper'/171522, l='MpServer', x=-920.34, y=39.00, z=-791.00], EntityLocomotiveElectric['Electric Locomotive'/0, l='MpServer', x=-946.14, y=144.35, z=-765.50], EntityLocomotiveElectric['Electric Locomotive'/1, l='MpServer', x=-944.89, y=145.59, z=-765.50], EntityCartAnchorAdmin['Admin Anchor Cart'/2, l='MpServer', x=-943.36, y=146.96, z=-765.50], EntityChicken['Chicken'/171521, l='MpServer', x=-906.38, y=91.00, z=-754.22], EntityCartBasic['entity.MinecartRideable.name'/3, l='MpServer', x=-941.57, y=148.26, z=-765.50], EntityCreeper['Creeper'/171526, l='MpServer', x=-912.50, y=112.00, z=-790.69], EntityCartBasic['entity.MinecartRideable.name'/4, l='MpServer', x=-939.76, y=148.50, z=-765.51], EntityCartChest['entity.MinecartChest.name'/171527, l='MpServer', x=-907.47, y=38.50, z=-769.50], EntityCartBasic['entity.MinecartRideable.name'/5, l='MpServer', x=-938.03, y=148.50, z=-765.53], EntityLocomotiveElectric['Electric Locomotive'/6, l='MpServer', x=-989.59, y=68.34, z=-716.50], EntityLocomotiveElectric['Electric Locomotive'/7, l='MpServer', x=-989.31, y=67.34, z=-714.97], EntityZombie['Undying Zombie'/171530, l='MpServer', x=-871.03, y=126.00, z=-751.53], EntityCartAnchorAdmin['Admin Anchor Cart'/8, l='MpServer', x=-989.50, y=67.34, z=-713.31], EntityCartChest['entity.MinecartChest.name'/171531, l='MpServer', x=-945.50, y=32.50, z=-809.50], EntityCartBasic['entity.MinecartRideable.name'/9, l='MpServer', x=-988.81, y=67.34, z=-711.88], EntityCartBasic['entity.MinecartRideable.name'/10, l='MpServer', x=-989.50, y=67.34, z=-710.50], EntityItem['item.item.egg'/171529, l='MpServer', x=-905.81, y=77.13, z=-750.72], EntityItem['item.item.rottenFlesh'/175881, l='MpServer', x=-918.78, y=100.13, z=-810.38], EntityXPOrb['Experience Orb'/171535, l='MpServer', x=-887.47, y=43.25, z=-776.44], EntityChicken['Chicken'/171532, l='MpServer', x=-945.44, y=93.00, z=-804.63], EntityChicken['Chicken'/171539, l='MpServer', x=-967.56, y=97.00, z=-813.41], EntityZombie['Zombie'/171537, l='MpServer', x=-879.50, y=128.00, z=-746.91], EntitySkeleton['Skeleton'/171543, l='MpServer', x=-878.50, y=77.00, z=-757.50], EntityChicken['Chicken'/171541, l='MpServer', x=-901.53, y=87.00, z=-800.53], EntityChicken['Chicken'/171547, l='MpServer', x=-879.47, y=61.73, z=-813.53], EntityChicken['Chicken'/171544, l='MpServer', x=-865.47, y=127.00, z=-760.69], EntityCreeper['Creeper'/171545, l='MpServer', x=-878.50, y=69.00, z=-737.50], EntityChicken['Chicken'/171550, l='MpServer', x=-893.75, y=71.00, z=-814.78], EntityItem['item.item.egg'/171551, l='MpServer', x=-889.28, y=101.13, z=-712.44], EntityChicken['Chicken'/171554, l='MpServer', x=-882.50, y=121.00, z=-712.50], EntityCow['Cow'/171555, l='MpServer', x=-879.78, y=68.00, z=-799.56], EntityChicken['Chicken'/171552, l='MpServer', x=-882.50, y=121.00, z=-712.50], EntitySkeleton['Skeleton'/173088, l='MpServer', x=-998.50, y=75.00, z=-706.50], EntityChicken['Chicken'/171553, l='MpServer', x=-882.50, y=121.00, z=-712.50], EntityChicken['Chicken'/171558, l='MpServer', x=-871.41, y=132.00, z=-722.41], EntityCreeper['Creeper'/175910, l='MpServer', x=-929.50, y=71.00, z=-828.50], EntityChicken['Chicken'/171559, l='MpServer', x=-867.31, y=135.00, z=-727.34], EntityCreeper['Creeper'/175909, l='MpServer', x=-932.50, y=71.00, z=-825.50], EntityChicken['Chicken'/171562, l='MpServer', x=-881.59, y=62.36, z=-817.44], EntityChicken['Chicken'/171560, l='MpServer', x=-1011.59, y=69.00, z=-765.47], EntityCreeper['Creeper'/171566, l='MpServer', x=-876.50, y=68.00, z=-800.50], EntityChicken['Chicken'/171564, l='MpServer', x=-873.78, y=62.44, z=-815.16], GCEntityClientPlayerMP['Icebelly'/171518, l='MpServer', x=-940.76, y=161.62, z=-761.30], EntityZombie['Zombie'/175923, l='MpServer', x=-934.50, y=71.00, z=-763.50], EntityChicken['Chicken'/171579, l='MpServer', x=-862.66, y=119.00, z=-743.59], EntitySheep['Sheep'/171576, l='MpServer', x=-861.66, y=119.00, z=-743.47], EntitySheep['Sheep'/171577, l='MpServer', x=-861.13, y=113.00, z=-742.47], EntityChicken['Chicken'/171590, l='MpServer', x=-873.84, y=62.44, z=-816.53], EntityZombie['Zombie'/175431, l='MpServer', x=-936.50, y=68.00, z=-779.50], EntityXPOrb['Experience Orb'/171588, l='MpServer', x=-851.72, y=125.25, z=-790.72], EntityZombie['Zombie'/171594, l='MpServer', x=-881.50, y=90.00, z=-840.50], EntityChicken['Chicken'/171592, l='MpServer', x=-875.19, y=89.00, z=-701.81], EntityZombie['Zombie'/175432, l='MpServer', x=-936.50, y=68.00, z=-780.50], EntityBrainyZombie['Angry Zombie'/175950, l='MpServer', x=-976.50, y=91.00, z=-753.50], EntityBrainyZombie['Angry Zombie'/175949, l='MpServer', x=-976.50, y=91.00, z=-752.50], EntityBat['Bat'/176467, l='MpServer', x=-944.56, y=43.08, z=-744.53], EntityCreeper['Creeper'/172625, l='MpServer', x=-984.50, y=119.00, z=-749.50], EntityBat['Bat'/176468, l='MpServer', x=-941.97, y=38.71, z=-761.46], EntitySpider['Vampiric Spider'/173141, l='MpServer', x=-965.06, y=79.00, z=-760.25], EntityCreeper['Creeper'/175454, l='MpServer', x=-973.50, y=116.00, z=-683.50], EntityCreeper['Creeper'/176736, l='MpServer', x=-967.50, y=95.00, z=-733.50], EntityCreeper['Creeper'/176737, l='MpServer', x=-969.10, y=94.00, z=-740.07], EntityChicken['Chicken'/171620, l='MpServer', x=-992.53, y=85.00, z=-838.72], EntitySkeleton['Skeleton'/174186, l='MpServer', x=-990.50, y=68.00, z=-770.50], EntitySpider['Spider'/174184, l='MpServer', x=-986.38, y=69.00, z=-766.28], EntityChicken['Chicken'/171638, l='MpServer', x=-864.53, y=71.00, z=-839.41], EntityZombie['Zombie'/176756, l='MpServer', x=-1007.50, y=71.00, z=-734.50], EntityZombie['Zombie'/176757, l='MpServer', x=-1007.50, y=71.00, z=-733.50], EntitySkeleton['Skeleton'/176760, l='MpServer', x=-1002.50, y=71.00, z=-734.50], EntitySkeleton['Skeleton'/176761, l='MpServer', x=-1002.50, y=71.00, z=-736.50], EntityChicken['Chicken'/171414, l='MpServer', x=-936.31, y=193.00, z=-779.66], EntityChicken['Chicken'/171415, l='MpServer', x=-929.25, y=208.00, z=-773.34], EntityItem['item.item.egg'/171418, l='MpServer', x=-946.34, y=82.13, z=-725.34], EntityCreeper['Creeper'/172698, l='MpServer', x=-944.00, y=148.00, z=-718.50], EntityChicken['Chicken'/171419, l='MpServer', x=-948.44, y=142.00, z=-733.38], EntityCartChest['entity.MinecartChest.name'/171416, l='MpServer', x=-956.50, y=37.34, z=-735.84], EntityItem['item.item.egg'/171417, l='MpServer', x=-948.88, y=72.13, z=-732.53], EntityItem['item.item.egg'/171422, l='MpServer', x=-971.03, y=69.13, z=-775.13], EntityCreeper['Creeper'/175262, l='MpServer', x=-935.50, y=38.00, z=-760.50], EntityPig['Pig'/171423, l='MpServer', x=-966.53, y=120.00, z=-773.47], EntityChicken['Chicken'/171420, l='MpServer', x=-947.88, y=129.00, z=-729.66], EntityChicken['Chicken'/171421, l='MpServer', x=-976.69, y=69.00, z=-773.53], EntitySkeleton['Skeleton'/171426, l='MpServer', x=-947.06, y=56.00, z=-774.56], EntitySkeleton['Skeleton'/171427, l='MpServer', x=-950.53, y=218.00, z=-761.94], EntityCartChest['entity.MinecartChest.name'/171425, l='MpServer', x=-971.50, y=36.50, z=-763.50], EntityZombie['Zombie'/171431, l='MpServer', x=-942.50, y=76.00, z=-764.50], EntityCartChest['entity.MinecartChest.name'/171429, l='MpServer', x=-1004.50, y=9.34, z=-745.50], EntityChicken['Chicken'/171432, l='MpServer', x=-951.53, y=131.00, z=-706.41], EntityZombie['Zombie'/173228, l='MpServer', x=-866.50, y=85.00, z=-769.50], EntityChicken['Chicken'/171442, l='MpServer', x=-926.84, y=204.01, z=-758.97], EntityItem['item.item.egg'/171443, l='MpServer', x=-927.25, y=210.13, z=-759.13], EntityChicken['Chicken'/171440, l='MpServer', x=-927.69, y=207.00, z=-772.47], EntitySkeleton['Skeleton'/177332, l='MpServer', x=-965.50, y=93.00, z=-743.50], EntitySkeleton['Skeleton'/177333, l='MpServer', x=-969.50, y=93.00, z=-747.50], EntityCreeper['Creeper'/177338, l='MpServer', x=-990.50, y=108.00, z=-753.50], EntityCartChest['entity.MinecartChest.name'/171455, l='MpServer', x=-976.50, y=17.34, z=-640.09], EntityCartChest['entity.MinecartChest.name'/171452, l='MpServer', x=-994.50, y=12.50, z=-622.50], EntityCreeper['Creeper'/177084, l='MpServer', x=-956.53, y=86.00, z=-749.95], EntityZombie['Zombie'/177099, l='MpServer', x=-992.50, y=98.00, z=-726.50], EntityItem['item.item.rottenFlesh'/168142, l='MpServer', x=-987.69, y=90.13, z=-724.97], EntityZombie['Zombie'/176077, l='MpServer', x=-863.50, y=91.00, z=-750.50], EntityCreeper['Creeper'/173267, l='MpServer', x=-1005.50, y=72.00, z=-710.50], EntityZombie['Zombie'/173521, l='MpServer', x=-965.66, y=81.00, z=-700.66], EntityCreeper['Creeper'/173272, l='MpServer', x=-890.56, y=126.00, z=-743.00], EntityBrainyZombie['Angry Zombie'/174302, l='MpServer', x=-985.50, y=115.00, z=-750.50], EntityCartChest['entity.MinecartChest.name'/171502, l='MpServer', x=-1009.50, y=11.34, z=-686.06], EntityItem['item.item.arrow'/175855, l='MpServer', x=-911.81, y=114.13, z=-787.38], EntityItem['item.item.arrow'/176111, l='MpServer', x=-891.19, y=90.13, z=-765.63], EntityItem['item.item.bone'/175857, l='MpServer', x=-912.31, y=115.13, z=-787.84], EntityItem['item.item.bone'/176113, l='MpServer', x=-891.19, y=90.13, z=-765.63], EntityChicken['Chicken'/171519, l='MpServer', x=-925.63, y=13.00, z=-737.44]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2433)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:908)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_31, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1704232784 bytes (1625 MB) / 2479489024 bytes (2364 MB) up to 4080271360 bytes (3891 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn2G
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 15, tallocated: 95
	FML: MCP v9.05 FML v7.10.85.1230 Minecraft Forge 10.13.2.1230 41 mods loaded, 41 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	FML{7.10.85.1230} [Forge Mod Loader] (forge-1.7.10-10.13.2.1230.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Forge{10.13.2.1230} [Minecraft Forge] (forge-1.7.10-10.13.2.1230.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	CodeChickenCore{1.0.4.29} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	<CoFH ASM>{000} [CoFH ASM Data Initialization] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	NotEnoughItems{1.0.3.74} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.3.74-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	ThaumicTinkerer-preloader{0.1} [Thaumic Tinkerer Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	mod_ThreadedLighting{1.7.10-1.0} [Threaded Lighting] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	gilded-games-util{1.7.10-1.0} [Gilded Games Utility] (gilded-games-util-1.7.10-1.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	aether{Alpha 1.7.10-1.0} [Aether II] (aether.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Thaumcraft{4.2.3.4} [Thaumcraft] (Thaumcraft-1.7.10-4.2.3.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	AetherAspects{Alpha 1.7.10-1.0} [Aether Aspects] (AetherAspects-1.7.10-1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	AnimationAPI{1.2.4} [AnimationAPI] (AnimationAPI-1.7.10-1.2.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Backpack{2.0.1} [Backpack] (backpack-2.0.1-1.7.x.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	betterstorage{0.11.3.123} [BetterStorage] (BetterStorage-1.7.10-0.11.3.123.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	BiblioCraft{1.9.2} [BiblioCraft] (BiblioCraft[v1.9.2][MC1.7.10].jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	CoFHCore{1.7.10R3.0.0B9} [CoFH Core] (CoFHCore-[1.7.10]3.0.0B9-40.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	BuildCraft|Core{6.3.1} [BuildCraft] (buildcraft-6.3.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	BuildCraft|Transport{6.3.1} [BC Transport] (buildcraft-6.3.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	BuildCraft|Silicon{6.3.1} [BC Silicon] (buildcraft-6.3.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	BuildCraft|Builders{6.3.1} [BC Builders] (buildcraft-6.3.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	BuildCraft|Energy{6.3.1} [BC Energy] (buildcraft-6.3.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	BuildCraft|Factory{6.3.1} [BC Factory] (buildcraft-6.3.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	BuildCraft|Compat{6.3.0} [BuildCraft Compat] (buildcraft-compat-6.3.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	chocolateQuest{0.0} [Chocolate Quest] (chocolateQuest-1.7.10-BETA2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	eplus{3.0.2-d} [Enchanting Plus] (EnchantingPlus-1.7.10-3.0.2-d.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	GalacticraftCore{3.0.8} [Galacticraft Core] (GalacticraftCore-1.7-3.0.8.257.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	GalacticraftMars{3.0.8} [Galacticraft Planets] (Galacticraft-Planets-1.7-3.0.8.257.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Mantle{1.7.10-0.3.2.jenkins184} [Mantle] (Mantle-1.7.10-0.3.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	MutantCreatures{1.4.8} [Mutant Creatures] (MutantCreatures-1.7.10-1.4.8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Railcraft{9.4.0.0} [Railcraft] (Railcraft_1.7.10-9.4.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	ReiMinimap{1.7.10} [Rei's Minimap] (Reis-Minimap-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	SolarFlux{1.7.10-0.5a} [Solar Flux] (SolarFlux-1.7.10-0.5a.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	ThermalFoundation{1.7.10R1.0.0RC1} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.0.0RC1-13.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	ThermalExpansion{1.7.10R4.0.0B8} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.0.0B8-23.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	TConstruct{1.7.10-1.8.2.build858} [Tinkers' Construct] (TConstruct-1.7.10-1.8.2a.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	ThaumicTinkerer{unspecified} [Thaumic Tinkerer] (ThaumicTinkerer-2.5-1.7.10-162.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	AS_UpdateCheck{1.1.6} [AtomicStryker Update Check Mod] (UpdateCheckerMod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	bspkrsCore{6.15} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.15.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Mantle Environment: Environment healthy.
	TConstruct Environment: Environment healthy.
	Launched Version: 1.7.10-Forge10.13.2.1230
	LWJGL: 2.9.1
	OpenGL: GeForce GT 640/PCIe/SSE2 GL version 4.4.0 NVIDIA 344.11, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by xJonL** [comment]
Yep, party system is broken with that feature atm, we'll fix it asap, thanks for the report

**Comment by aridhol** [comment]
I am here to report this same bug!

I won't repost the report since its already documented but I definitely can confirm its existance, and in the same exact way described above!

**Comment by aridhol** [comment]
Did a check to see if 1.7.10-1.1 fixed this, and it definitely doesn't :) so this one is still around sadly :( no parties until its fixed : /

**Comment by Collin1971** [comment]
Did you update Gilded Games Util to 1.6?
