### ISSUE TITLE
Wrong dungeon

### ISSUE THREAD

**Issue by Eregerog** [gildedgames/aether-issues#398]
I could only generate this bug twice, but randomly the "totem" sends you into a new generated dungeon other than the original. If you re-enter you'll end up in the original dungeon. Additionally, both times I used the same "totem" in the aether dimension and it send me to the exact same wrong dungeon.

**Comment by xJonL** [comment]
When you're not in a party, you'll be sent to your own instance, but when you are in one, you'll be since to a new instance.  Did you make a party at any time?

**Comment by Eregerog** [comment]
No, I played in Singleplayer all the time and didn't even touch the party system

**Comment by xJonL** [comment]
Explain further how to reproduce the issue
