### ISSUE TITLE
Weird terrain gen. Looks like the golden oak biome teased for mutation but no trees.

### ISSUE THREAD

**Issue by roket333** [gildedgames/aether-issues#400]
I found this weird terrain GEN on my server (Fixed the cloud bug BTW
![2015-02-18_05 34 23](https://cloud.githubusercontent.com/assets/5241048/6247303/1b1eeaa4-b730-11e4-9b8b-d40fab766e78.png)
)

**Comment by xJonL** [comment]
That's really strange. Are you running any other mods?

**Comment by roket333** [comment]
no other mods. just aether.

On Wed, Feb 18, 2015 at 9:39 AM, Jon <notifications@github.com> wrote:

> That's really strange. Are you running any other mods?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gildedgames/aether-issues/issues/400#issuecomment-74897350>
> .
>



-- 
http://signaturecraft.us/signatures/eJwrs9OLcnNzEtNLkpMK0kt4ipCE3BIz03MzNFLzs-FSBkbG3OFpCbmKrjlF5UUpRYXKxhxBZfmFWUWp3IZmZqCsQGXAQDJYh4C.png

**Comment by roket333** [comment]
the weirder thing is that what would be holystone/aether dirt is the enchanted overworld grass.

**Comment by roket333** [comment]
Man, I'm a bug finding MACHINE! I should be part of beta testing.

**Comment by xJonL** [comment]
Did you generate a new world? Or did you load a previous world?

**Comment by Collin1971** [comment]
@roket333 Oh trust me, the current beta testers make our lives _hell_. (I'm kidding of course, not about how good they are at finding bugs, though.)

**Comment by Collin1971** [comment]
Closing this issue because it's most likely related to #412. If you have _evidence_ showing otherwise, please re-open this issue.
