### ISSUE TITLE
Request: Add certain things to the oredict for more mod compatibility

### ISSUE THREAD

**Issue by BBoldt** [gildedgames/aether-issues#402]
These shouldn't affect any of your recipes, and would allow a lot of other mods to be able to use the materials from your mod.

logs as 'logWood'
skyroot sticks as 'stickWood'
holystone and holystone bricks as 'holystone' (for compatibility with chisel's holystone)
cold aercloud as 'cloud' (for compatibility with chisel's cloud blocks)

**Comment by roket333** [comment]
or at least allow us to make skyroot item frames and stuff like that

**Comment by Collin1971** [comment]
I'll look into it for ya'. :)

**Comment by Collin1971** [comment]
I've added things such as logWood, plankWood, stairWood, slabWood, treeSaplings, treeLeaves, and the such. I won't be adding oredict entries for Chisel Holystone because it's not the same thing as Aether Holystone from what (very little research) I've done.

**Comment by BBoldt** [comment]
@Collin1971 It actually is the same thing pretty much, it just has a crafting recipe and it sparkles.


![](http://i.imgur.com/DUrKtrr.jpg)
Here is an example of what it looks like compared to aether holystone, it makes sense that you should be able to chisel the aether holystone into all of the neat chisel holystone variations.

**Comment by BBoldt** [comment]
I appreciate that you added those other things to the oredict though. Thank you.

**Comment by Collin1971** [comment]
You make a fair point. I've added the holystone and cloud entries. :)

**Comment by BBoldt** [comment]
woo!

**Comment by Collin1971** [comment]
The changes made for this issue have been _reverted_ in 1.7.10-1.2.

Adding Skyroot Sticks to the Ore Dictionary causes the inability to craft Skyroot Sticks, which seriously hinders the playability of the Aether II.

**Comment by BBoldt** [comment]
That's probably from adding the planks to the oredict, not the sticks.

**Comment by BBoldt** [comment]
@Collin1971 

I kinda did this myself using minetweaker and I didn't run into any of the issues mentioned in that bug report. Everything made of skyroot is still craftable with skyroot materials.

Here is the minetweaker script I made if you're interested:
http://hastebin.com/iqatomenab.hs

**Comment by Collin1971** [comment]
Oops, forgot to update another issue.

We've added back some things to the oredict and changed how we registered some stuff in 1.7.10-1.3 to prevent another silly mistake. :)
