### ISSUE TITLE
Launcher problems

### ISSUE THREAD

**Issue by Pyrospower** [gildedgames/aether-issues#407]
Hello, I'm French, and I have a problem with the launcher : 

http://i.gyazo.com/c55ef74eac07d1f4e2f5acdfb5aee013.png

Can you help me guys ?

**Comment by xJonL** [comment]
Try installing the latest version of Java.  I recommend 64-bit Java if you have a 64 bit computer.

http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html

**Comment by Pyrospower** [comment]
Can I have a 32-bit version, please ?
