### ISSUE TITLE
//drain does not work with aether water

### ISSUE THREAD

**Issue by roket333** [gildedgames/aether-issues#411]
title says it all

**Comment by Collin1971** [comment]
We don't support custom modifications right now, and probably wouldn't be able to fix this anyways, sadly.

Does the //drain command in WorldEdit take a parameter for a block ID?

**Comment by roket333** [comment]
no
just "//drain <radius>"

On Sat, Feb 21, 2015 at 10:34 PM, Collin Soares <notifications@github.com>
wrote:

> We don't support custom modifications right now, and probably wouldn't be
> able to fix this anyways, sadly.
>
> Does the //drain command in WorldEdit take a parameter for a block ID?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gildedgames/aether-issues/issues/411#issuecomment-75420892>
> .
>



-- 
http://signaturecraft.us/signatures/eJwrs9OLcnNzEtNLkpMK0kt4ipCE3BIz03MzNFLzs-FSBkbG3OFpCbmKrjlF5UUpRYXKxhxBZfmFWUWp3IZmZqCsQGXAQDJYh4C.png

**Comment by xJonL** [comment]
Tested with Cauldron, Aether II and WorldEdit.  It works fine  "Aether Water" is basically just normal water with a modified color for the Aether biome.  Try using latest worldedit version if you are not already.

http://dev.bukkit.org/bukkit-plugins/worldedit/files/60-world-edit-6-0/
