### ISSUE TITLE
More weird terrain gen

### ISSUE THREAD

**Issue by roket333** [gildedgames/aether-issues#412]
![2015-02-21_09 16 37](https://cloud.githubusercontent.com/assets/5241048/6314806/6df413a4-b9aa-11e4-8948-653e2584cc10.png)

**Comment by 115kino** [comment]
Are you using an old aether map?

**Comment by roket333** [comment]
nope. brand new.

**Comment by Collin1971** [comment]
This issue could not be reproduced and seems to be an long-standing issue with vanilla.

Perhaps this is a similar issue to https://bugs.mojang.com/browse/MC-315?
