### ISSUE TITLE
Gloves do not show enchantments

### ISSUE THREAD

**Issue by roket333** [gildedgames/aether-issues#414]
![2015-02-21_20 29 50](https://cloud.githubusercontent.com/assets/5241048/6317296/75714ecc-ba08-11e4-8c8b-b6323fee5ed4.png)

**Comment by xJonL** [comment]
This is an issue with accessory renders.

**Comment by Collin1971** [comment]
Gloves don't even have the functionality to be enchanted in the first place, hence why they don't render enchantments.
