### ISSUE TITLE
multiplayer bugs

### ISSUE THREAD

**Issue by Cr0wmaster** [gildedgames/aether-issues#418]
- when going from overwolrd to aether i get disconneted from server

- when leaving a dungeon whole server shuts down

- party system is bit buggy, cant disband existing parties, when someone joins existing party it somehow does not register like beaing in party, party gui shows multiple copies of one player

- when riding moa,phyg or flying cow it looks like mount is facing wrong direction (just when looking on other players)

**Comment by Collin1971** [comment]
_Please_ only report one bug per issue, and check for similar issues before posting.
