### ISSUE TITLE
Too Many Items Slightly alters the placement of item spaces in the accessories

### ISSUE THREAD

**Issue by roket333** [gildedgames/aether-issues#421]

**Comment by Collin1971** [comment]
Could you please provide a screenshot?

**Comment by roket333** [comment]
![2015-02-24_12 56 17](https://cloud.githubusercontent.com/assets/5241048/6357859/a9695102-bc24-11e4-8280-48b01d6e1a9b.png)

**Comment by roket333** [comment]
btw, what would it be to spawn the aether coin entityfor use in /summon?

**Comment by therule2010** [comment]
Well, I think GG will probably fix this, but until then I wouldn't worry too much about this, it's not like it's really gonna hurt the game much, but hey, what do I know?
~rule
