### ISSUE TITLE
Mounts facing wrong direction

### ISSUE THREAD

**Issue by Cr0wmaster** [gildedgames/aether-issues#426]
This happens on multiplayer. When riding moa, phyg or flying cow it looks like mount is facing wrong direction while moving. Client side is ok, but other players see me like im rinding backwards.
Vanilla Horses are ok.

**Comment by Collin1971** [comment]
We believe this issue was fixed in a recent update.

If this issue still occurs on the latest version (1.7.10-1.4 as of writing this), please re-open the issue.
