### ISSUE TITLE
Aerclouds

### ISSUE THREAD

**Issue by Cr0wmaster** [gildedgames/aether-issues#427]
Aercloud (mostly blue Aercloud) does not work when player touches them on connection between blocks. For exapamle formation of 2x2 blue Aercloud does not launch player up when that player hits them from below in between blocks.

**Comment by Collin1971** [comment]
This is intentional so you can walk on groups of clouds and fall through individual clouds. :)

If you feel this should be changed, feel free to re-open the issue with your proposed solution.
