### ISSUE TITLE
lava flows comepletely instantly in >1 second

### ISSUE THREAD

**Issue by roket333** [gildedgames/aether-issues#428]

**Comment by 115kino** [comment]
Please be more specific. What Dimension? Was it on a server?

**Comment by roket333** [comment]
In the aether and on singleplayer and a server

**Comment by 115kino** [comment]
Seems like I am completely unable to reproduce it but this can't just be ignored. We will keep this in mind.

**Comment by roket333** [comment]
Tomorrow I will make a video and link it.

**Comment by 115kino** [comment]
That will be most appreciated. Thank you.

**Comment by roket333** [comment]
Also, when it happens, it makes a big lag spike

**Comment by Collin1971** [comment]
I think a video would be unhelpful as the issue is very easy to understand conceptually.

Could you send us a crash log by forcing a Minecraft crash _after_ you've placed lava in the Aether? To force a crash, simply hold down _F3 + C_ until the game, erhm, crashes.
