### ISSUE TITLE
Change shards of life to check for "shards of life health gain" and persist after death?

### ISSUE THREAD

**Issue by Toerr** [gildedgames/aether-issues#429]
Currently the shards of life only check to see what the PC's current max health is and only allows use if it is <20 hearts. This conflicts with other mods that add max health like Advanced Genetics and Tinker's Construct. With TiCon you can just remove the canisters then use the Shards and replace canisters. With AG, you'd have to wait (or die) to give yourself the iron golem gene until you maxed your shard capacity. Also, they [shard hearts] don't persist after death. Don't know if they were supposed to. Some of this information is on the wiki, but not all, so I thought it bore explaining here.
Edit: Forgot to put "request" in title and couldn't figure out how to add a label...

**Comment by 115kino** [comment]
We will try our best to see if we can fix this issue.

**Comment by Razorskills** [comment]
This is also a issue for me, and I would really love for a config to possibly allow disabling of the shards effects. Or maybe a way to limit how high someones health can get. Currently people can run around with 100 hp if they collect all of the shards to max, then collect all the tinkers construct health additions. It really becomes overpowered against a new player.

There is also no way of removing the shards from a player that I know of without editing the player.dat file. Hopefully in the future some of these things can be possible.
Really loving the mod though. Amazing stuff.

**Comment by Toerr** [comment]
Actually the Green Canisters from TiCon aren't available in survival, so the current max from that mod is 60hp, coupled with the current gain from the shards (20hp) only gives you a max 80hp possible. Plus the Yellow hearts only drop from bosses, and shards of life can only be found in gold dungeons, so if your players make it that far, it sounds like they deserve the extra health. Just sayin'.

**Comment by Collin1971** [comment]
We believe we've fixed how Life Shards work now in the next release. If the issue still persists with other mods in 1.7.10-1.2, feel free to re-open the issue.
