### ISSUE TITLE
Aerbunny spawn portals

### ISSUE THREAD

**Issue by babybasher** [gildedgames/aether-issues#430]
Jumping off the Aether into the overworld when wearing an Aerbunny will create a new portal at the location, on the ground, you enter the overworld in. 
I've had to remove the mod coz of this, which sucks coz my daughter loves it so far.  Furthermore she loves jumping off the world with a bunny :(  

If this is a 'feature', can we have an option to disable portal creation not done on purpose by the player?  I don't want random portals all over my world haha :P

Thanks for such a great mod too, very polished!

Edit:  If its any help, when the player leaves the aether wearing a bunny (floating down) the server console displays the message:

"[20:33:40] [Server thread/WARN]: Fetching addPacket for removed entity"

This message isn't displayed when jumping off the aether WITHOUT a bunny.

**Comment by Collin1971** [comment]
Caused by #384.
