### ISSUE TITLE
Client-only crash on server due to conflict with Just Another Spawner (JAS)

### ISSUE THREAD

**Issue by GrinningMoon** [gildedgames/aether-issues#434]
Using a Forge 1291 Server and Client, with only Aether II, gilded_util, and JAS installed, I get a client-only crash (server just says player disconnected) when I arrive in the Aether due to a Ticking Entity exception. Looking through the crash report (which I don't have with me atm, I'll post later), it looks like natural spawning Aether II mobs are causing it.

- Disabling the Aether biome in JAS does nothing.
- Setting it so mobs can't spawn via the Aether II config doesn't help
- Setting it so mobs can't spawn in both the Aether II config and via JAS works but there are no mobs..

I realize this isn't much to go on without a crash report. I will update this post ASAP.

Edit:
Here's the log.
http://pastebin.com/4sPHVNnh

**Comment by Collin1971** [comment]
This seems to be an issue with JAS not understanding Aether entities.

Perhaps you could create an issue over at [JAS's issues tracker](https://github.com/ProjectZulu/JustAnotherSpawner/issues)?

**Comment by GrinningMoon** [comment]
Thanks for the reply! Posted it on their github, hopefully I'll get an answer...

**Comment by GrinningMoon** [comment]
Forgot to close this. Crudedragos (JAS dev) released an update to fix this.
