### ISSUE TITLE
Aether Achievements Screen Crash [1.7.10 - 1.1]

### ISSUE THREAD

**Issue by BakuMinerGuy** [gildedgames/aether-issues#435]
When you try to scroll up further than the Aether's achievements screen allows, the game crashes.

https://gist.github.com/Collin1971/fd318ad5b658c936a1cb

(Edited by @Collin1971-- put crash log into a gist)

**Comment by Collin1971** [comment]
Should be simple to fix. We'll look into it. :)

**Comment by Collin1971** [comment]
Could you try to reproduce this bug with _only_ the Aether installed?

**Comment by BakuMinerGuy** [comment]
Extensive testing has shown that the bug can't be reproduced with just the Aether installed, but can be reproduced after installing Legend Gear 2.  Mod site here: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2198530-legendgear-2-version-2-b-2-updated-2-22-2015
