### ISSUE TITLE
String crashes player

### ISSUE THREAD

**Issue by Pepperx3** [gildedgames/aether-issues#436]
When stepping on string in the Aether you will get an Internal Server error in Multiplayer and will crash your game in Singleplayer

**Comment by xJonL** [comment]
We've fixed this in 1.7.10-1.1, are you running the latest Aether?

**Comment by Collin1971** [comment]
Could you please provide a crash log?

**Comment by Collin1971** [comment]
Fixed in 1.7.10-1.2.
