### ISSUE TITLE
Slider boss still breaks dungeon. 

### ISSUE THREAD

**Issue by typervader** [gildedgames/aether-issues#442]
I don't know if he should be able to break his dungeon room blocks. While he doesn't move weridly anymore, its still a pain to fight him like this.

**Comment by roket333** [comment]
He purposely does that.

**Comment by Collin1971** [comment]
This is intentional.

**Comment by typervader** [comment]
Oh, was not aware of this. The old versions he was not able to so I was not sure if it was a bug or not. Thanks for clearing it up.
