### ISSUE TITLE
Crash Report on Cauldron Server Happening Frequently

### ISSUE THREAD

**Issue by Amaxter** [gildedgames/aether-issues#443]
---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 2/28/15 11:14 AM
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at net.aetherteam.aether.tile_entities.TileEntityIncubator.func_145845_h(TileEntityIncubator.java:222)
	at net.minecraft.world.World.func_72939_s(World.java:2491)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:669)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:943)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.aetherteam.aether.tile_entities.TileEntityIncubator.func_145845_h(TileEntityIncubator.java:222)

-- Block entity being ticked --
Details:
	Name: Incubator // net.aetherteam.aether.tile_entities.TileEntityIncubator
	Block type: ID #1376 (tile.incubator // net.aetherteam.aether.blocks.BlockIncubator)
	Block data value: 4 / 0x4 / 0b0100
	Block location: World: (-799,72,-365), Chunk: (at 1,4,3 in -50,-23; contains blocks -800,0,-368 to -785,255,-353), Region: (-2,-1; contains chunks -64,-32 to -33,-1, blocks -1024,0,-512 to -513,255,-1)
	Actual block type: ID #1376 (tile.incubator // net.aetherteam.aether.blocks.BlockIncubator)
	Actual block data value: 4 / 0x4 / 0b0100
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:2491)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:669)

-- Affected level --
Details:
	Level name: world
	All players: 25 total; [EntityPlayerMP['NoShana_'/348, l='world', x=-1723.94, y=81.00, z=-650.79](NoShana_ at -1723.9368839753367,81.0,-650.7872776340907), EntityPlayerMP['DestroyerMB'/350, l='world', x=-63.50, y=71.00, z=363.50](DestroyerMB at -63.5,71.0,363.5), EntityPlayerMP['BlueHaze33'/615, l='world', x=-68.70, y=71.00, z=362.10](BlueHaze33 at -68.69999998807904,71.0,362.0976974056849), EntityPlayerMP['enlion101'/1013, l='world', x=1541.21, y=76.25, z=-1125.84](enlion101 at 1541.2102830881784,76.24918707874468,-1125.835919254377), EntityPlayerMP['IIstardustII'/1558, l='world', x=-4861.30, y=62.78, z=2628.08](IIstardustII at -4861.300000011921,62.778248220429724,2628.078112962889), EntityPlayerMP['TreyBlazer95'/1461, l='world', x=10308.45, y=56.00, z=9911.63](TreyBlazer95 at 10308.448505091634,56.0,9911.63469845719), EntityPlayerMP['BRE77'/1557, l='world', x=-1722.70, y=81.00, z=-653.28](BRE77 at -1722.695279564742,81.0,-653.2841527160684), EntityPlayerMP['cbshish123'/2458, l='world', x=-349.50, y=31.00, z=4039.36](cbshish123 at -349.5022590487337,31.0,4039.3593257887587), EntityPlayerMP['lyky_bloodpaw'/2802, l='world', x=-412.12, y=64.00, z=-3555.73](lyky_bloodpaw at -412.12447560263524,64.0,-3555.733147022984), EntityPlayerMP['TidalWarrior18'/3392, l='world', x=3369.76, y=69.00, z=-1345.81](TidalWarrior18 at 3369.762499988079,69.0,-1345.8135230948594), EntityPlayerMP['CrazyphoeniXX6'/3883, l='world', x=3610.90, y=65.00, z=-7062.90](CrazyphoeniXX6 at 3610.9007455791325,65.0,-7062.898510170049), EntityPlayerMP['King_Sombra'/3860, l='world', x=176.14, y=73.00, z=2075.70](King_Sombra at 176.13743088591835,73.0,2075.7007933554237), EntityPlayerMP['bendic_j'/4044, l='world', x=633.84, y=83.00, z=-3852.05](bendic_j at 633.8425791598044,83.0,-3852.0499624495446), EntityPlayerMP['HanaNoTenshi'/4607, l='world', x=-63.93, y=172.00, z=362.93](HanaNoTenshi at -63.92500001192097,172.0,362.92500001192093), EntityPlayerMP['flash314'/2424, l='world', x=2830.28, y=64.59, z=-2163.31](flash314 at 2830.279609151125,64.58941599040367,-2163.313626077676), EntityPlayerMP['negativitys'/4751, l='world', x=-4990.10, y=71.00, z=2570.06](negativitys at -4990.10012952129,71.0,2570.0553344857663), EntityPlayerMP['Rerecrosz'/6047, l='world', x=-6026.70, y=77.00, z=6498.34](Rerecrosz at -6026.699999988079,77.0,6498.337597252265), EntityPlayerMP['Creep1999'/6090, l='world', x=850.25, y=50.00, z=4264.68](Creep1999 at 850.254480983421,50.0,4264.677460767329), EntityPlayerMP['cougarman333'/6893, l='world', x=-5062.22, y=136.00, z=2557.73](cougarman333 at -5062.221414314794,136.0,2557.7252684996524), EntityPlayerMP['Kimx600'/8159, l='world', x=-2225.96, y=98.00, z=-903.57](Kimx600 at -2225.962951363305,98.0,-903.5688316789629), EntityPlayerMP['FunPiggy'/9530, l='world', x=-617.60, y=64.00, z=204.26](FunPiggy at -617.6047781177177,64.0,204.26143418681286), EntityPlayerMP['GlitchClick'/9865, l='world', x=-3813.95, y=65.00, z=-2194.74](GlitchClick at -3813.951572652232,65.0,-2194.7379048969415), EntityPlayerMP['Shrekislife'/12200, l='world', x=-2121.55, y=63.00, z=3009.63](Shrekislife at -2121.546811560778,63.0,3009.634196188496), EntityPlayerMP['flamingcreeper28'/6898, l='world', x=-65.71, y=172.00, z=364.39](flamingcreeper28 at -65.7081688180782,172.0,364.38522023162557), EntityPlayerMP['MrDerpio'/13496, l='world', x=-723.50, y=85.00, z=-208.50](MrDerpio at -723.5,85.0,-208.5)]
	Chunk stats: ServerChunkCache: 8892 Drop: 0
	Level seed: -2622730017212790447
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-66,172,364), Chunk: (at 14,10,12 in -5,22; contains blocks -80,0,352 to -65,255,367), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 67886069 game time, 68561223 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 26661 (now: false), thunder time: 9511 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:943)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Linux (amd64) version 3.10.23-xxxx-std-ipv6-64
	Java Version: 1.8.0_31, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 9278711416 bytes (8848 MB) / 13513523200 bytes (12887 MB) up to 15271460864 bytes (14564 MB)
	JVM Flags: 2 total; -Xms8G -Xmx16G
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 33659, allocated: 12, tallocated: 94
	FML: MCP v9.05 FML v7.10.85.1286 git-Cauldron-MCPC-Plus-1.7.10-1.1240.06.213 (MC: 1.7.10) (API v1.7.10-R0.1-SNAPSHOT) Minecraft Forge 10.13.2.1286 68 mods loaded, 68 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	FML{7.10.85.1286} [Forge Mod Loader] (cauldron.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Forge{10.13.2.1286} [Minecraft Forge] (cauldron.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	CodeChickenCore{1.0.4.35} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ivtoolkit{IvToolkit} [1.0.3] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	NotEnoughItems{1.0.4.83} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.4.83-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	mod_ThreadedLighting{1.7.10-1.0} [Threaded Lighting] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	gilded-games-util{1.7.10-1.0} [Gilded Games Utility] (gilded-games-util-1.7.10-1.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	bspkrsCore{6.15} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.15.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	CrystalWing{1.7.10.r02} [CrystalWing] ([1.7.10]CrystalWing-universal-1.7.10.r02.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Treecapitator{1.7.10} [Treecapitator] ([1.7.10]Treecapitator-universal-2.0.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ChickenShed{1.1.3} [Chicken Shed] ([1.7.2] ChickenShed (v1.1.3).jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	adventurebackpack{1.7.10-0.8b} [Adventure Backpack] (adventurebackpack-1.7.10-0.8b.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	aether{Alpha 1.7.10-1.1} [Aether II] (aether.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	betterrain{0.15} [Better Rain] (betterrain-1.7.2-1.7.10_0.15.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	betterrecords{1.7.10-1.1.9} [Better Records] (betterrecords-1.7.10-1.1.9.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BiblioCraft{1.9.2} [BiblioCraft] (BiblioCraft[v1.9.2][MC1.7.10].jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ExtrabiomesXL{3.16.0} [ExtrabiomesXL] (extrabiomesxl_1.7.10-3.16.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BiblioWoodsEBXL{1.4} [BiblioWoods ExtraBiomesXL Edition] (BiblioWoods[ExtraBiomesXL][v1.4].jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	CarpentersBlocks{3.3.5} [Carpenter's Blocks] (Carpenter's Blocks v3.3.5 - MC 1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Thaumcraft{4.2.3.5} [Thaumcraft] (Thaumcraft-1.7.10-4.2.3.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	TwilightForest{2.3.3} [The Twilight Forest] (twilightforest-1.7.10-2.3.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	chisel{2.3.7.34} [Chisel 2] (Chisel2-2.3.7.34.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	colourfulportalsmod{1.4.2} [Colourful Portals] (ColourfulPortals-1.4.2_for_1.7.X.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	lootablebodies{1.3.2} [DrCyano's Lootable Bodies] (CyanosLootableBodies-1.3.2-backport.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	DeadlyWorld{1.0.2} [Deadly World] (DeadlyWorld-1.7.10-1.0.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	CavesAPI{1.0} [Caves API] (ElementalCaves-1.7.2-1.1.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ElementalCaves{1.7.2-1.1.3} [Elemental Caves] (ElementalCaves-1.7.2-1.1.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	FlatSigns{2.1.0.19} [Flat Signs] (FlatSigns-1.7.10-universal-2.1.0.19.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ganysend{1.8.8} [Gany's End] (Ganys End-1.8.8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ganysnether{1.7.8} [Gany's Nether] (Ganys Nether-1.7.8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ganyssurface{1.9.5} [Gany's Surface] (Ganys Surface-1.9.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Growthcraft{2.1.0a} [Growthcraft] (growthcraft-core-1.7.10-2.1.0a.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Growthcraft|Cellar{2.1.0a} [Growthcraft Cellar] (growthcraft-cellar-1.7.10-2.1.0a.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Growthcraft|Apples{2.1.0} [Growthcraft Apples] (growthcraft-apples-1.7.10-2.1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Growthcraft|Bamboo{2.1.0} [Growthcraft Bamboo] (growthcraft-bamboo-1.7.10-2.1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Growthcraft|Bees{2.1.0} [Growthcraft Bees] (growthcraft-bees-1.7.10-2.1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Growthcraft|Fishtrap{2.1.0a} [Growthcraft Fishtrap] (growthcraft-fishtrap-1.7.10-2.1.0a.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Growthcraft|Grapes{2.1.0} [Growthcraft Grapes] (growthcraft-grapes-1.7.10-2.1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Growthcraft|Hops{2.1.0} [Growthcraft Hops] (growthcraft-hops-1.7.10-2.1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Growthcraft|Rice{2.1.0a} [Growthcraft Rice] (growthcraft-rice-1.7.10-2.1.0a.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	HopperDuctMod{1.3.2} [Hopper Ducts] (hopperductmod-1.7.10-1.3.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	iChunUtil{4.1.3} [iChunUtil] (iChunUtil-4.1.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	inventorytweaks{1.58-147-645ca10} [Inventory Tweaks] (InventoryTweaks-1.58-147.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	wuppy29_jellycubes{1.12.6} [Jelly Cubes] (Jelly Cubes 1.7.10-1.12.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	wuppy29_koi{1.11.2} [Koi] (Koi 1.7.10-1.11.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Mantle{1.7.10-0.3.2.jenkins184} [Mantle] (Mantle-1.7.10-0.3.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	modularsystemsapi{0.0.1} [Modular Systems API] (Modular Systems-1.7.10-1.7.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	modularsystems{1.7.1} [Modular Systems] (Modular Systems-1.7.10-1.7.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	wuppy29_nethereye{1.4.1} [Nether Eye] (Nether Eye 1.7.10-1.4.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ObsidiPlates{3.0.0.18} [ObsidiPlates] (ObsidiPlates-1.7.10-universal-3.0.0.18.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	PetBat{1.3.6} [Pet Bat] (PetBat-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Ping{%MOD_VERSION} [Ping] (Ping-1.7.X-1.0.2.B6-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	progressiveautomation{1.5.24} [Progressive Automation] (ProgressiveAutomation-1.7.10-1.5.24.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	reccomplex{0.9.4} [Recurrent Complex] (RecurrentComplex-0.9.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	RedstonePasteMod{1.6.2} [Redstone Paste] (RedstonePasteMod-1.7.10-1.6.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Roguelike{1.3.6} [Roguelike Dungeons] (roguelike-1.7.10-1.3.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	RopesPlus{1.6.3} [Ropes+] (RopePlus-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Shatter{4.0.0} [Shatter] (Shatter-4.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	shipwrecks_winslow{1.6.2} [Shipwrecks!] (shipwrecks_winslow-1.7.10-1.6.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	SpecialMobs{3.0.3} [Special Mobs] (SpecialMobs-1.7.10-3.0.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	supercraftingframe{1.7.10.3} [Super Crafting Frame] (supercraftingframe-1.7.10.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	TConstruct{1.7.10-1.8.2.build858} [Tinkers' Construct] (TConstruct-1.7.10-1.8.2a.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	tradeboothmod{1.7.10.1} [Trade Booth Mod] (tradebooth.1.7.10.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	UtilityMobs{3.1.1} [Utility Mobs] (UtilityMobs-1.7.10-3.1.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	VanillaPlus{1.4.4} [VanillaPlus] (VanillaPlus-1.7.10-1.4.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	weaponmod{v1.14.3} [Balkon's WeaponMod] (weaponmod-1.14.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Mantle Environment: DO NOT REPORT THIS CRASH! Unsupported mods in environment: bukkit
	TConstruct Environment: Environment healthy.
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 27 / 50; [EntityPlayerMP['NoShana_'/348, l='world', x=-1723.94, y=81.00, z=-650.79](NoShana_ at -1723.9368839753367,81.0,-650.7872776340907), EntityPlayerMP['DestroyerMB'/350, l='world', x=-63.50, y=71.00, z=363.50](DestroyerMB at -63.5,71.0,363.5), EntityPlayerMP['BlueHaze33'/615, l='world', x=-68.70, y=71.00, z=362.10](BlueHaze33 at -68.69999998807904,71.0,362.0976974056849), EntityPlayerMP['enlion101'/1013, l='world', x=1541.21, y=76.25, z=-1125.84](enlion101 at 1541.2102830881784,76.24918707874468,-1125.835919254377), EntityPlayerMP['IIstardustII'/1558, l='world', x=-4861.30, y=62.78, z=2628.08](IIstardustII at -4861.300000011921,62.778248220429724,2628.078112962889), EntityPlayerMP['TreyBlazer95'/1461, l='world', x=10308.45, y=56.00, z=9911.63](TreyBlazer95 at 10308.448505091634,56.0,9911.63469845719), EntityPlayerMP['BRE77'/1557, l='world', x=-1722.70, y=81.00, z=-653.28](BRE77 at -1722.695279564742,81.0,-653.2841527160684), EntityPlayerMP['cbshish123'/2458, l='world', x=-349.50, y=31.00, z=4039.36](cbshish123 at -349.5022590487337,31.0,4039.3593257887587), EntityPlayerMP['lyky_bloodpaw'/2802, l='world', x=-412.12, y=64.00, z=-3555.73](lyky_bloodpaw at -412.12447560263524,64.0,-3555.733147022984), EntityPlayerMP['RookSlimeKnight'/2585, l='DIM4', x=16008.87, y=29.00, z=32.91](RookSlimeKnight at 16008.868084162801,29.0,32.910968568404286), EntityPlayerMP['TidalWarrior18'/3392, l='world', x=3369.76, y=69.00, z=-1345.81](TidalWarrior18 at 3369.762499988079,69.0,-1345.8135230948594), EntityPlayerMP['CrazyphoeniXX6'/3883, l='world', x=3610.90, y=65.00, z=-7062.90](CrazyphoeniXX6 at 3610.9007455791325,65.0,-7062.898510170049), EntityPlayerMP['King_Sombra'/3860, l='world', x=176.14, y=73.00, z=2075.70](King_Sombra at 176.13743088591835,73.0,2075.7007933554237), EntityPlayerMP['bendic_j'/4044, l='world', x=633.84, y=83.00, z=-3852.05](bendic_j at 633.8425791598044,83.0,-3852.0499624495446), EntityPlayerMP['HanaNoTenshi'/4607, l='world', x=-63.93, y=172.00, z=362.93](HanaNoTenshi at -63.92500001192097,172.0,362.92500001192093), EntityPlayerMP['flash314'/2424, l='world', x=2830.28, y=64.59, z=-2163.31](flash314 at 2830.279609151125,64.58941599040367,-2163.313626077676), EntityPlayerMP['negativitys'/4751, l='world', x=-4990.10, y=71.00, z=2570.06](negativitys at -4990.10012952129,71.0,2570.0553344857663), EntityPlayerMP['neatherman999'/5093, l='DIM7', x=397.21, y=39.00, z=4182.96](neatherman999 at 397.214749500559,39.0,4182.955278040531), EntityPlayerMP['Rerecrosz'/6047, l='world', x=-6026.70, y=77.00, z=6498.34](Rerecrosz at -6026.699999988079,77.0,6498.337597252265), EntityPlayerMP['Creep1999'/6090, l='world', x=850.25, y=50.00, z=4264.68](Creep1999 at 850.254480983421,50.0,4264.677460767329), EntityPlayerMP['cougarman333'/6893, l='world', x=-5062.22, y=136.00, z=2557.73](cougarman333 at -5062.221414314794,136.0,2557.7252684996524), EntityPlayerMP['Kimx600'/8159, l='world', x=-2225.96, y=98.00, z=-903.57](Kimx600 at -2225.962951363305,98.0,-903.5688316789629), EntityPlayerMP['FunPiggy'/9530, l='world', x=-617.60, y=64.00, z=204.26](FunPiggy at -617.6047781177177,64.0,204.26143418681286), EntityPlayerMP['GlitchClick'/9865, l='world', x=-3813.95, y=65.00, z=-2194.74](GlitchClick at -3813.951572652232,65.0,-2194.7379048969415), EntityPlayerMP['Shrekislife'/12200, l='world', x=-2121.55, y=63.00, z=3009.63](Shrekislife at -2121.546811560778,63.0,3009.634196188496), EntityPlayerMP['flamingcreeper28'/6898, l='world', x=-65.71, y=172.00, z=364.39](flamingcreeper28 at -65.7081688180782,172.0,364.38522023162557), EntityPlayerMP['MrDerpio'/13496, l='world', x=-723.50, y=85.00, z=-208.50](MrDerpio at -723.5,85.0,-208.5)]
	Is Modded: Definitely; Server brand changed to 'cauldron,craftbukkit,mcpc,fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by Amaxter** [comment]
Oh if it helps I should also note using Dinnerbone's chunk converter and deleting the affected chunk solves the issue but then it reoccurs sometime later down the line inevitably.

**Comment by Collin1971** [comment]
We think we've fixed the issue.

It appears Cauldron was invalidating the tile entity's "last used player" and crashing when it tried giving achievements.
