### ISSUE TITLE
Aerbunnies

### ISSUE THREAD

**Issue by Fightr2021** [gildedgames/aether-issues#447]
If you're wearing an Aerbunny, and go in water, it gets off your head. Also if you are in a 2 block high room and try to get it off, you simply can't.

**Comment by Cr0wmaster** [comment]
Aerbunnies also swim very fast

**Comment by xJonL** [comment]
Poor things, their little hearts are probably terrifed of the water, so they try their hardest to survive...

**Comment by Collin1971** [comment]
> If you're wearing an Aerbunny, and go in water, it gets off your head.

This is intentional.

> Also if you are in a 2 block high room and try to get it off, you simply can't.

I'll look into this. :)

**Comment by Collin1971** [comment]
Wow, I've really been forgetting to update some issues.

We've fixed the issue by making Aerbunnies fall off if they collide into the block above you, as it seems more logical. (for example. walking into a 1x2 gap will make them fall off)
