### ISSUE TITLE
Holystone furnance

### ISSUE THREAD

**Issue by Cr0wmaster** [gildedgames/aether-issues#450]
I dont know if that block will stay in the game but right now, when You smelt somethiing in it, all torches have blue flames.

**Comment by xJonL** [comment]
Really cool bug.

**Comment by Collin1971** [comment]
Could you please _force a Minecraft crash_ by holding down F3+C for 10
seconds whilst your smelting something and upload the log? (Github Gist or
Pastebin is fine)

**Comment by Cr0wmaster** [comment]
https://gist.github.com/c325d05b034a4e9a3908.git

**Comment by Cr0wmaster** [comment]
https://gist.github.com/Cr0wmaster/c325d05b034a4e9a3908#file-gistfile1-txt
