### ISSUE TITLE
Step assist issue

### ISSUE THREAD

**Issue by BiwaShiwaBiwa** [gildedgames/aether-issues#452]
I know that you guys state that mod compatibility isn't your top priority, but I just thought I'd mention Aether II 1.7.10-1.1 and/or GildedGamesUtil somehow prevents step assist with both Botania's sashes and TiCon's Traveler's gear, but strangely enough does not prevent Thaumcraft's Boots of the Traveler's step assist.

I tested this with the latest versions of Botania and TiCon, both individually and together alongside the latest Aether II and GildedGamesUtil and Forge 10.13.2.1307.  Besides the sashes not stepping up, everything has been very smooth.

**Comment by xJonL** [comment]
With 1.7.10, we've been trying to have as much mod compatibility. We actually know one of the developers of botania, maybe she can look into the issue as well if it's not us.  But, thanks for the report. :heart_eyes:

**Comment by BiwaShiwaBiwa** [comment]
And it has been extremely compatible with other mods as far as I've seen.  I've had the Aether II working with over 140 other mods together very nicely indeed with ^^^ that issue being the only thing that I considered 'bugged'.  Should I get in touch with Vazkii then, too?

**Comment by xJonL** [comment]
Yeah, go ahead an contact Vazkii. :palm_tree:

**Comment by BiwaShiwaBiwa** [comment]
Vazkii has investigated and concluded it was an issue at the Aether end. Hope that helps and this can be fixed!

**Comment by roket333** [comment]
perhaps use the code of minecraft's horse to detect when to auto-step?

On Tue, Mar 3, 2015 at 10:29 AM, BiwaShiwaBiwa <notifications@github.com>
wrote:

> Vazkii has investigated and concluded it was an issue at the Aether end.
> Hope that helps and this can be fixed!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gildedgames/aether-issues/issues/452#issuecomment-76992427>
> .
>



-- 
http://signaturecraft.us/signatures/eJwrs9OLcnNzEtNLkpMK0kt4ipCE3BIz03MzNFLzs-FSBkbG3OFpCbmKrjlF5UUpRYXKxhxBZfmFWUWp3IZmZqCsQGXAQDJYh4C.png

**Comment by Toerr** [comment]
It's interesting that it works with the original BotT, because I noticed step-assist didn't function with Thaumic Tinkerer's KAMI Boots of the Horizontal Shield. Have not tested with EMT's Nano/Quantum Boots.

**Comment by Collin1971** [comment]
It appears our step-up-code-thingy is doing some sneaky stuff... I have a lot of backlog to do right now, but I'll try to take a look at it.

**Comment by BiwaShiwaBiwa** [comment]
Hey guys, did you manage to look at the step-up-code-thingy?

**Comment by CandiceJoy** [comment]
Issue still present in 1.4 with TE ID patch.  This breaks Botania sashes' and Thaumcraft boots' step-assist functionality and several of my users have noticed it and mentioned it to me.

**Comment by piano1997** [comment]
Same thing with Draconic Evolution Step assist :(

**Comment by Collin1971** [comment]
We've fixed the issue in the next release of the Aether.
