### ISSUE TITLE
Crash when changing tabs in creative

### ISSUE THREAD

**Issue by l3CY** [gildedgames/aether-issues#453]
Section of crash found here http://pastebin.com/87WjQJb5

When exploring through the creative mod tabs, the mod occasionally causes a crash.

**Comment by Collin1971** [comment]
Please do not crop sections out of the crash logs or your issue _will be ignored_.

**Comment by xJonL** [comment]
@l3CY A full crash would be nice if you still have that. Also are you running any other mods?

**Comment by Collin1971** [comment]
This issue is over a month old and doesn't contain enough details to help us figure out what's wrong.

If this issue still occurs in the latest version (1.7.10-1.4) and you have more details, feel free to re-open the issue. :smile:
