### ISSUE TITLE
Cannot Craft Skyroot Blocks and Tools

### ISSUE THREAD

**Issue by Edward-of-Wolperting** [gildedgames/aether-issues#454]
While playing a modded Minecraft in 1.7.10, I encountered a problem with getting started in the Aether II. When I tried to craft things, I couldn't, as I was never allowed to even craft a Skyroot crafting table.

The mods I am using are as follows:

Tinker's Construct
Thaumcraft 3
Buildcraft
Backpacks
Clay Soldiers
Ropes+
Rei's Minimap
Aether II

Here's some screenshots of the problem occuring:

http://i.imgur.com/WL0Sc9c.png

http://i.imgur.com/zSbYdsV.png

**Comment by xJonL** [comment]
We've fixed this in the next patch of Aether, the issue was #444
