### ISSUE TITLE
Leaves decay after placment

### ISSUE THREAD

**Issue by Cr0wmaster** [gildedgames/aether-issues#457]
Leaves (green skyroot leaves and probably other) decay after they are placed by player (after some time).

**Comment by xJonL** [comment]
This is how leaves work when they're not near logs.

**Comment by aeryk17aj** [comment]
That's how they are if they are world-generated or sapling-grown, but they shouldn't decay if they are placed by the player like how vanilla leaf blocks do

**Comment by Cr0wmaster** [comment]
aeryk17aj is right. In addition golden oak leaves and probaly rest of the ather leaves dont burn. (cant set them on fire)

**Comment by Collin1971** [comment]
Fixed! :)
