### ISSUE TITLE
Zelda Sword Skill Mod and Tinkerers Mod Extra Heart containers cause health Skyrocket and retain out of Aether

### ISSUE THREAD

**Issue by CherryHotaling** [gildedgames/aether-issues#459]
Hello,
It seems that if someone has ANY extra hearts from the heart containers in the Zelda sword skills mod or tinkerers construct mod they regen health in the Aether WELL past normal. If they have One heart they gain a whole extra bar of life, two hearts 2 full burs of life and so on.

Is there a way to turn this off or fix it in the config file?

BTW LOVING The Aether mod its fantastic!

**Comment by CherryHotaling** [comment]
I had to disable it on my server for now , someone was up to 900 health, I tried it with all the other mods off. Not a problem but once i added tinkerers mod and/or Iguanas Tinker Tweaks, or Zelda Sword Skills and step into the Aether your hearts start going up. 
Really really love this mod and disabling it on my server is not what I wanted to do so if there is anything I can do to help let me know!

**Comment by jochuan** [comment]
this is happening to me too when i am on survival them i go to creative i gain more 3 health bars

**Comment by CherryHotaling** [comment]
Yeah this was happening in the Aether for us too, if we were fully fed (No hunger)  our hearts would slowly rise to a crazy amount depending on how many additional heart containers we had.

**Comment by jochuan** [comment]
![2015-03-16_09 17 56](https://cloud.githubusercontent.com/assets/11268912/6666155/4e45340c-cbc0-11e4-9967-80f24828323e.png)

**Comment by Jaitsu** [comment]
Even if it's not possible to fix this entirely before the 1.8 update, I'd be eternally grateful for at least a config option to disable Aether's interactions with maximum health in general. I've been dying to stick The Aether on my server for months, but the other mods aren't likely to all update to 1.8 in the forseeable future.

**Comment by CherryHotaling** [comment]
A config option would be perfect to disable whatever item is causing this issue. So many people on my server are dying to have this mod on our server. We dont see moving to 1.8 for a very very long time.
Loved playing this mod for the short time we did and I check back every day to see if there is an update hehe.

**Comment by CherryHotaling** [comment]
Does 1.7.10-1.3 fix this issue? I dont see it on the bug fix list, just says and much more fixes.

**Comment by CherryHotaling** [comment]
Tested 1.7.10-1.3 Its not fixed yet. :( Every time i go back and forth through the portal I have more and more base health.
If there is anything I can help supply like logs etc to help please let me know!

**Comment by xJonL** [comment]
This patch we didn't do anything for other mods.  Another one of our developers have been doing things for mods like this for Aether to be compatible with. I'll show him what's up.

**Comment by jochuan** [comment]
all we have to do is wait until we get a reply

**Comment by CherryHotaling** [comment]
xJonL thank you very much!

**Comment by CherryHotaling** [comment]
xJonL,
Will they be releasing the compatible version on the main site or is there a forum post i should be keeping an eye on?

Thanks

**Comment by xJonL** [comment]
@CherryHotaling Once we get into fixing some more compatibility issues, they'll be available to download on http://www.AetherII.com

**Comment by CherryHotaling** [comment]
Thanks xJonL you rock!

**Comment by CherryHotaling** [comment]
Did 1.4 Fix this issue? I cant check this second but it said some health fixes, so I was not sure.

**Comment by Razorskills** [comment]
It solved my issues with tinkers construct canisters completely. all players will odd health were automatically fixed and it has not had any issues with changing their health upon teleport anymore :) hopefully this will be the same with Zelda Sword Skill Mod

**Comment by Collin1971** [comment]
@115kino was the one who fixed the issue, props to him. :)
