### ISSUE TITLE
Aether II Dungeon Boss Bug (Neptune Gloves)

### ISSUE THREAD

**Issue by zachup100** [gildedgames/aether-issues#463]
Aether Version: 1.7.10-1.2

I was on my server and my friend and I were playing through the dungeon and when we receive all three keys from the Mini-Bosses, we went to face the Boss, the Slider, and when we killed it, we crashed, and I read through the Crash Log, and It said that Neptune Gloves were crashing us, like there in a stack or something... but they were removed from the world and was fixed.

Crash Report: http://pastebin.com/huMsgPdE

**Comment by Collin1971** [comment]
Redownload 1.7.10-1.2. We made a fix right after uploading it because of this crash. :)

**Comment by zachup100** [comment]
Oh, I appologize, thanks for responding so fast! <3

**Comment by zachup100** [comment]
By the way, Is the party system still not working when you try to "Add Members"?

**Comment by Collin1971** [comment]
I believe that was fixed, too.

**Comment by zachup100** [comment]
Ok, Thank you for giving me updates and giving us all the Aether Back! <3
