### ISSUE TITLE
Invisible Bush and Wildgrass

### ISSUE THREAD

**Issue by Yelenn44** [gildedgames/aether-issues#468]
Since the 1.7.10-1.1 patch i can't see berry bush and Wild grass in the aether, like it was not textured. (I now play with 1.7.10-1.2)

I have reinstall minecraft+forge+AetherII no changes
I play on my own server, so i reinstalled it as well. 
But nothings seems to work.

Sorry for my bad english.

**Comment by Collin1971** [comment]
Berry Bushes and Wild Grass are both transparent textures. Perhaps your graphics card doesn't support some graphic features, or is filling up it's available memory?

It'd be helpful to see a screenshot of the issue.

**Comment by Yelenn44** [comment]
Here the wild grass 
http://www.hostingpics.net/viewer.php?id=58833020150316172748.png

And the bushes
http://www.hostingpics.net/viewer.php?id=64388820150316172854.png

My graphics card is a GTX 770 and works perfectly. For the memory i've got 8Go and 2.5Go free when the game is running. :-(
And the wild grass in the minecraft world works.

**Comment by Collin1971** [comment]
Do you think you could force a Minecraft crash by holding down `F3 + C` for 10 seconds (or until it crashes) and attach it to this issue with [GitHub Gist](https://gist.github.com)? This usually dumps a list of what OpenGL features your graphics card supports and any issues there may be.

**Comment by Collin1971** [comment]
Oops, accidentally closed the issue! Fixed it.

**Comment by Yelenn44** [comment]
Of course.

https://gist.github.com/65390ada49d5cf6e5b10.git

**Comment by Collin1971** [comment]
It appears you have Optifine installed (which tends to cause all kinds of graphical oddities in other mods). Could you remove Optifine and see if the issue persists?

If that doesn't fix anything, you could try [updating your graphics card drivers](http://www.nvidia.com/download/driverResults.aspx/83080/en-us), as they released an update a little over a day ago that could fix the issue. (the driver you're using now was released in January)

**Comment by Yelenn44** [comment]
Yep. It was optifine. 
Sorry for evrything. :-(

**Comment by roket333** [comment]
That's what they're here for. To help when problems rise.

**Comment by Collin1971** [comment]
Nah, don't worry about it. You're not bothering anyone, @Yelnenn44.
