### ISSUE TITLE
Update Crash

### ISSUE THREAD

**Issue by THEVOLCO** [gildedgames/aether-issues#470]
Hi,
 I updated aether to the newest version and now i´m getting this Crash Report when i try to create a new world.

Crash Report:

http://pastebin.com/YmdHyegA

**Comment by Collin1971** [comment]
This issue is invalid because _we don't support modified clients_. My only advice is that you can try deleting the Aether II config file in your profile's config folder.

Please reopen this issue if you're able to reproduce it _without additional mods_.
