### ISSUE TITLE
Mount thru portal get wrong cords

### ISSUE THREAD

**Issue by Jonasrems** [gildedgames/aether-issues#472]
The aether portal allow you to be riding an entety while going thru it (Nether portal does not allow this).
And when you go thru the portal mounted your cords stays the same as in the dimention you were in. But does not generate a portal there. This bug have the potential to teleport you into the ground when going to overworld from aether (Happened to me on a server).

**Comment by 115kino** [comment]
This problem is fixed in 1.5 :)
