### ISSUE TITLE
Dying in the aether sends me to spawn instead of my bed.

### ISSUE THREAD

**Issue by BBoldt** [gildedgames/aether-issues#473]
So, I set my spawn with a bed in the overworld, but every time I die, I get sent back to spawn.

Using latest versions of the aether at the time of posting this.

**Comment by xJonL** [comment]
Plugins can actually mess with respawning, like Essentials. In it's config you can disable to spawn at the spawn when you die.

**Comment by BBoldt** [comment]
@xJonL 

I don't have any plugins like that. It happens in single player too. In fact I just downloaded the aether launcher which includes only the aether mod, and it happens there too.

So this rules out any plugins or crazy mod interaction.

**Comment by BBoldt** [comment]
@xJonL 

I wasn't aware the aether beds could set your spawn in the aether. 

I see why what I wrote could have been a bit unclear.

If you haven't set your spawn in the aether with a bed, and you die in the aether, you go to overworld spawn rather than your bed set spawn point in the overworld.
