### ISSUE TITLE
Bug with Gravitite tools and golden oak trees

### ISSUE THREAD

**Issue by therule2010** [gildedgames/aether-issues#475]
Hey there GG team, I wanted to report some bugs with gravitite stuff and the golden oak trees in the aether ii mod. One bug with gravitite is the sword will not launch enemies, or lose durability. Another bug is that gravitite axes will not collect the amber from golden oak trees. That's all for now, bye have a great time!
~rule

**Comment by xJonL** [comment]
With the Gravitite Sword, you have to hold down shift and hit an enemy for them to go flying. The Gravitite Axe not being able to obtain Golden Amber is working fine for me when I tested it. The issue with axes and golden oak sounds like an old bug to me.  Are you on the latest version?

**Comment by therule2010** [comment]
ok, I'm using 1.7.10, dunno if there's a new version for 1.7.10 or not, but the sword also doesn't lose durabiliity when i attack things.

**Comment by Collin1971** [comment]
Make sure you're not in _creative_. If it still appears it's not taking damage, press `F3 + H` then `F3`, open your inventory, and hover over the item. It'll show the durability count as a number. Try again and make sure it's just not visually changing.

**Comment by therule2010** [comment]
I do use f3 + h, and the durability never goes down unless i shift-click
with it to send enemies flying.
