### ISSUE TITLE
tempests bug

### ISSUE THREAD

**Issue by THEVOLCO** [gildedgames/aether-issues#477]
I´m making a private modpack atm and I noticed that Tempests are spawning in the overworld (or at least in jungle biomes because i found them there)´.

**Comment by THEVOLCO** [comment]
and when u kill it it Drops rails...

**Comment by xJonL** [comment]
We're VERY aware of this issue.  We've fixed this in a soon to be release build.

**Comment by roket333** [comment]
lol! railests! do they shoot minecarts?

On Tue, Mar 31, 2015 at 12:08 AM, Jon Lachney <notifications@github.com>
wrote:

> We're VERY aware of this issue. We've fixed this in a soon to be release
> build.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gildedgames/aether-issues/issues/477#issuecomment-87969470>
> .
>



-- 
http://signaturecraft.us/signatures/eJwrs9OLcnNzEtNLkpMK0kt4ipCE3BIz03MzNFLzs-FSBkbG3OFpCbmKrjlF5UUpRYXKxhxBZfmFWUWp3IZmZqCsQGXAQDJYh4C.png
