### ISSUE TITLE
crash with flans mod 

### ISSUE THREAD

**Issue by jochuan** [gildedgames/aether-issues#479]
this happens when i fall of the aether with a plane of flans mod
http://openeye.openmods.info/crashes/44c723e17c947d46cd9c4dc49d67fcd8

**Comment by jochuan** [comment]
https://github.com/FlansMods/FlansMod/issues/649

**Comment by xJonL** [comment]
Looks like an issue with Flan's Mod, it's a NullPointer, I see you've already made the issue on his tracker. Hope he gets back to you!
