### ISSUE TITLE
Aether present causes client disconnect

### ISSUE THREAD

**Issue by neum69** [gildedgames/aether-issues#480]
Running my own forge server -- forge-1.7.10-10.13.2.1343-1.7.10-universal with the latest aether ii, as well as the latest gravestone mod and mr. crayfish furniture mod.  My daughter placed a present in the aether while in creative.  when I broke the present in survival it flashed for a second and then my client disconnected with the below stacktrace talking about a class cast exception.  After that point, I cannot connect to the server at all.  It always disconnects me after a moment with the same stacktrace. 

---- Minecraft Crash Report ----
// Sorry :(

Time: 4/4/15 7:25 AM
Description: Ticking entity

java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer
	at net.minecraft.entity.DataWatcher.func_75679_c(SourceFile:91)
	at noppes.npcs.entity.EntityNPCInterface.func_70636_d(EntityNPCInterface.java:324)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1611)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:206)
	at noppes.npcs.entity.EntityNPCInterface.func_70071_h_(EntityNPCInterface.java:225)
	at noppes.npcs.entity.old.EntityNpcSkeleton.func_70071_h_(EntityNpcSkeleton.java:42)
	at net.minecraft.world.World.func_72866_a(World.java:2070)
	at net.minecraft.world.World.func_72870_g(World.java:2034)
	at net.minecraft.world.World.func_72939_s(World.java:1887)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1994)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:961)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.entity.DataWatcher.func_75679_c(SourceFile:91)
	at noppes.npcs.entity.EntityNPCInterface.func_70636_d(EntityNPCInterface.java:324)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1611)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:206)
	at noppes.npcs.entity.EntityNPCInterface.func_70071_h_(EntityNPCInterface.java:225)
	at noppes.npcs.entity.old.EntityNpcSkeleton.func_70071_h_(EntityNpcSkeleton.java:42)
	at net.minecraft.world.World.func_72866_a(World.java:2070)
	at net.minecraft.world.World.func_72870_g(World.java:2034)

-- Entity being ticked --
Details:
	Entity Type: npcskeleton (noppes.npcs.entity.old.EntityNpcSkeleton)
	Entity ID: 256
	Entity Name: Nalworche
	Entity's Exact location: 395.00, 71.00, 264.00
	Entity's Block location: World: (395,71,264), Chunk: (at 11,4,8 in 24,16; contains blocks 384,0,256 to 399,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0.00, -0.08, 0.00
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1887)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [GCEntityClientPlayerMP['hip3pop'/248, l='MpServer', x=364.28, y=71.52, z=246.53]]
	Chunk stats: MultiplayerChunkCache: 225, 225
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-44,64,252), Chunk: (at 4,4,12 in -3,15; contains blocks -48,0,240 to -33,255,255), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 7668429 game time, 96085 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 20 total; [EntityNpcPony['Gareld'/273, l='MpServer', x=411.47, y=58.00, z=169.81], EntityAerbunny['Aerbunny'/272, l='MpServer', x=389.00, y=68.22, z=322.00], GCEntityClientPlayerMP['hip3pop'/248, l='MpServer', x=364.28, y=71.52, z=246.53], EntityNPCHumanMale['Blaze'/258, l='MpServer', x=373.16, y=57.00, z=277.75], EntityNpcMonsterFemale['William'/259, l='MpServer', x=379.41, y=62.00, z=283.44], EntityNpcSkeleton['Nalworche'/256, l='MpServer', x=395.00, y=71.00, z=264.00], EntityNpcSkeleton['Ariel'/257, l='MpServer', x=392.00, y=72.00, z=261.00], EntityItem['item.item.swetJellyBlueSwetJelly'/262, l='MpServer', x=395.75, y=9.13, z=223.91], EntityNpcPony['Oldam'/263, l='MpServer', x=396.28, y=58.00, z=283.59], EntityNpcMonsterFemale['Ayumu'/260, l='MpServer', x=378.53, y=60.00, z=278.03], EntityNpcMonsterFemale['Darage'/261, l='MpServer', x=379.84, y=59.00, z=287.94], EntityNpcSkeleton['Torerod'/266, l='MpServer', x=374.00, y=63.00, z=317.00], EntityNpcSkeleton['Malus'/267, l='MpServer', x=373.00, y=62.00, z=317.00], EntityNPCHumanFemale['Nalworche'/264, l='MpServer', x=414.69, y=69.00, z=258.41], EntityNpcPony['Apolitho'/265, l='MpServer', x=419.47, y=75.41, z=230.91], EntityAerbunny['Aerbunny'/270, l='MpServer', x=387.00, y=67.22, z=324.00], EntityAerbunny['Aerbunny'/271, l='MpServer', x=388.00, y=68.22, z=321.00], EntityNpcSkeleton['Wyrl'/268, l='MpServer', x=373.00, y=63.00, z=318.00], EntityItem['item.tile.greenSkyrootSapling'/254, l='MpServer', x=385.78, y=71.13, z=253.25], EntityItem['item.tile.greenSkyrootSapling'/255, l='MpServer', x=387.25, y=71.13, z=252.13]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2432)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:909)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.7.0_75, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 105817848 bytes (100 MB) / 371240960 bytes (354 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.97.1343 Minecraft Forge 10.13.2.1343 16 mods loaded, 16 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	FML{7.10.97.1343} [Forge Mod Loader] (forge-1.7.10-10.13.2.1343-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Forge{10.13.2.1343} [Minecraft Forge] (forge-1.7.10-10.13.2.1343-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	mod_ThreadedLighting{1.7.10-1.0} [Threaded Lighting] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	gilded-games-util{1.7.10-1.1} [Gilded Games Utility] (gilded-games-util.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	aether{Alpha 1.7.10-1.2} [Aether II] (aether.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	AnimationAPI{1.2.4} [AnimationAPI] (AnimationAPI-1.7.10-1.2.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	customnpcs{1.7.10b} [CustomNpcs] (CustomNPCs_1.7.10b_withskins.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	GalacticraftCore{3.0.1} [Galacticraft Core] (GalacticraftCore-BETA-1.7-3.0.1.170.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	GalacticraftMars{3.0.1} [Galacticraft Planets] (Galacticraft-Planets-BETA-1.7-3.0.1.170.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	GraveStone{2.11.3} [GraveStone] (GraveStone-2.11.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	hamsterrific{0.2.0} [Hamsterrific] (Hamsterrific-0.2.0.jar.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	cfm{3.4.7} [§9MrCrayfish's Furniture Mod] (MrCrayfishFurnitureModv3.4.7(1.7.10).jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	MutantCreatures{1.4.8} [Mutant Creatures] (MutantCreatures-1.7.10-1.4.8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	TwilightForest{2.3.1} [The Twilight Forest] (twilightforest-1.7.10-2.3.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Launched Version: 1.7.10-Forge10.13.2.1343-1.7.10
	LWJGL: 2.9.1
	OpenGL: ATI Radeon HD 4800 Series GL version 3.3.11672 Compatibility Profile Context, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by xJonL** [comment]
From the looks of your crash log, I'm not seeing anything about the Present TNT crashing. If you look closely at your stacktrace, it looks you've crashed from CustomNPS. I went ahead and installed all the mods you are running and tested the Present TNT issue. I'm not crashing from it. You say it always happens for you? Try testing this on a new world and then the world you are crashing on.

Stacktrace:
at net.minecraft.entity.DataWatcher.func_75679_c(SourceFile:91)
at noppes.npcs.entity.EntityNPCInterface.func_70636_d(EntityNPCInterface.java:324)
at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1611)
at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:206)
at noppes.npcs.entity.EntityNPCInterface.func_70071_h_(EntityNPCInterface.java:225)
at noppes.npcs.entity.old.EntityNpcSkeleton.func_70071_h_(EntityNpcSkeleton.java:42)
at net.minecraft.world.World.func_72866_a(World.java:2070)
at net.minecraft.world.World.func_72870_g(World.java:2034)

**Comment by neum69** [comment]
Thanks for the rapid reply.  :-)  I did try a new server and got the same
behavior.  I think the problem is solved by removing customNPCs from my
client machine mods folder.  I have been playing in the aether now for
about 10 minutes with no disconnects.

Strange though--I had customNPCs loaded on the client but not on the
server--I would have expected that means it's not active/doing anything on
this server.  Is that a bad assumption?

I still suspect this is some kind of interaction between customNPCs and the
aether mod, because after reporting the bug, I removed the aether and
gilded-games-util jars from the mods directory, restarted, did the /fml
confirm, and connected successfully.  then stopped the server, reinstalled
the jars in the mod directory, restarted, and was then able to log in fine
and play for some time in the overworld with no prob.  then went back to
the aether and was able to run around for about 10 seconds, then got the
disconnect again.  after that, same behavior of immediate disconnects until
I re-performed the remove/replace of the aether mod files.  Prior to going
to the aether the first time, we had probably 20 hours logged in this
server in the overworld and the nether with no issues; this disconnect
issue seems to only happen in the aether and with customNPCs lo.

**Comment by xJonL** [comment]
That's awesome!  If you have any other issues, don't hesitate to make a new issue. Take care. ♥

**Comment by xJonL** [comment]
Oh, I apologize I did not see the rest of your reply. When I tested the issue, I tested on singleplayer. It could be a strange serer issue. You say you are getting disconnected. Are you crashing or literally getting disconnected from the server?

**Comment by roket333** [comment]
Such a mean present!

On Sat, Apr 4, 2015 at 7:32 AM, Jon Lachney <notifications@github.com>
wrote:

> Reopened #480 <https://github.com/gildedgames/aether-issues/issues/480>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gildedgames/aether-issues/issues/480#event-273292219>.
>



-- 
http://signaturecraft.us/signatures/eJwrs9OLcnNzEtNLkpMK0kt4ipCE3BIz03MzNFLzs-FSBkbG3OFpCbmKrjlF5UUpRYXKxhxBZfmFWUWp3IZmZqCsQGXAQDJYh4C.png

**Comment by neum69** [comment]
Sorry, just saw your followup.  I think I've used imprecise language.
Symptoms were experienced when playing on a server, but its pretty clearly
the client crashing, not the server disconnecting us.

I was more concerned about the fact that there seems to be an unhealthy
interaction between the mods, I.e. I don't get the crash with CustomNPCs
(which was installed only on client side, not server side) unless playing
in the Aether.

**Comment by xJonL** [comment]
You are using CustomNPCs 1.7.10b, try using the latest, which is 1.7.10d:
http://www.curse.com/mc-mods/minecraft/221826-custom-npcs
