### ISSUE TITLE
Sheepuff

### ISSUE THREAD

**Issue by MCCrystle** [gildedgames/aether-issues#482]
When a baby sheepuff eats, it floats up in the air and it has an adult sheepuff's wool. (not sure if actual bug or not)
![2015-04-06_11 30 20](https://cloud.githubusercontent.com/assets/11838020/7026604/c24c787e-dd18-11e4-9c4e-0bfbbd66e027.png)

**Comment by roket333** [comment]
that's a lot of wool on that baby sheep O_o

On Tue, Apr 7, 2015 at 8:25 AM, MCCrystle <notifications@github.com> wrote:

> When a baby sheepuff eats, it floats up in the air and it has an adult
> sheepuff's wool. (not sure if actual bug or not)
> [image: 2015-04-06_11 30 20]
> <https://cloud.githubusercontent.com/assets/11838020/7026604/c24c787e-dd18-11e4-9c4e-0bfbbd66e027.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gildedgames/aether-issues/issues/482>.
>



-- 
http://signaturecraft.us/signatures/eJwrs9OLcnNzEtNLkpMK0kt4ipCE3BIz03MzNFLzs-FSBkbG3OFpCbmKrjlF5UUpRYXKxhxBZfmFWUWp3IZmZqCsQGXAQDJYh4C.png

**Comment by 115kino** [comment]
Fixed in 1.4 finally!!! :D
