### ISSUE TITLE
gloves, mouse cap, and pendants disapear when other mods installed

### ISSUE THREAD

**Issue by BrianIsBro** [gildedgames/aether-issues#486]
i have optifine to make my game smoother but yet i get a pair of Zanite gloves and it doesn't show in my hand. So it just doesn't work with some mods and other mods like optifine.

**Comment by BrianIsBro** [comment]
p.s. Its when you put them on.

**Comment by 115kino** [comment]
Is optifine the only mod you have installed or are there others? (besides Aether and GG util)

**Comment by Collin1971** [comment]
Related to #379.
