### ISSUE TITLE
Small WAILA Issue

### ISSUE THREAD

**Issue by Amaxter** [gildedgames/aether-issues#488]
I think when registering the holystone block there was a mistake or something, in WAILA when looking at the item this is what happens: http://inft.ly/32XPLek

**Comment by roket333** [comment]
Does it say the same thing if you look at a holystone block that you placed? If not, I guess the naturally generated holystone needs a localized name.

**Comment by xJonL** [comment]
That's an issue with us not naming the block correctly in our language files. Applied this fix.
