### ISSUE TITLE
Inventory slots API

### ISSUE THREAD

**Issue by NightKosh** [gildedgames/aether-issues#492]
Hello. I need an API to get access to additional inventory slots for a compatibility purposes with gravestone mod.
Or, maybe there is another way to get access to these slots without an API?

**Comment by Collin1971** [comment]
Unfortunately there's no way to (easily) access the accessory slots and the such, (and the source code of the Aether for MC 1.7 is far too coupled and rusty to allow any kind of API right now).

With the rewrite of the Aether for 1.8 we're working on right now, I'm planning on making some basic functionality for people to access inventory slots we add, add Altar recipes, and other stuff we've been long overdue for.

If you have anything specific you'd like, you can always send me a PM about it. :D

**Comment by Collin1971** [comment]
This issue has been merged into #508.

**Comment by NightKosh** [comment]
Hello. Sorry for posting in closed thread, but I'd like to know your plans about my request.
The reason I asked about it is an API for my mod(for 1.8) which I made a few days ago.
https://github.com/NightKosh/GraveStone-mod-API/blob/master/nightkosh/gravestone/api/IGraveGeneration.java (addPlayerItemsHandler method)
https://github.com/NightKosh/GraveStone-mod-API/blob/master/nightkosh/gravestone/api/grave_items/IPlayerItems.java (addItems method)

So if you will not provide access to this slots, you can use my API to place items in grave.

**Comment by Collin1971** [comment]
> Sorry for posting in closed thread, but I'd like to know your plans about my request.

My bad, I originally meant to comment back on this issue but seemingly I didn't.

I recently changed the way of which we drop the accessory items upon death in 1.7.10-1.6 (and the 1.8 codebase) to allow better compatibility with mods which use regular Forge events to capture drops.

I _believe_ this fixed the issue with your gravestones mod, but I'm not entirely sure. If not, I can look into providing some sort of rudimentary interface for other mods to hook into, but right now I unfortunately have other priorities.
