### ISSUE TITLE
Spawn in quicksoil island with bushes falling from the sky.

### ISSUE THREAD

**Issue by SrItalo** [gildedgames/aether-issues#494]
That a really odd bug, because i used to play the aether on version 1.7.10, and it was perfect. But now that i am playing at the version 1.6.4 i just spawn in a island of quicksoil with blue leave bushes and sapplings falling from the sky. 
I tried to go to a normal island nearby, but it seemed that some of the islands had turned into quick soil-falling bush islands. Please help.

**Comment by Collin1971** [comment]
1.7.10 worlds are NOT compatible with 1.6.4 worlds.

**Comment by SrItalo** [comment]
Well..i've downloaded the one that was on your site. The one for 1.6.4

Em 17/05/2015 20:52, Collin Soares <notifications@github.com> escreveu:
1.7.10 worlds are NOT compatible with 1.6.4 worlds.

---
