### ISSUE TITLE
thaumcraft and tinkers construct bug

### ISSUE THREAD

**Issue by THEVOLCO** [gildedgames/aether-issues#495]
Hi,
there is a Little bug with thaumcraft and tinkers. 
1.Greatwood tress sometimes generate in the aether
2. The blue slimes from tinkers spawn in the aether

**Comment by Collin1971** [comment]
This sounds like a biome ID conflict between the Aether II and TCon.

If this issue still persists, try changing the biome ID in the Aether II's configuration file.
