### ISSUE TITLE
Cant craft an incubator.

### ISSUE THREAD

**Issue by SrItalo** [gildedgames/aether-issues#496]
Hello, i'm using the minecraft 1.6.4 version, and your aether II version designed for it. I simply am not able to craft the incubator for the moa eggs. I tried the 5 skyroot planks up, Amb torche in the middle and the bottom with holystone, but it didnt work . I did some research and tried the one that is the same than the one before but changing the planks for holystone a vice versa, but it didnt work either. Please help, i love aether and i really want to ride a Moa.

**Comment by Collin1971** [comment]
1.6.4 is _NOT_ supported anymore. Please do not create issues for old versions of the Aether II.
