### ISSUE TITLE
the gloves didnt appear on my hand

### ISSUE THREAD

**Issue by jochuan** [gildedgames/aether-issues#499]
![2015-05-26_08 48 59](https://cloud.githubusercontent.com/assets/11268912/7811973/a0092612-0384-11e5-9efb-7e6f7b50dce1.png)
![2015-05-26_08 50 07](https://cloud.githubusercontent.com/assets/11268912/7811976/a2d8e512-0384-11e5-82c3-765db44e400b.png)

**Comment by xJonL** [comment]
The gloves/pendants/rings will not render on your player if you're using Optifine. We're working out this issue. Thanks for the report!
