### ISSUE TITLE
Crash upon hitting a Ghast fireball with a Valkyrie Lance

### ISSUE THREAD

**Issue by BrandonPotts** [gildedgames/aether-issues#501]
Crash upon hitting a Ghast's fireball back using a Valkyrie Lance.
[Full crash on GitHub Gist.](https://gist.github.com/BrandonPotts/8c0c5f0572ef61f04cf2) (Aether II 1.7.10-1.4)

**Comment by Collin1971** [comment]
Fixed in 1.7.10-1.5. :smile:
