### ISSUE TITLE
2 more bugs!

### ISSUE THREAD

**Issue by LemectricLP** [gildedgames/aether-issues#502]
Hi Aether II Team! I have found 2 bugs, 1 of them is a bigger problem. 
1. If you have a skyroot water bucket in your inventory and go trough an aether portal, the skyroot bucket is empty.
2. If you destroy a skyroot door, you`ll get 2 skyroot doors.

**Comment by xJonL** [comment]
I cannot reproduce the first issue but the second one is definitely an issue.

**Comment by Collin1971** [comment]
In the future, please create multiple issues for each individual bug. The Skyroot Door bug has been fixed.
