### ISSUE TITLE
You can't see chests through waypoints

### ISSUE THREAD

**Issue by rotolonico** [gildedgames/aether-issues#503]
I just found this bug in the aether, you can't see chests through waypoints...

**Comment by xJonL** [comment]
Sorry, but could you be a little more clear? I don't understand. What are "waypoints" and you cannot see overworld, skyroot or both chests?

**Comment by Collin1971** [comment]
This issue is invalid and has been closed due to lack of activity.

If you can provide the name (and preferably, a link) to the mod that adds waypoints, feel free to re-open the issue.

**Comment by rotolonico** [comment]
I used technic launcher The Aether II modpack... sorry for inactivity
Here you can find the mod description: http://www.technicpack.net/modpack/the-aether-ii-modpack-v2.276151
If you put this link in technic launcher you can install the modpack http://api.technicpack.net/modpack/the-aether-ii-modpack-v2

**Comment by roket333** [comment]
This is very similar to a 1.8 multiplayer glitch where when  a sign with
text on it is seen through a glass pane in another player's hand, the text
is invisible.

**Comment by rotolonico** [comment]
Also it's like the bug in the Vanilla version, you can't see water through ice and viceversa...
