### ISSUE TITLE
Zephyrs attacking through glass.

### ISSUE THREAD

**Issue by Ultra131** [gildedgames/aether-issues#504]
So i loaded up V1.7.10-1.4 and made a quicksoil glass room. After staying there for a while i noticed Zephyrs started attacking me through the glass, i assumed it was a bug so i tested it with normal glass and found they did the same thing. I took two screenshots one with normal glass
![2015-06-07_08 15 14](https://cloud.githubusercontent.com/assets/12784555/8024102/9169e26e-0ced-11e5-8576-628e79c17fef.png)
and the other with quicksoil glass.
![2015-06-07_08 18 54](https://cloud.githubusercontent.com/assets/12784555/8024116/e23ef7ce-0ced-11e5-8a5a-3be625bc134b.png)

**Comment by Ultra131** [comment]
After playing a bit longer i noticed the Zephyrs were also attacking through walls. I also saw that they would only attack through the wall if you were standing right next to it, but i stepped back to take the screenshots from the original post and the one below.
![2015-06-11_09 56 31](https://cloud.githubusercontent.com/assets/12784555/8110197/9ab46a7a-1020-11e5-8b77-d9399e0bc36c.png)

**Comment by 115kino** [comment]
I forgot to mention that their radius has decreased, if there are still issues with zephyr's with the 1.5 update re-open this issue
