### ISSUE TITLE
Flying Cows and Phygs 

### ISSUE THREAD

**Issue by Fightr2021** [gildedgames/aether-issues#505]
When riding a cow or phyg, it can randomly go weird. Like you can't even control it at times and it'll never face the direction your facing. It happens frequently, and I've died a few times from this issue.
http://prntscr.com/7fh3i8

**Comment by Collin1971** [comment]
Judging by the screenshot, the server appears to be running Cauldron with Bukkit plugins. It's most likely the issue doesn't lie within the Aether, but instead with the server's implementation.

I have yet to encounter any awkwardness when riding a mount in the Aether, on singleplayer or the Aether Official Server.

**Comment by Fightr2021** [comment]
This event was recorded on the AOS, and from closer inspection when I'm sitting still on my cow it will move, and it'll be messed up.

**Comment by Collin1971** [comment]
The Aether Official Server also runs Cauldron with Bukkit plugins. :smile:

> It's most likely the issue doesn't lie within the Aether, but instead with the server's implementation.

Please try reproducing the issue in a Forge-only server.

**Comment by Fightr2021** [comment]
I was not able to replicate this in singleplayer or a Forge-only server. This is a bug with Cauldron/plugins as you stated.
