### ISSUE TITLE
Ghast Crash

### ISSUE THREAD

**Issue by Fightr2021** [gildedgames/aether-issues#506]
I was fighting a ghast and it crashed, I think it was caused by the valkyrie lance. Here's the crash log: http://pastebin.com/00CV7aKj

**Comment by Collin1971** [comment]
This issue was already reported internally within the Aether team and was patched a week ago.

![](http://i.imgur.com/tZS8P6U.png)

1.7.10-1.5 will contain the fix. :smile:

**Comment by Collin1971** [comment]
Duplicate of #501.
