### ISSUE TITLE
Accessories given the "Unbreakable" tag break almost immediately, 1.7.10

### ISSUE THREAD

**Issue by SpaceKGreen** [gildedgames/aether-issues#511]
Mostly what the title says.  If an accessory item is given the "Unbreakable: 1" tag, as soon as an action is performed that would reduce their durability, they break and disappear.  Zanite rings/pendants, for example, disappear almost immediately, and gravitite gloves broke after punching a squid once.

An ice ring given the tag didn't break right away, but it also stopped freezing things, and eventually disappeared as well.

**Comment by 115kino** [comment]
Has this been tested on server and client yet?

**Comment by SpaceKGreen** [comment]
I am personally unable to test it server-wise at the moment; my ISP is terrible and only really works with a few games, Minecraft not included.  This issue does occur on the client.  Is there enough of a difference in the server's item handling code that this wouldn't happen?

**Comment by 115kino** [comment]
All accessories should have this issue fixed in 1.5
