### ISSUE TITLE
Unstackable Bread

### ISSUE THREAD

**Issue by Bricex17** [gildedgames/aether-issues#513]
I made 3 loaves of bread but when I shift clicked, they wouldn't go to my inventory. So I took them out individually, but when I started to stack them, they just stacked into one loaf? then I tried to stack that loaf onto a stack of 64 loaves (I know its impossible) but the loaf disappeared. So instead of 67 loaves, I still have 64.

**Comment by 115kino** [comment]
Has this issued occurred on server or client or both?

**Comment by Bricex17** [comment]
As far as I know, it has only occurred on the server.
 


     On Tuesday, July 7, 2015 12:10 PM, 115kino <notifications@github.com> wrote:
   

 Has this issued occurred on server or client or both?—

**Comment by 115kino** [comment]
As far as I can tell it COULD have been server connection issues as well as issues with aether crafting inventory. Was this crafting done in a crafting table, or aether's accessory inventory?
