### ISSUE TITLE
Can't Connect To The Cloud Network

### ISSUE THREAD

**Issue by OrangeEnderMatt** [gildedgames/aether-issues#515]
So I recently started to play on Aether II again. Haven't played on it in awhile. I opened up the launcher and loaded up the Cloud Network. I tried connecting to "Aether Official Network" and even as I type it just says "logging in". It doesn't time out of anything. Anyone know why?

**Comment by xJonL** [comment]
Our box has an issue blacklisting IPs when they're too many requests. Since it's been 7 days, you should try again. Reply and tell me if you're still having the issue.

**Comment by Collin1971** [comment]
We've corrected the issue on the AOS.
