### ISSUE TITLE
Hard-coded Biome IDs

### ISSUE THREAD

**Issue by CandiceJoy** [gildedgames/aether-issues#520]
Some Biome IDs, at the very least ID 200 (the dungeon) are hardcoded and can easily conflict.  For instance, we set Atum to ID 200 and so the Atum dimension was messed up and we couldn't figure out why until we realized that your Biome IDs (some of them) are hardcoded.

**Comment by 115kino** [comment]
This will be talked about and be looked into as soon as possible

**Comment by 115kino** [comment]
The Dungeon Biome is now going to be configurable in 1.5
