### ISSUE TITLE
Cannot open my chests/access my house due to username change.

### ISSUE THREAD

**Issue by ChartvplaysMC** [gildedgames/aether-issues#522]
Hello!I recently returned to the server yesterday as _Rize_Kamishiro_ after a long time of no Aether.Today,I changed my username back to what it was at the very start of buying minecraft,which is ChartvplaysMC.

I cannot open my chest or place anything due to the protection blocks I placed,Rain (not sure of the username) the Mod on the server tried everything to open the chest/break it,but it was and still is really buggy.

It has been reported,but I am posting this here just so if anyone else has this issue they will know how to fix it.

**Comment by Collin1971** [comment]
Please do not use this issue tracker for issues involving the Aether Official Server.

**Comment by ChartvplaysMC** [comment]
Oh sorry
