### ISSUE TITLE
Slider's Labrynth Crash/Misplaced Spawn [1.7.10_1.4]

### ISSUE THREAD

**Issue by yackaro** [gildedgames/aether-issues#523]
I worked really hard to get where I was on my survival world, I was doing really good. I had the nether, the aether, plenty of the materials I needed, everything.
I decided to do the Slider's Labrynth.
First time I go in, Everything seems like it's going to be normal, just some heavy lagg from what I thought was the dungeon loading for the first time.
I gave it a minute, but instead of clearing out and playing normally, Minecraft just... closed.
I opened it back up and went back in, I was in the wall.
I destroyed the culprit to my suffocation, and mined as far as I could in all four directions, I never did find the dungeon.
It lagged out and crashed again after a little bit.
and if I die, it respawns me at the top of the dungeon (bedrock under me) and then it teleports me to somewhere that causes me to die in the void. HALP.
Other mods used: Optifine 1.7.10 HD U

**Comment by Collin1971** [comment]
Please upload the logs to [GitHub Gist](https://gist.github.com).

**Comment by yackaro** [comment]
I could only find one crash log in my aether II 1.4 folder, not sure whether it's related to the Slider's Labrynth crashes or not. https://gist.github.com/yackaro/f948f9f628a672fd23de
every time it crashed it was a silent crash, no notifications or app has stopped working popups or anything. It just closed suddenly.

**Comment by Collin1971** [comment]
> time: Tue Aug 04 01:13:38 2015

It seems that the crash log is fairly recent and most likely related to the crash you encountered.

Unfortunately, it's not a typical crash that I'm familiar with. I believe this kind of crash is actually Java crashing from calling native code (graphics drivers, OpenGL, etc), and not our's or Minecraft's code.

I noticed too that you were running Windows 10 in the crash. As it's fairly new, you might want to update your graphics drivers to see if the issue lies with a early version of your graphics driver for Windows 10.

**Comment by yackaro** [comment]
I am running the latest stable driver release from Nvidia, the ones they released specifically for Windows 10 release. I don't think this crash log is relatable to the issue, I'm pretty sure that it was from the time I turned the render distance up to max and didn't have enough vram left, but it's the only crash log located in the directory. I would have had multiple logs if it made them in any of the silent crashes I had in the Labrynth, I ran it and crashed at least twice. As far as I know, there are no crash logs from any of them. I wish I could give them to you, but they were unfortunately never created.

**Comment by Collin1971** [comment]
Is this crash reproducible? If so, which launcher are you using to run the Aether II?

**Comment by yackaro** [comment]
I believe I could likely reproduce it, and I was using the official aether launcher.

**Comment by yackaro** [comment]
I will see if I can record video of the crash.

**Comment by ethancook2** [comment]
I'm having the exact same issue!

**Comment by ethancook2** [comment]
Why did they close this?

**Comment by jellysquid3** [comment]
The issue was closed because we were unable to reproduce the issue, and from the look of it, it lies outside our code.
