### ISSUE TITLE
Jar files should have proper naming.

### ISSUE THREAD

**Issue by JAWSAWN** [gildedgames/aether-issues#529]
I just hate when this happens. Download file for 1.7.10 1.4 aether file (or any version) ONLY has "aether.jar" name. This will confuse lots of players and may cause issues, and the worst of them all all the downloads will be renamed to aether(x).jar. I would love see better names like "aether2-1.7.10-1.4" or just plain "aether1.4" would be much better.

**Comment by Collin1971** [comment]
The JAR files are named that way because the Aether II Launcher expects them to all be `aether.jar`.

There's not much we can do about this until we deprecate the launcher.

**Comment by JAWSAWN** [comment]
Ah I see...

**Comment by xJonL** [comment]
I agree, @JAWSAWN

**Comment by Collin1971** [comment]
Well, it turns out I was misinformed.

The JARs are now properly named, for everyone's sanity. :)
