### ISSUE TITLE
Aether Portal not working

### ISSUE THREAD

**Issue by BritishAlpha** [gildedgames/aether-issues#535]
So, I installed everything correctly, started up my own server so my brother and I could play without worrying about lag, griefers etc

But when I tried to make the portal the water didn't activate the portal?
I went into creative and checked that Aether 2 was installed correctly and I have everything there but if I try to use something from the mod, for example the Skyroot door when I place it, it goes invisible... I then tried to use the Aether Portal block and place it down, I stood where I placed it and I heard the music but it didn't take me anywhere.

I noticed in the Server file that Allow Nether is set to true, but there's nothing about Aether? Is that maybe the issue? I've never ran my own server that's been modded before, only Vanilla, any help would be much appreciated

**Comment by Collin1971** [comment]
You haven't properly installed the Aether on the server.

Did you create a Forge server and copy the Aether mod to the mods folder?

**Comment by BritishAlpha** [comment]
I copied exactly what the Aether 2 website told me to do, I put the Aether mod in the mods folder along with the Gilded games one

**Comment by Collin1971** [comment]
We don't provide instructions for installing the Aether II to a Minecraft server (as far as I know).

The Aether II (along with Gilded Games Utility) is required to be installed on both the Minecraft Forge client and Minecraft Forge server for it to work.

**Comment by BritishAlpha** [comment]
Can I make my own multiplayer server using the Aether II?
Of course! The Aether II is built on Minecraft Forge, meaning it's fairly simple to set up a server running it, just follow this simple tutorial from one of our staff members. Remember that you will have to install both the Aether II and Gilded Games Utility to your server for content to operate in multiplayer, both of which are available on our downloads page.

https://imgur.com/a/hH5nx 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
The imgur link is the website that they direct you to when you click on "This simple tutorial from one of our staff members" 

That's from the Aether 2 FAQ, that's what I followed, I'll retry the installation on Forge and see if it works in the morning (Well later today haha)

**Comment by xJonL** [comment]
@Collin1971 Wow you got rekt, lol. :laughing: 

@BritishAlpha Sounds like your server isn't loaded the mods properly, make sure starting script is using Forge's server jar and not vanillas. Also be sure to check if your mods are in your server's mods folder.
