### ISSUE TITLE
Problem when exiting Aether II Dungeon

### ISSUE THREAD

**Issue by CA2020** [gildedgames/aether-issues#537]
I have a problem, sometimes when leaving the Aether Dungeon I'm placed in the roof of the Portal on the Aether

http://imgur.com/Mb2QpWY

I broke those 2 blocks in creative, but playing in survival, you just die.

Using Aether 1.7.10-1.2 (But I believe it's 1.4 I think the mcmod.info file is wrong in this version and says you using 1.2

Forge 10.13.4.1448-1.7.10

Any idea what the problem can be?

Also when not placed there and die by suffocation, most the time I get a half heart hit when exiting the dungeons.

**Comment by Collin1971** [comment]
Merged into #542.
