### ISSUE TITLE
Dungeons still generating. Bug or missundertood config?

### ISSUE THREAD

**Issue by CA2020** [gildedgames/aether-issues#540]
I have changed in the configs:

B:"Generate Aether Portals"=false

Will that make so the Dungeons entrances dont generate anymore and players can only access when they place a portal by hand?

I created a world and still found dungeons entrances generating, so not sure if it's a bug, or if it means other thing.

**Comment by Collin1971** [comment]
The configuration option only stops the generation of glowstone Aether portals, not dungeon entrances.

**Comment by CA2020** [comment]
Ohhh ok I understand now ;) Thanks for the answer.

Would there be a way, maybe on future updates to have a config so Dungeons don't generate? We have Aether on a progression pack where we give the player some Dungeon Entrances items, and it would be nice if we can stop them from going there until it's time to do so. Specially because also, they can mine on the dungeons for Gravitite, without the risk of falling into the void.

Thanks a lot for your time ;)
