### ISSUE TITLE
Suffocation when exiting Aether II dungeon totems

### ISSUE THREAD

**Issue by cp888** [gildedgames/aether-issues#542]
When exiting the Slider's Labyrinth in Aether II, I would respawn in the aether but with my head stuck in the roof of the totem, which caused me to suffocate. When playing in survival mode I had to quickly switch to creative before it killed me. It doesnt always happen, but it is a fairly common occurence. I think a solution for this would just be to make the roof of the totem higher.

**Comment by Collin1971** [comment]
Can you provide a world seed and the totem's exact coordinates?

**Comment by CA2020** [comment]
My topic here seams a "clone" of this problem also

https://github.com/gildedgames/aether-issues/issues/537

Here is a video with the seed and the example, it doesn't happens 100% of the time, but it eventually can happen and you suffocate to death.
(Covered my ingame name on the video)
Seed: -7021353085666963584
X: 135
Y: 88
Z: -775

Used the top dungeon entrance.

http://www.mediafire.com/watch/rqxzjnyxqn9zi7x/AetherDungeonDead.mp4

**Comment by Collin1971** [comment]
We were able to reproduce it on multiple worlds, so I'll take a look. :)

**Comment by Collin1971** [comment]
The issue was because the totem always spawns you 2 blocks diagonally away from it.

I've changed it to search in an 8x8 radius, and choose the safest block for you to spawn in. (if it can't find one, it'll create one).

**Comment by cp888** [comment]
Ok thanks. It happens on random totems though, no specific ones in any specific worlds.
