### ISSUE TITLE
Party Member's Button Crash

### ISSUE THREAD

**Issue by EVDESTROY** [gildedgames/aether-issues#544]
If your hosting a party and you go to the Members button, it crashes the game. Theres no crash report, it shows a dirt block for a split second and closes out Aether II. Sorry :(

**Comment by Collin1971** [comment]
Could you look in the crash-reports folder where the profile with the Aether is installed?

On the Aether Launcher, you should be able to find it in `%APPDATA%/.aether/profiles/1.7.10-1.5/crash-reports`
