### ISSUE TITLE
1.7.10-1.5 Bug: Skyroot Beds don't work properly anymore

### ISSUE THREAD

**Issue by cp888** [gildedgames/aether-issues#545]
When I used a skyroot bed at night in the aether, I woke up from the bed as normal, but it was still nighttime. The beds don't change night to day anymore. Edit: Just found out that regular beds don't work in the aether either.

**Comment by Collin1971** [comment]
Fixed in the next upcoming release. :)

**Comment by cp888** [comment]
Ok. Looking forward to it :)
