### ISSUE TITLE
Aether II 1.7.10 1.5 load problem

### ISSUE THREAD

**Issue by DomiWroc** [gildedgames/aether-issues#546]
In that version of aether the aether mod don't loading! I don't know the reason of that. In loaded minecraft i see only normal mc menu , mods options , but aether mod isn't loaded. I using the official Aether II launcher. Anyone can help??

**Comment by Amaxter** [comment]
Likely the spawn egg crash, in any case post a PASTEBIN link to the crash report, currently you'r giving no specific information. If the crash involves a duplicate stat ID then there's already an issue for it.

**Comment by Collin1971** [comment]
@Amaxter The game wouldn't even load if it was the case (and since he's using the Aether Launcher, no additional mods would be installed).

The Aether Launcher can sometimes fail to download the Aether mod itself, without even itself noticing. Could you try to clear your launcher's data by deleting `.aether` in `%APPDATA%`?

**Comment by Amaxter** [comment]
@Collin1971 I just read the title, being the idiot I occasionally can be, and assumed his game crashed. As someone who runs a few GitHub issue trackers I regularly get dupe bugs so I kind of am hyper sensitive to that, next time I need to be smart and read the actual body though :P

**Comment by DomiWroc** [comment]
Ok i try to delete .aether . P. s. My game don't crash , but the aether mod
 isn't loading correctly .

**Comment by Collin1971** [comment]
I think I've resolved the issue with the launcher. Could you try to run 1.5.1, again?

**Comment by DomiWroc** [comment]
Everything works good . Thank for help guys .
