### ISSUE TITLE
Tinkers Construct - Shard of Life compatibility issue

### ISSUE THREAD

**Issue by MrKrabat** [gildedgames/aether-issues#547]
Hello,
i found a compatibility issue with Tinkers Construct.
The Shard of Life has the ability to double the life of a player, TConstruct also have such a feature with red/yellow/green heart canister every colour can add 10 hearts (20 life points).

The logical result is with Aether and TConstruct the player can gain a max of 50 hearts (100 life points).
But the combination seems to double the life, for example:

The player uses 10 life of shards and doubles his life from 10 hearts to 20 hearts.
Now the player adds one red heart canister, we can see the player gain 2 new hearts instead of 1.
when he have 10 red heart canister he has 20 additional hearts instead of 10 hearts.

In the end the player gains 80 hearts.
It does not matter in wich order we apply the extra life upgrades.

The next bug occurs on death, now the player has the correct TConstruct life but the Aether extra life is completely gone and you can not consume the shard of life again.

TConstruct- 1.7.10-1.8.7
Aether 1.7.10-1.5

Of course this issue can also be on TConstructs side :)

**Comment by SrihanB** [comment]
why was it closed? hes right
