### ISSUE TITLE
Use mod without overriding launch screen?

### ISSUE THREAD

**Issue by krues8dr** [gildedgames/aether-issues#551]
Is there a way to use Aether II but not show the Aether II launch screen?  I'd like to use it in a modpack, but it's kind of confusing to have that new replacement screen up.  I tried setting "use aether menu system" to `false` in the config but that just causes it to load without any menu screen at all and crash.

**Comment by MrKrabat** [comment]
As you said, open config\aether\Aether II.cfg

"use aether menu system" {
    #  [default: true]
    B:"Menu Configuration"=true
}

I have set this to false and have the vanilla screen, no crash.
Maybe one of your other mods is causing this. can you post the crashlog?

**Comment by krues8dr** [comment]
Thanks, so that is the right setting?  Here are logs of my errors:

https://gist.github.com/krues8dr/e4c4df3565f345dab8d5

The first error seems to come from ArmorStatusHUD, but if I disable that I still get an error from Minecraft itself (?) and disabling *all* mods but Aether II still gives the same error (I think).

This is aether 1.5.1, gilded-games-util 1.7, and running under 1.7.10.

**Comment by MrKrabat** [comment]
yes, the setting is right,

maybe this is a Mac OS X/AMD related compatibility problem, can you try it on a windows machine?

**Comment by krues8dr** [comment]
I'm afraid I don't have access to any other machines, sorry. :(  I'm not great at Java, but I'll see if I can't dig in to the source a bit...  Otherwise the mod runs great!

**Comment by Collin1971** [comment]
There's a small issue in GGUtil where if you disabled the Aether menu when the last used menu _was_ the Aether menu, the game doesn't load any menu, and causes some really buggy behavior.

Could you try downloading and replacing your 'gilded-games-util.jar' with this fix I've made? http://files.aetherii.com/files/versions/1.7.10-1.5.1/gilded-games-util-1.7.10-1.7.1.jar

**Comment by krues8dr** [comment]
Shiny, that works perfectly @Collin1971 !   Thanks so much for the quick fix!

**Comment by Collin1971** [comment]
No problem. :smile:

We'll update the downloads page and launcher to reflect the new version later this week.
