### ISSUE TITLE
Client Crash I had just killed a zombie in the overworld with a hollystone sword.

### ISSUE THREAD

**Issue by ProsperCraft** [gildedgames/aether-issues#553]
http://pastebin.com/hD7ZJS6L

**Comment by MrKrabat** [comment]
I can partially confirm this issue.

I got this issue with Aether 1.5 and with 1.5.1 in my test worlds,
when you wearing aether accessoires like the Zanit Ring and it break you get this crash.
Armor, tools and weapons seems not to be affected by this, only items in the aether accessoires slots.

https://gist.github.com/MrKrabat/f8c7e67694350593002d

When you reopen the world it will crash again.
As i said, the problem occurs when the accessoire break.

**Comment by Collin1971** [comment]
Reproduced it both on singleplayer and multiplayer in 1.5.1, marking as a bug.

**Comment by 115kino** [comment]
It was an issue with all accessories breaking. It is now fixed :)
