### ISSUE TITLE
Client Crash - RenderPlayerAether.renderGloves

### ISSUE THREAD

**Issue by ProsperCraft** [gildedgames/aether-issues#555]
Player is wearing iron gloves, he is unable to log in.

Server log section- http://pastebin.com/MjXgmr5n
at sun.nio.ch.FileDispatcherImpl.read0(Native Method)

Client crashlog- http://pastebin.com/vknQ2WAV
at net.aetherteam.aether.client.renders.entities.player.RenderPlayerAether.renderGloves(RenderPlayerAether.java:74)

**Comment by Collin1971** [comment]
`weather2.weathersystem.EntityRendererProxyWeather2Mini.func_78480_b(EntityRendererProxyWeather2Mini.java:50)`

It seems a weather system mod is doing some pretty strange stuff. Please ask him to remove the weather mod, and see if he's able to connect afterwards.

**Comment by ProsperCraft** [comment]
http://pastebin.com/5AyPJ2yg

Client crash with weather 2 mod removed from server and client.

I have removed his data from the data/aether/playerdata and his playerfile, not sure where else to look to get him back in.

**Comment by Collin1971** [comment]
We're looking into getting this patched as soon as possible, since it affects a large amount of our users.

Hold tight! :)

**Comment by Psiiche** [comment]
I do not know how this worked, but I was able to access my world again after having this issue. My workaround was caveman at best. I started a new world and one at a time equipped the Leather, Iron, Gold, Chain, Zanite, etc, gloves, and logged out with them on. Upon re-entering I took them off and put on the next pair. After I had went through all the gloves I tried to access my original world, to which it worked. I immediately took all gloves from my equip, inventory, and boxes, as well as the other players. We have no issues now and will try to avoid gloves until a future patch. Not sure how this will help bigger servers, but if individuals/single players are having problems, perhaps this will help :)

**Comment by xJonL** [comment]
Shoudl be completely fixed for the next update. If any issues arise just re-open this issue. :jack_o_lantern:

**Comment by TheSerenin** [comment]
@xJonL When do you expect the update to release?

**Comment by PGMacDesign** [comment]
I'm still having this issue as I cannot login. Has the patch for this already been released?

**Comment by PGMacDesign** [comment]
I was able to temporarily fix it by using Psiiche's method (Here: https://github.com/gildedgames/aether-issues/issues/555#issuecomment-147409036 ).

**Comment by Collin1971** [comment]
@PGMacDesign We still haven't released the update containing the fix.

**Comment by ProsperCraft** [comment]
Can we please re-open this till it gets fixed?

**Comment by Collin1971** [comment]
@ProsperCraft If the issue still persists in the latest version (1.7.10-1.5.2 as of the time of writing), we'll re-open the issue and look further into it.
