### ISSUE TITLE
slider glitch

### ISSUE THREAD

**Issue by alexjamespeter** [gildedgames/aether-issues#556]
hi i was fighting the slider and i killed it but as soon as i killed it i died and so it responed i got the stuff off the 1st one but all my armor i was wearing was gone and it was full durability.

**Comment by xJonL** [comment]
Where you on a multiplayer server or on singleplayer?

**Comment by alexjamespeter** [comment]
Multiplayer

**Comment by xJonL** [comment]
So, could you briefly explain again clearly now? Your armor was missing after.. what happended now?
