### ISSUE TITLE
Aether II doesn't load worlds

### ISSUE THREAD

**Issue by aaron5015** [gildedgames/aether-issues#557]
i was playing Resonant Rise and i added Aether II to the modpack because its a fun mod. but when i tried loading a world or creating a world. it took me back to main menu BUT when i removed the mod they worked.
Can this be fixed?

**Comment by Collin1971** [comment]
Could you provide us with a client log when you try loading a world?

**Comment by aaron5015** [comment]
well i didn't get a log out of it. the world never loaded until i removed it.

**Comment by aaron5015** [comment]
okay well i took a look in the resonant rise folder and there was no log that i could find.

**Comment by Collin1971** [comment]
There should be a `latest.log` inside the `logs` folder. I can't help you find where the folder is exactly (since you're using a custom modpack), but it should be near the same place as were your saves are located.

**Comment by aaron5015** [comment]
do you mind waiting like 10 minutes considering that seems like how long MC needs to load *since i removed aether i need to put it back in to load up again.*

**Comment by aaron5015** [comment]
http://pastebin.com/YRfFh4L0
Sorry it took so long. MC took forever to load.

**Comment by aaron5015** [comment]
http://pastebin.com/n5USn3Nc heres a FML log.

**Comment by Collin1971** [comment]
```java.lang.IllegalArgumentException: Failed to register dimension for id 3, One is already registered```

You have a mod which is registering a dimension on the same ID as the Aether II.

Edit the Aether configuration file in `config/` and change the dimension IDs.

**Comment by aaron5015** [comment]
i changed that but i have a off topic issue http://pastebin.com/cwdBx5UP anyway to fix this?

**Comment by aaron5015** [comment]
after i find a fix for the off topic issue i'll test the aether on Resonant rise :P

**Comment by aaron5015** [comment]
I fixed everything. 
thanks for all the help...even though not much was needed but thanks nonetheless
