### ISSUE TITLE
Launcher won't open. even though re-installing it.

### ISSUE THREAD

**Issue by SpookyDOTexe** [gildedgames/aether-issues#558]
I don't know what went wrong, but it worked fine until next day when i were gonna play. then the launcher opened, And i could login. but when it loaded the Mod, it got stuck at 100%. then i removed the .aether and .aether_old folders in %appdata% and then the launcher didn't open even. Help please?

**Comment by Collin1971** [comment]
Could you try to re-download the launcher from [the downloads page](http://aetherii.com/downloads) after deleting .aether and .aether_old (if they still exist)?

**Comment by SpookyDOTexe** [comment]
already tried that D:
