### ISSUE TITLE
Crash after leaving dungeon

### ISSUE THREAD

**Issue by ZephaniahNoah** [gildedgames/aether-issues#559]
After I leave a dungeon in Aether 1.6.4 it says "shutting down internal server" then it crashes. Also I hit my head when I leave a dungeon, which isn't a problem but really annoying. (Suffocating in the ceiling.)
---- Minecraft Crash Report ----
// Everything's going to plan. No, really, that was supposed to happen.

Time: 9/30/15 11:40 AM
Description: Ticking tile entity

java.lang.NullPointerException
	at net.aetherteam.aether.blocks.util.BlockMultiTileEntity.func_71860_a(BlockMultiTileEntity.java:121)
	at net.aetherteam.aether.tile_entities.util.TileEntityMultiBlock.func_70316_g(TileEntityMultiBlock.java:219)
	at net.aetherteam.aether.tile_entities.TileEntityTotem.func_70316_g(TileEntityTotem.java:41)
	at net.minecraft.world.World.func_72939_s(World.java:2209)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1921)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:910)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:838)
	at net.minecraft.client.main.Main.main(SourceFile:101)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:131)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:27)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.aetherteam.aether.blocks.util.BlockMultiTileEntity.func_71860_a(BlockMultiTileEntity.java:121)
	at net.aetherteam.aether.tile_entities.util.TileEntityMultiBlock.func_70316_g(TileEntityMultiBlock.java:219)
	at net.aetherteam.aether.tile_entities.TileEntityTotem.func_70316_g(TileEntityTotem.java:41)

-- Tile entity being ticked --
Details:
	Name: Totem // net.aetherteam.aether.tile_entities.TileEntityTotem
	Block type: ID #4048 (tile.aether:Slider Labyrinth's Totem // net.aetherteam.aether.blocks.BlockSliderLabyrinthTotem)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (591,44,-4), Chunk: (at 15,2,12 in 36,-1; contains blocks 576,0,-16 to 591,255,-1), Region: (1,-1; contains chunks 32,-32 to 63,-1, blocks 512,0,-512 to 1023,255,-1)
	Actual block type: ID #0
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:2209)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [UnglitchClientPlayer['ZephaniahNoah'/224, l='MpServer', x=-47.50, y=60.28, z=44.50]]
	Chunk stats: MultiplayerChunkCache: 30
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (8,64,8), Chunk: (at 8,4,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 1377234 game time, 1000019655 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 17 total; [EntitySheepuff['Sheepuff'/42668, l='MpServer', x=-51.84, y=54.00, z=50.00], EntityFlyingCow['Flying Cow'/42664, l='MpServer', x=10.53, y=65.00, z=19.75], EntityItem['item.item.aether:Swet Jelly.Blue Swet Jelly'/42723, l='MpServer', x=-50.69, y=60.13, z=28.28], EntityMoa['Moa'/42725, l='MpServer', x=-48.47, y=59.00, z=29.69], EntityItem['item.item.sugar'/42724, l='MpServer', x=-50.69, y=60.13, z=28.28], EntityFlyingCow['Flying Cow'/42727, l='MpServer', x=-55.47, y=58.00, z=2.38], EntityMoa['Moa'/42726, l='MpServer', x=-58.50, y=59.00, z=5.84], EntityAerbunny['Aerbunny'/42680, l='MpServer', x=-69.00, y=60.24, z=9.00], EntityAerbunny['Aerbunny'/42681, l='MpServer', x=-72.19, y=59.24, z=8.34], UnglitchClientPlayer['ZephaniahNoah'/224, l='MpServer', x=-47.50, y=60.28, z=44.50], EntitySheepuff['Sheepuff'/42682, l='MpServer', x=-64.56, y=59.00, z=7.47], EntityXPOrb['Experience Orb'/42755, l='MpServer', x=-73.84, y=56.13, z=48.81], EntityCarrionSprout['Carrion Sprout'/42683, l='MpServer', x=-65.00, y=62.00, z=18.00], EntityCarrionSprout['Carrion Sprout'/42678, l='MpServer', x=-66.00, y=60.00, z=11.00], EntityCarrionSprout['Carrion Sprout'/42679, l='MpServer', x=-66.00, y=60.00, z=13.00], EntityZephyroo['Zephyroo'/42742, l='MpServer', x=-42.53, y=34.00, z=74.75], EntitySheepuff['Sheepuff'/42743, l='MpServer', x=-46.09, y=36.00, z=72.47]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:440)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2312)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:856)
	at net.minecraft.client.main.Main.main(SourceFile:101)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:131)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:27)

-- System Details --
Details:
	Minecraft Version: 1.6.4
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.7.0_79, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 570706976 bytes (544 MB) / 1068498944 bytes (1019 MB) up to 1908932608 bytes (1820 MB)
	JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G
	AABB Pool Size: 1999 (111944 bytes; 0 MB) allocated, 228 (12768 bytes; 0 MB) used
	Suspicious classes: FML and Forge are installed
	IntCache: cache: 18, tcache: 0, allocated: 6, tallocated: 62
	FML: MCP v8.11 FML v6.4.50.1,345 Minecraft Forge 9.11.1.1345 Optifine OptiFine_1.6.4_HD_U_D1 55 mods loaded, 55 mods active
	mcp{8.09} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	FML{6.4.50.1,345} [Forge Mod Loader] (minecraftforge-9.11.1.1345.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Forge{9.11.1.1345} [Minecraft Forge] (minecraftforge-9.11.1.1345.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	CodeChickenCore{0.9.0.9} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	NotEnoughItems{1.6.1.9} [Not Enough Items] (NotEnoughItems-1.6.4-1.6.1.9-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	PlayerAPI{1.2} [Player API] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	threadedlighting{0.1} [Threaded Lighting] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	chunkbase_unglitch{1.2} [Unglitch] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	OpenModsCore{@VERSION@} [OpenModsCore] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	bspkrsCore{v5.3(1.6.4)} [bspkrsCore] ([1.6.4]bspkrsCorev5.3.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	TreeCapitator{Forge 1.6.4.r06} [Treecapitator] ([1.6.4]TreeCapitator.Forge.1.6.4.r06.Universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Aether II{Alpha 1.6.4-4.0} [Aether II] (aether.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	AnimationAPI{1.1.1} [AnimationAPI] (AnimationAPI v1.1.2 mc1.6.4.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	antiqueatlas{3.1.1-1.6.4} [Antique Atlas] (antiqueatlas-3.1.1-1.6.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	mod_a{a} [mod_a] (Awesome Swords.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Backpack{1.28.37} [Backpack] (backpack-1.28.37-1.6.x.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BasicArmour{1.5} [Basic Armour Mod] (Basic Armor mod 1.6 (v1.5).zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BiblioCraft{1.5.5} [BiblioCraft] (BiblioCraft[v1.5.5].zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	bigtrees{1.6.4} [BigTrees] (BigTrees-164-forge.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BuildCraft|Core{4.2.1} [BuildCraft] (buildcraft-A-1.6.4-4.2.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BuildCraft|Builders{4.2.1} [BC Builders] (buildcraft-A-1.6.4-4.2.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BuildCraft|Energy{4.2.1} [BC Energy] (buildcraft-A-1.6.4-4.2.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BuildCraft|Factory{4.2.1} [BC Factory] (buildcraft-A-1.6.4-4.2.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BuildCraft|Transport{4.2.1} [BC Transport] (buildcraft-A-1.6.4-4.2.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BuildCraft|Silicon{4.2.1} [BC Silicon] (buildcraft-A-1.6.4-4.2.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	CarpentersBlocks{3.2.8.6} [Carpenter's Blocks] (Carpenter's Blocks v3.2.8.6 - MC 1.6.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Chisel{1.4.11} [Chisel] (chisel-1.6.4-1.4.11.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ComputerCraft{1.63} [ComputerCraft] (ComputerCraft1.63.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	customrecipes{4.52} [Custom Recipes] (CustomRecipes-4.5-5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MoCreatures{6.1.0} [DrZhark's Mo'Creatures Mod] (DrZharks MoCreatures Mod v6.1.0.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	EnderStorage{1.4.3.6} [EnderStorage] (EnderStorage-1.6.4-1.4.3.6-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Highlands{2.1.3} [Highlands] (Highlands2.1.4_MC1.6.4.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	HopperDuctMod{1.2.2} [Hopper Ducts] (HopperDuctsMod1.2.2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	KeithyUtils{1.3} [Keithy Utils] (KeithyUtils-1.6.4-1.3.30.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	mod_LivelyEnd{1.0} [mod_LivelyEnd] (Lively End.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Metallurgy3Core{3.4.1} [Metallurgy 3 Core] (Metallurgy-1.6.4-3.4.1.32.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Metallurgy3Base{3.4.1} [Metallurgy 3 Base] (Metallurgy-1.6.4-3.4.1.32.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Metallurgy3Vanilla{3.4.1} [Metallurgy 3 Vanilla] (Metallurgy-1.6.4-3.4.1.32.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Metallurgy3Machines{3.4.1} [Metallurgy 3 Machines] (Metallurgy-1.6.4-3.4.1.32.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MutantCreatures{1.4.4} [Mutant Creatures] (Mutant_Creatures_v1.4.4_mc1.6.4.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	NEIPlugins{1.1.0.6} [NEI Plugins] (NEIPlugins-1.1.0.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	OpenMods{0.5.1} [OpenMods] (OpenModsLib-0.5.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	OpenBlocks{1.2.9} [OpenBlocks] (OpenBlocks-1.2.9.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	RedstonePasteMod{1.5.1} [Redstone Paste] (RedstonePasteMod1.5.1.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Roguelike{1.3.3} [Roguelike Dungeons] (roguelike-v1.3.3-forge-1.6.4.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	shinyfood{1.3.0} [ShinyFood] (ShinyFood-1.6.4-v1.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	chunkbase_slimemod{2.0-b2} [Slime Mod] (SlimeMod_Forge_1.6.4_2.0-b2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	SnowCatLib{0.0.1} [SnowCat's Library] (SnowCatLib-1.6.4-0.0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	SnowCatsSlimeBlockFromTheFuture{0.0.1} [SnowCat's Slime Block From The Future] (SnowCatFutureSlimeBlock-1.6.4-0.0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	jetpackMod{1.0.0} [tripl3's Jetpacks] (tripl3sJetpacksv1.0.0.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	TwilightForest{1.20.4} [The Twilight Forest] (twilightforest-1.6.4-1.20.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	chunkbase_villageinfo{2.0-b3} [Village Info] (VillageInfo_Forge_1.6.4_2.0-b3.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	weaponmod{1.6.2 v1.13.6} [Balkon's WeaponMod] (WeaponMod.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	wildcaves3{0.4.3.5} [Wild Caves 3] (Wild-Caves-Mod-1.6.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	mod_XavillianCore{1.8} [mod_XavillianCore] (Xavillian Core (1.6.4).jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Launched Version: 1.6.4-Forge9.11.1.1345
	LWJGL: 2.9.0
	OpenGL: GeForce GTX 970/PCIe/SSE2 GL version 4.5.0 NVIDIA 355.60, NVIDIA Corporation
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Pack: Default
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 130 (7280 bytes; 0 MB) allocated, 41 (2296 bytes; 0 MB) used

**Comment by Collin1971** [comment]
The Aether II for Minecraft 1.6.4 is not supported anymore. Please do not create issues for old versions.

**Comment by prodkid** [comment]
have you tried turning it off and turning it back on again?
