### ISSUE TITLE
Aechor plant milking

### ISSUE THREAD

**Issue by Jesterguythedemon** [gildedgames/aether-issues#562]
Milking an aechor plant with 2 or more skyroot buckets will only give you just the one poison bucket.
![skyroot bucket](https://cloud.githubusercontent.com/assets/14991792/10301958/253b027c-6c64-11e5-8175-d82491a7a64f.gif)
Buckets do not get returned.

**Comment by Collin1971** [comment]
Fixed in the upcoming release.
