### ISSUE TITLE
Accessory missing, wiping issue

### ISSUE THREAD

**Issue by xJonL** [gildedgames/aether-issues#564]
Accessories are wiped via server restart. Well, I figured out how to reproduce this issue. It's not the server restart and this won't happen on other big server. When the AOS goes for a restart, it takes a very long time, and then times out players, not really saving 'everything'. When the server is saved without a player getting timed out, accessories are still there.

**Comment by Collin1971** [comment]
Your server implementation isn't properly kicking players. File a bug there.

Cannot reproduce on a Forge server.
