### ISSUE TITLE
Mod issues with Dimensional Doors

### ISSUE THREAD

**Issue by ajthemacboy** [gildedgames/aether-issues#565]
You can view the issue here: https://github.com/CannibalVox/DimDoors/issues/45#event-428433289

The developer indicated that this is a problem with your mod, not his.

**Comment by xJonL** [comment]
@ajthemacboy Can't seem to reproduce the crash anymore, give it a try with the latest verions of Aether, GGUtil and Dimensional Doors.

**Comment by ajthemacboy** [comment]
I could never reproduce it either, it just happens randomly... Try flying through a bunch really fast on a big modpack perhaps?
