### ISSUE TITLE
Apologies for Reopening...

### ISSUE THREAD

**Issue by Psiiche** [gildedgames/aether-issues#568]
But I do not know how to send private messages on this site, nor do I believe anything is seen after a thread is marked "closed". I was not even granted time to ask a question about the response in https://github.com/gildedgames/aether-issues/issues/567 before my thread was closed. I responded with both a question on how to fix it, and an alternate log.

To tldr, <b> Where do I go to delete the "playerdata" files so I can attempt to load again?</b>
The thread mentions the path of "data/aether/playerdata" but I've looked in all surrounding areas and have yet to run into a playerdata file.

Again my apologies.

**Comment by Collin1971** [comment]
The post in #555 says that deleting player data _does not work_.

In the future, please comment on issue #555 (or whichever issue yours has been merged into as a duplicate) instead of creating new ones.
