### ISSUE TITLE
Donation Glitch

### ISSUE THREAD

**Issue by FlinchFace** [gildedgames/aether-issues#571]
I never donated, because i was 20 cents short. but for some reason, i have donator perks, there is no way your donation service would`ve known my Minecraft username, and i never made the payment anyway, I feel extremely cheaty even though i have no idea how this happened.

**Comment by Collin1971** [comment]
What is your in-game username?

**Comment by FlinchFace** [comment]
MC_Flinch

**Comment by Collin1971** [comment]
Oddly, I couldn't find a donation under your in-game name or UUID in our database anywhere.

We're looking into the issue however, since we've had a few reports about this issue for the last month.

**Comment by Collin1971** [comment]
I've applied a small patch to the system. Do you still have donator status in-game?
