### ISSUE TITLE
Aether 2 and Animated Player mod incompatibility 

### ISSUE THREAD

**Issue by SlipperySkater** [gildedgames/aether-issues#576]
So when I run just aether 2 version 1.5.1 and latest animated player mod there seems to be a problem with the animations of the animated player mod. I'm not exactly sure if its a problem with Aether causing it but whenever I run the 2 mods together the animations do not work and when I take out Aether it does work. I only ran just those mods together, no other mods installed.

**Comment by xJonL** [comment]
I've tested with the mod alone and with Aether combind, the animations seem smooth after Aether II 1.7.10-1.5.2, try updating your mods and tell me if you still get an issue! :)

Aether II
http://www.AetherII.com/downloads
Animation API
http://www.curse.com/mc-mods/minecraft/animationapi

Animated Player
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1288552-aesthetic-animated-player-compatibility-and
