### ISSUE TITLE
Lighting Aether Portal Crashes Server and Client

### ISSUE THREAD

**Issue by RSmeep13** [gildedgames/aether-issues#581]
I'm having a  pretty annoying issue here. After manually installing Aether II and GildedGamesUtil to my server and client, lighting a server immediately results in a crash: 
---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 12/6/15 11:34 AM
Description: Unexpected error

java.lang.NoSuchMethodError: net.minecraftforge.fluids.FluidStack.getFluidID()I
	at net.aetherteam.aether.AetherEvents.onFillBucket(AetherEvents.java:133)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_39_AetherEvents_onFillBucket_FillBucketEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at net.minecraft.item.ItemBucket.func_77659_a(ItemBucket.java:39)
	at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:146)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78769_a(PlayerControllerMP.java:377)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1463)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1941)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:961)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.aetherteam.aether.AetherEvents.onFillBucket(AetherEvents.java:133)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_39_AetherEvents_onFillBucket_FillBucketEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at net.minecraft.item.ItemBucket.func_77659_a(ItemBucket.java:39)
	at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:146)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78769_a(PlayerControllerMP.java:377)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1463)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['VoidPrince'/345, l='MpServer', x=-214.63, y=73.62, z=237.15]]
	Chunk stats: MultiplayerChunkCache: 169, 169
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-228,64,240), Chunk: (at 12,4,0 in -15,15; contains blocks -240,0,240 to -225,255,255), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 176834 game time, 176834 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 57 total; [EntityClientPlayerMP['VoidPrince'/345, l='MpServer', x=-214.63, y=73.62, z=237.15], EntityChicken['Chicken'/132, l='MpServer', x=-255.41, y=78.00, z=188.59], EntityChicken['Chicken'/133, l='MpServer', x=-252.56, y=74.00, z=185.53], EntityChicken['Chicken'/134, l='MpServer', x=-252.53, y=80.00, z=201.44], EntityZombie['Zombie'/137, l='MpServer', x=-238.69, y=42.00, z=278.88], EntityPig['Pig'/138, l='MpServer', x=-247.72, y=64.00, z=303.09], EntityChicken['Chicken'/146, l='MpServer', x=-232.56, y=86.00, z=179.59], EntityChicken['Chicken'/147, l='MpServer', x=-235.44, y=80.00, z=189.53], EntityCreeper['Creeper'/148, l='MpServer', x=-234.34, y=42.00, z=279.50], EntityCreeper['Creeper'/149, l='MpServer', x=-237.50, y=42.00, z=282.50], EntityCreeper['Creeper'/150, l='MpServer', x=-236.16, y=42.00, z=278.75], EntityZombie['Zombie'/152, l='MpServer', x=-235.31, y=42.00, z=278.31], EntityZombie['Zombie'/153, l='MpServer', x=-237.50, y=42.00, z=278.50], EntityPig['Pig'/154, l='MpServer', x=-227.75, y=67.00, z=275.50], EntityChicken['Chicken'/159, l='MpServer', x=-223.47, y=74.00, z=169.47], EntityChicken['Chicken'/160, l='MpServer', x=-216.56, y=83.00, z=188.44], EntityCreeper['Creeper'/161, l='MpServer', x=-215.38, y=28.00, z=231.70], EntityCreeper['Creeper'/162, l='MpServer', x=-213.38, y=28.00, z=230.38], EntitySpider['Spider'/163, l='MpServer', x=-222.72, y=55.00, z=253.00], EntityChicken['Chicken'/168, l='MpServer', x=-197.44, y=73.00, z=271.44], EntityPig['Pig'/169, l='MpServer', x=-202.50, y=69.00, z=272.50], EntityChicken['Chicken'/170, l='MpServer', x=-206.53, y=68.00, z=283.53], EntityChicken['Chicken'/171, l='MpServer', x=-195.56, y=65.00, z=282.47], EntityChicken['Chicken'/172, l='MpServer', x=-200.38, y=65.00, z=294.63], EntitySheep['Sheep'/179, l='MpServer', x=-184.50, y=67.00, z=195.50], EntitySheep['Sheep'/180, l='MpServer', x=-192.91, y=67.00, z=191.88], EntitySheep['Sheep'/181, l='MpServer', x=-184.75, y=67.00, z=193.66], EntitySheep['Sheep'/182, l='MpServer', x=-190.91, y=67.00, z=191.06], EntityChicken['Chicken'/183, l='MpServer', x=-176.38, y=68.00, z=227.53], EntityChicken['Chicken'/184, l='MpServer', x=-185.53, y=78.00, z=255.41], EntityChicken['Chicken'/185, l='MpServer', x=-183.44, y=76.00, z=265.41], EntityChicken['Chicken'/186, l='MpServer', x=-178.53, y=67.00, z=306.53], EntityChicken['Chicken'/200, l='MpServer', x=-172.66, y=72.00, z=254.59], EntitySkeleton['Skeleton'/215, l='MpServer', x=-144.50, y=52.00, z=182.50], EntityChicken['Chicken'/216, l='MpServer', x=-147.63, y=72.00, z=304.59], EntityBat['Bat'/347, l='MpServer', x=-221.91, y=25.16, z=247.50], EntityBat['Bat'/348, l='MpServer', x=-214.38, y=27.00, z=255.63], EntityChicken['Chicken'/92, l='MpServer', x=-291.47, y=78.00, z=173.44], EntityBat['Bat'/350, l='MpServer', x=-209.25, y=26.05, z=247.50], EntityPig['Pig'/95, l='MpServer', x=-291.94, y=72.00, z=193.03], EntityZombie['Zombie'/226, l='MpServer', x=-143.50, y=52.00, z=181.50], EntityCreeper['Creeper'/101, l='MpServer', x=-294.97, y=27.00, z=213.53], EntityChicken['Chicken'/230, l='MpServer', x=-142.38, y=72.00, z=298.41], EntityBat['Bat'/361, l='MpServer', x=-134.07, y=51.36, z=285.70], EntityBat['Bat'/362, l='MpServer', x=-135.27, y=51.00, z=288.16], EntityChicken['Chicken'/108, l='MpServer', x=-289.69, y=80.00, z=171.53], EntityPig['Pig'/109, l='MpServer', x=-280.53, y=72.00, z=196.34], EntityChicken['Chicken'/110, l='MpServer', x=-272.44, y=72.00, z=203.41], EntityPig['Pig'/111, l='MpServer', x=-282.97, y=72.00, z=225.03], EntityChicken['Chicken'/116, l='MpServer', x=-271.41, y=72.00, z=175.41], EntityChicken['Chicken'/118, l='MpServer', x=-267.25, y=76.00, z=166.53], EntityChicken['Chicken'/119, l='MpServer', x=-274.47, y=73.00, z=184.56], EntityChicken['Chicken'/120, l='MpServer', x=-259.97, y=72.00, z=202.47], EntityCreeper['Creeper'/121, l='MpServer', x=-263.00, y=47.00, z=218.50], EntityCreeper['Creeper'/122, l='MpServer', x=-261.50, y=47.00, z=209.97], EntitySkeleton['Skeleton'/123, l='MpServer', x=-252.56, y=41.00, z=222.09], EntityChicken['Chicken'/124, l='MpServer', x=-271.38, y=67.00, z=285.38]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2432)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:916)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_45, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 121416968 bytes (115 MB) / 296484864 bytes (282 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP v9.05 FML v7.10.85.1286 Minecraft Forge 10.13.2.1286 6 mods loaded, 6 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	FML{7.10.85.1286} [Forge Mod Loader] (forge-1.7.10-10.13.2.1286.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Forge{10.13.2.1286} [Minecraft Forge] (forge-1.7.10-10.13.2.1286.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	mod_ThreadedLighting{1.7.10-1.0} [Threaded Lighting] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	gilded-games-util{1.7.10-1.1} [Gilded Games Utility] (gilded-games-util-1.7.10-1.8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	aether{1.7.10-1.5.2} [Aether II] (aether-1.7.10-1.5.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Launched Version: 1.7.10-Forge10.13.2.1286
	LWJGL: 2.9.1
	OpenGL: GeForce GTX 660/PCIe/SSE2 GL version 4.5.0 NVIDIA 353.62, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: [Torhans Clear Glass 1.7.2 - Black Border.zip, NoBlur1_0.zip, §lDefault 3D§r             §lV2.3.5.zip, SnowSong1.4_1.7.x.zip]
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

This also occurs in Singleplayer, but notably, it does not occur when I use the launcher. I can't use the launcher to run my server, however, so what am I doing wrong/What's wrong with the Manual Installation?

**Comment by Collin1971** [comment]
You have to use a newer version of Forge.
