### ISSUE TITLE
Ban accepted appeal inventory clear BUG

### ISSUE THREAD

**Issue by creepertech2000** [gildedgames/aether-issues#582]
I am not wandering why my inventory was cleared but it has some glitches first of all I did not loose my aether coins and second if you have for Ect. a Regen stone or a pet or any backpack item in general you will not loose it all I had before I was banned was a  Regen stone but when my appeal got accepted it was still there. (I told kid and gave the stone to him)

**Comment by Collin1971** [comment]
@xJonL This issue is not invalid. How we clear player inventories needs to be changed on the AOS, as it doesn't remove items from our inventory slots.
