### ISSUE TITLE
Life Shard sometimes gives you 0.5 hearts and sometimes 1 heart

### ISSUE THREAD

**Issue by jeremj22** [gildedgames/aether-issues#590]
On the AOS i've found 2 life shards one gave me 0.5 hearts and the 2. gave me 1 heart. Now I have 11.5 hearts instead of 12. i've tried to fix this with the Devs but they couldn't find a solution. I wanted that half heart back and tried around in a singleplayer-world. There i ate 1 life shard and it gave me 0.5 hearts and as i ate another my client though i should now have 1.5 extrahearts and showed me the hearts for a short time. Directly after that the internal server cut my health down on 11 hearts, removing the half from my client and playing a damage-animation. If the AOS team reads this: here's the was to fix it http://download1075.mediafire.com/hf3axb1tlo4g/84wndf9vbgjeesg/Aether+Life-Shard+Fix.PNG. In my Player.data (Username: jeremj22. but there should only be UUIDs) File you can open "Attributes", then randomly open the 3 entries until finding something called "generic.maxHealth". there you open the "Modifiers", finding a Modifier with the name "Aether Health Modifier". As you can see the "Amount" in this represents a % Number and should be 0.2 for my 2 lifeshards.

**Comment by xJonL** [comment]
I can reproduce this issue, we'll look into it, thanks~
