### ISSUE TITLE
The mystery of the vanishing cooked foods!

### ISSUE THREAD

**Issue by SirMrDrJosippy** [gildedgames/aether-issues#592]
Hello reader!

So, I was playing the AetherII Multiplayer Cloud Server, the official one. Everything was running smoothly until about an hour ago. I would go "hunting" for meat in the normal world; this includes cows, pigs, and chicken. For a while I could cook and eat without issue, now however I've run into a bit of a conundrum. When cooked, Beef and Pork alike vanish after trying to eat them. In addition, the two no longer stack with one another. I have tried cooking in both the Aether world and normal world, relogging, and closing out the client. Maybe it's just the server, but it seemed like a good idea to post this here! (Edit: 10:29PM) It turns out that it's just regular normal furnaces are producing this issue, and not the hollystone ones.

**Comment by Collin1971** [comment]
This issue is an extension of #587.
