### ISSUE TITLE
Can't get Aether coins on server

### ISSUE THREAD

**Issue by chy1982** [gildedgames/aether-issues#594]
Hi there, we got some coin problems here. I am not a native speaker so I'll try to describe it briefly.

Version:
minecraft 1.7.10 forge 1558
aether-1.7.10-1.5.2
MCPC cauldron server

What happens: 
1. We can see coins drop after killing creatures.
2. When characters on single mode pick up coins, coin amounts add correctly, but on server it doesn't.
3. When characters get coins  on single mode then back to server, he can see coin amounts added, and the amount will be the same as single mode. 
4. I have tried to remove all server plugins but it didn't work.

Is this a bug or just something like setting error? 

Thanks a lot!

**Comment by Collin1971** [comment]
We do not support server implementations other than Minecraft Forge.

You're welcome to try your hands with [KCauldron](http://tcpr.ca/kcauldron) however, which is a newer and more maintained version of MCPC's Cauldron.
