### ISSUE TITLE
Torches Recipe Botched

### ISSUE THREAD

**Issue by Goldbartender** [gildedgames/aether-issues#601]
Bug found with attempting to make regular torches in the Crafting Table. Ingredients placed on the 3x3 grid only result in a single torch appearing on the crafted-items slot. The torch can only be grabbed once, and disappears when placed. I attempted this thrice, and got a screenshot. 

![2016-01-07_19 45 56](https://cloud.githubusercontent.com/assets/16602045/12187358/32ba3888-b579-11e5-8617-12db21645a8a.png)

**Comment by Collin1971** [comment]
**Please stop creating issues for the Aether Official Server.**

This is a KCauldron/AOS configuration issue, not ours.
