### ISSUE TITLE
Textures in the festive update

### ISSUE THREAD

**Issue by ThatPortal2Fan** [gildedgames/aether-issues#605]
They got "#rekt". I don't even know what's the problem with these, but either in multiplayer or single player it's the same thing! Here is a shot from the AOS and a shot from the vanilla achievement section:

![screen shot 2016-01-17 at 7 38 18 am](https://cloud.githubusercontent.com/assets/16741341/12376460/7b3658b4-bced-11e5-8efd-c4fdd429a67c.png)

 Just look at this mess!

![2016-01-17_07 37 35](https://cloud.githubusercontent.com/assets/16741341/12376461/8b49517a-bced-11e5-89bb-d460b04effee.png)

 Please fix it in the 1.8 rewrite!

 Love, ThatPortal2Fan.

**Comment by roket333** [comment]
I'm not having this problem. Try defraging your computer's hard drive.

**Comment by ThatPortal2Fan** [comment]
I discovered that this only happens sometimes… Also, this is a borrowed computer, so until I get a new one, (my old one's broken) I guess I'll just have to bare with these… Oh well, they're kind of funny, so it doesn't really matter. :) (but seriously the Aether Team should really fix whatever is going on, because this never happened to me in any other version of Aether/Aether II/vanilla/anything else really.

**Comment by Collin1971** [comment]
> Try defraging your computer's hard drive.
This wouldn't do anything.

> I discovered that this only happens sometimes…
Are you running the Aether on a Mac?
