### ISSUE TITLE
Crash when opening "Manage part members" or "View party members"

### ISSUE THREAD

**Issue by roket333** [gildedgames/aether-issues#608]
---- Minecraft Crash Report ----
// Don't be sad. I'll do better next time, I promise!

Time: 1/24/16 5:49 AM
Description: Rendering screen

java.lang.NullPointerException: Rendering screen
    at java.util.regex.Matcher.getTextLength(Unknown Source)
    at java.util.regex.Matcher.reset(Unknown Source)
    at java.util.regex.Matcher.<init>(Unknown Source)
    at java.util.regex.Pattern.matcher(Unknown Source)
    at net.minecraft.util.StringUtils.func_76338_a(SourceFile:22)
    at net.aetherteam.aether.client.SkinManager.getSkinUrl(SkinManager.java:32)
    at net.aetherteam.aether.client.SkinManager.bindSkin(SkinManager.java:23)
    at net.aetherteam.aether.client.gui.social.GuiPlayerSlot.drawPlayerSlot(GuiPlayerSlot.java:80)
    at net.aetherteam.aether.client.gui.social.party.GuiManageMembers.func_73863_a(GuiManageMembers.java:253)
    at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1061)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:990)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at java.util.regex.Matcher.getTextLength(Unknown Source)
    at java.util.regex.Matcher.reset(Unknown Source)
    at java.util.regex.Matcher.<init>(Unknown Source)
    at java.util.regex.Pattern.matcher(Unknown Source)
    at net.minecraft.util.StringUtils.func_76338_a(SourceFile:22)
    at net.aetherteam.aether.client.SkinManager.getSkinUrl(SkinManager.java:32)
    at net.aetherteam.aether.client.SkinManager.bindSkin(SkinManager.java:23)
    at net.aetherteam.aether.client.gui.social.GuiPlayerSlot.drawPlayerSlot(GuiPlayerSlot.java:80)
    at net.aetherteam.aether.client.gui.social.party.GuiManageMembers.func_73863_a(GuiManageMembers.java:253)

-- Screen render details --
Details:
    Screen name: net.aetherteam.aether.client.gui.social.party.GuiManageMembers
    Mouse location: Scaled: (528, 230). Absolute: (1057, 534)
    Screen size: Scaled: (960, 498). Absolute: (1920, 996). Scale factor of 2

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityClientPlayerMP['roket333'/226173, l='MpServer', x=-19251.08, y=65.62, z=-25843.20]]
    Chunk stats: MultiplayerChunkCache: 309, 309
    Level seed: 0
    Level generator: ID 00 - default, ver 1. Features enabled: false
    Level generator options: 
    Level spawn location: World: (-19329,62,-25737), Chunk: (at 15,3,7 in -1209,-1609; contains blocks -19344,0,-25744 to -19329,255,-25729), Region: (-38,-51; contains chunks -1216,-1632 to -1185,-1601, blocks -19456,0,-26112 to -18945,255,-25601)
    Level time: 476559861 game time, 183775830 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
    Forced entities: 58 total; [EntitySheepuff['Sheepuff'/336135, l='MpServer', x=162.94, y=-0.08, z=27162.06], EntityZephyr['Zephyr'/340268, l='MpServer', x=-19274.96, y=92.44, z=-25865.07], EntitySheepuff['Sheepuff'/336136, l='MpServer', x=157.94, y=-0.04, z=27164.25], EntitySheepuff['Sheepuff'/316244, l='MpServer', x=27684.50, y=-0.08, z=25681.53], EntityFlyingCow['Flying Cow'/336144, l='MpServer', x=73.03, y=-0.02, z=27135.19], EntityAechorPlant['Aechor Plant'/337513, l='MpServer', x=27697.00, y=-0.05, z=25597.00], EntityAechorPlant['Aechor Plant'/337515, l='MpServer', x=27699.00, y=-0.09, z=25592.00], EntityAechorPlant['Aechor Plant'/337514, l='MpServer', x=27702.00, y=-0.09, z=25595.00], EntityMoa['Moa'/336156, l='MpServer', x=160.41, y=-0.02, z=27166.25], EntityFlyingCow['Flying Cow'/335142, l='MpServer', x=24040.19, y=-0.00, z=-8975.53], EntityMoa['Moa'/316230, l='MpServer', x=27608.53, y=-0.01, z=25676.66], EntityMoa['Moa'/316229, l='MpServer', x=27606.69, y=-0.05, z=25663.75], EntityMoa['Moa'/336155, l='MpServer', x=129.69, y=-0.02, z=27127.25], EntityClientPlayerMP['roket333'/226173, l='MpServer', x=-19251.08, y=65.62, z=-25843.20], EntityMoa['Moa'/335135, l='MpServer', x=24038.00, y=-0.05, z=-9095.28], EntityMoa['Moa'/332096, l='MpServer', x=-19235.19, y=58.00, z=-25779.72], EntityAerbunny['Aerbunny'/332103, l='MpServer', x=-19232.66, y=58.89, z=-25800.69], EntityPhyg['Phyg'/332100, l='MpServer', x=-19313.88, y=46.00, z=-25824.44], EntityZephyr['Zephyr'/340236, l='MpServer', x=-19277.60, y=184.80, z=-25857.97], EntityAerbunny['Aerbunny'/332104, l='MpServer', x=-19237.59, y=60.13, z=-25804.09], EntityZephyr['Zephyr'/340233, l='MpServer', x=-19286.76, y=150.66, z=-25885.26], EntityFlyingCow['Flying Cow'/332111, l='MpServer', x=-19240.19, y=62.00, z=-25820.50], EntityZephyr['Zephyr'/340235, l='MpServer', x=-19268.14, y=147.30, z=-25864.77], EntityAerbunny['Aerbunny'/332109, l='MpServer', x=-19235.77, y=61.52, z=-25821.23], EntityItem['item.tile.aercloud0'/337487, l='MpServer', x=-19261.16, y=20.13, z=-25892.72], EntityFlyingCow['Flying Cow'/332115, l='MpServer', x=-19252.47, y=66.59, z=-25849.50], EntityAerbunny['Aerbunny'/337486, l='MpServer', x=-19270.00, y=88.52, z=-25893.00], EntitySheepuff['Sheepuff'/332114, l='MpServer', x=-19277.57, y=62.00, z=-25838.52], EntityAerbunny['Aerbunny'/337485, l='MpServer', x=-19271.00, y=88.52, z=-25890.00], EntityMoa['Moa'/332113, l='MpServer', x=-19271.25, y=65.00, z=-25843.38], EntitySheepuff['Sheepuff'/337484, l='MpServer', x=-19273.94, y=83.00, z=-25898.47], EntityFlyingCow['Flying Cow'/332112, l='MpServer', x=-19235.75, y=59.00, z=-25804.53], EntityFlyingCow['Flying Cow'/332119, l='MpServer', x=-19305.50, y=33.00, z=-25875.03], EntityFlyingCow['Flying Cow'/332118, l='MpServer', x=-19312.50, y=15.00, z=-25873.41], EntityFlyingCow['Flying Cow'/332117, l='MpServer', x=-19230.38, y=58.00, z=-25829.53], EntityFlyingCow['Flying Cow'/332116, l='MpServer', x=-19216.22, y=55.00, z=-25835.88], EntityFlyingCow['Flying Cow'/332121, l='MpServer', x=-19239.97, y=86.00, z=-25880.06], EntityZephyr['Zephyr'/337477, l='MpServer', x=27643.00, y=57.00, z=25615.00], EntityFlyingCow['Flying Cow'/332120, l='MpServer', x=-19215.41, y=75.00, z=-25853.94], EntityZephyr['Zephyr'/337476, l='MpServer', x=27640.00, y=23.00, z=25612.00], EntityZephyr['Zephyr'/336924, l='MpServer', x=23958.00, y=119.00, z=-8997.00], EntitySwet['Swet'/335079, l='MpServer', x=24042.47, y=-0.09, z=-9081.59], EntityZephyr['Zephyr'/336923, l='MpServer', x=23962.00, y=222.00, z=-9042.00], EntityFlyingCow['Flying Cow'/332079, l='MpServer', x=-19276.88, y=56.00, z=-25801.97], EntityFlyingCow['Flying Cow'/332074, l='MpServer', x=-19285.50, y=56.00, z=-25802.69], EntityFlyingCow['Flying Cow'/332075, l='MpServer', x=-19274.22, y=58.00, z=-25807.63], EntityFlyingCow['Flying Cow'/335089, l='MpServer', x=24043.66, y=-0.00, z=-8976.50], EntityMoa['Moa'/332080, l='MpServer', x=-19272.63, y=58.00, z=-25795.38], EntityMoa['Moa'/332095, l='MpServer', x=-19229.06, y=53.00, z=-25784.66], EntityFlyingCow['Flying Cow'/332088, l='MpServer', x=-19309.31, y=48.00, z=-25820.53], EntityZephyr['Zephyr'/336222, l='MpServer', x=61.00, y=134.00, z=27201.00], EntityZephyr['Zephyr'/336223, l='MpServer', x=56.00, y=217.00, z=27201.00], EntityAerbunny['Aerbunny'/332039, l='MpServer', x=-19285.72, y=61.75, z=-25779.38], EntityZephyr['Zephyr'/336224, l='MpServer', x=60.00, y=103.00, z=27205.00], EntityAerbunny['Aerbunny'/335063, l='MpServer', x=24003.66, y=-0.03, z=-9091.16], EntityAerbunny['Aerbunny'/335064, l='MpServer', x=24010.69, y=-0.05, z=-9094.16], EntitySentry['Sentry'/280616, l='MpServer', x=168406.38, y=-0.07, z=23.03], EntitySentry['Sentry'/280617, l='MpServer', x=168406.81, y=-0.02, z=18.41]]
    Retry entities: 0 total; []
    Server brand: kcauldron,cauldron,craftbukkit,mcpc,fml,forge
    Server type: Non-integrated multiplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2433)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:908)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 8.1 (amd64) version 6.3
    Java Version: 1.7.0_71, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 121293160 bytes (115 MB) / 419954688 bytes (400 MB) up to 1908932608 bytes (1820 MB)
    JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
    FML: MCP v9.05 FML v7.10.85.1236 Minecraft Forge 10.13.2.1236 7 mods loaded, 7 mods active
    mcp{9.05} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    FML{7.10.85.1236} [Forge Mod Loader](forge-1.7.10-10.13.2.1236.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    Forge{10.13.2.1236} [Minecraft Forge](forge-1.7.10-10.13.2.1236.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    mod_ThreadedLighting{1.7.10-1.0} [Threaded Lighting](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    gilded-games-util{1.7.10-1.2} [Gilded Games Utility](gilded-games-util-1.7.10-1.9.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    aether{1.7.10-1.6} [Aether II](aether-1.7.10-1.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    TestEnvironmentMod{1.0} [TestEnvironmentMod](SliderDanger.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    Launched Version: 1.7.10-Forge10.13.2.1236
    LWJGL: 2.9.1
    OpenGL: GeForce GTX 970/PCIe/SSE2 GL version 4.5.0 NVIDIA 361.43, NVIDIA Corporation
    GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

```
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: []
Current Language: English (US)
Profiler Position: N/A (disabled)
Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
Anisotropic Filtering: Off (1)
```

The "SliderDanger" mod is one I made which adds a pickaxe that kills the slider in 28 hits but in no way contacts the aether

**Comment by roket333** [comment]
what puzzles me is the "EntitySentry['Sentry'/280616, l='MpServer', x=168406.38, y=-0.07, z=23.03], EntitySentry['Sentry'/280617, l='MpServer', x=168406.81, y=-0.02, z=18.41]]"
Why are there sentries in the Aether?

**Comment by Collin1971** [comment]
@roket333 Multiple dimensions are loaded at a time...

**Comment by Collin1971** [comment]
You're running an outdated version of Forge (10.13.2.1236). Please update to the latest recommended build for 1.7.10.
