### ISSUE TITLE
Aether respawn bug

### ISSUE THREAD

**Issue by roket333** [gildedgames/aether-issues#616]
https://www.youtube.com/watch?v=7aj1LgtwlMw
When any players die, they have to relog or the world glitches out
Then again, this may be a bug with kcauldron or Creeper Hosting but I just wanted to run it by you guys to double check.

**Comment by Lachney** [comment]
That is a server bug, whatever plugin that handles respawning is causing this problem. In your Essentials configuration, find where it handles spawning and change its priority to LOW.
