### ISSUE TITLE
Potion ID conflicts with Biomes O' Plenty

### ISSUE THREAD

**Issue by roket333** [gildedgames/aether-issues#623]
25 is asked by: potion.paralysis (biomesoplenty.common.potions.PotionParalysis), Slowfall (net.aetherteam.aether.potions.AetherPotion)
26 is asked by: potion.possession (biomesoplenty.common.potions.PotionPossession), High Steps (net.aetherteam.aether.potions.AetherPotion)

**Comment by roket333** [comment]
Potion ID conflict

**Comment by Collin1971** [comment]
There's a configuration file for the Aether (found in `config/aether/Aether II.cfg`) where you can change the potion ids.

```
"potion ids" {
    I:"High Steps Potion ID"=26
    I:"Slowfall Potion ID"=25
}
```
