### ISSUE TITLE
Lighting Code Issue

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [gildedgames/aether-issues#624]
"com.gildedgames.util.threadedlighting.world.ThreadedWorld" is the problem, remove the mod. Moving the lighting calculations to a thread isn't safely doable as it involves global state modifications and running arbitrary code on some mod blocks. Doing it regardless will cause sporadic crashes and corruption. FC detects one case of those invalid global state modifications since ctest22 for debugging purposes, the final versions won't have this by default.

http://forum.industrial-craft.net/index.php?page=Thread&postID=199072#post199072

**Comment by Collin1971** [comment]
The Aether II is near unplayable without Threaded Lighting on MC 1.7.10.

We have no plans to remove it until MC 1.8, as the issue doesn't exist in that version.

**Comment by Razorskills** [comment]
#584 might also be similiar

**Comment by P3rf3ctXZer0** [comment]
Unfortunately than I have no choice but to remove your awesome mod.
