### ISSUE TITLE
Placing a bucket of water with any bucket crashes my Hamachi server

### ISSUE THREAD

**Issue by Nexus345** [gildedgames/aether-issues#628]
So I made a hamachi server for me and my brother to play the aether and when we tried to make a portal with and iron bucket, the server crashed.Then I tried a skyroot bucket and the same thing happened. This doesn't happen in single player.I can pick up water fine.

Please help
~Nexus345

_Here is the crash report_
[http://pastebin.com/chkHfGM4](url)

**Comment by Collin1971** [comment]
You need to update Forge to the latest *recommended* 1.7.10 version for the Aether to work.

**Comment by Nexus345** [comment]
Thank you a lot for responding quickly

**Comment by Nexus345** [comment]
Bummer I can't have plugins because I can't change the current forge version.
