### ISSUE TITLE
Protected Chests

### ISSUE THREAD

**Issue by Gaster666** [gildedgames/aether-issues#632]
I have a house in the Aether that is protected with a block. I placed an altar, some chests, and some other things, and they now say that they aren't owned by me. I now don't have access to any of my things. Is there any way to open them?

**Comment by JamesLandregan** [comment]
Have you changed your username recently? If not i may have to delete my issue as that's my theory.

**Comment by Collin1971** [comment]
This issue tracker isn't for issues involving the multiplayer gameplay or the Aether Official Server. You'll need to contact the staff of the server you're on.
