### ISSUE TITLE
How to change where you fall out of the world from

### ISSUE THREAD

**Issue by Kusorai** [gildedgames/aether-issues#639]
Is it possible to change where you fall after falling out of the Aether? Like, instead of a random location you get sent to spawn?

**Comment by Lachney** [comment]
With the mod, no you cannot unfortunately as it's hard coded into the mod. Out of curiosity, what kind of world did you have in mind to fall into?

**Comment by Kusorai** [comment]
Just the overworld spawn point.

**Comment by Lachney** [comment]
Ahh okay I see. I'll keep note of this and maybe has this adjustable in the future. Thanks for submitting an issue!
