### ISSUE TITLE
Block ID config

### ISSUE THREAD

**Issue by Kusorai** [gildedgames/aether-issues#640]
There's a lack in Block ID changing and I think that needs fixed asap. I'd love to be able to use this mod with other modpacks like Advent of Ascension but sadly even it lacks a Block ID config. Perhaps add this in the next update?

**Comment by Tamaized** [comment]
Block IDs were removed from Forge in 1.7 (Well, it's forge that handles it) there shouldn't be any conflicts unless you're running outdated 1.6 versions.

**Comment by Kusorai** [comment]
When I have AoA in the mods folder, all of the blocks in the Aether morph into the blocks from the different dimendions from AoA.

**Comment by Collin1971** [comment]
It's not possible for us to add configuration options for block IDs, it's decided by Forge per-world last time I checked.

Are you using an existing world or a new one after you've installed the Aether?

**Comment by Kusorai** [comment]
Existing.

**Comment by Collin1971** [comment]
Could you see if the issue still persists in an _new_ world once you've installed the Aether? If so, you'll need to simply re-create your world, unfortunately.

**Comment by Kusorai** [comment]
As soon as I get home in a few hours I will post my results of that. Just to clearify, Aether II was installed first off and worked fine but when I placed Advent of Ascending into the mods folder, their blocks began fusing with the Aethers.

**Comment by Kusorai** [comment]
It worked btw. Thanks. I don't know why it had to be so complicated.
