### ISSUE TITLE
loading into laberath demension crashes whole client. 1.7.10 issue

### ISSUE THREAD

**Issue by Shadowmaster94** [gildedgames/aether-issues#642]
my issue I've figured out is that  when spawning in a slider's Labyrinth totem thing and clicking yes for it to take you.. it crashes the client in transit to the dimension,  no matter how many mods i put in the client . i don't know if it would do this on a server but I'm certain it does it on single player.

**Comment by Collin1971** [comment]
Perhaps you should _upload_ that crash log.

**Comment by Shadowmaster94** [comment]
certainly that will be done asap

i tried with and without optifine and found it to still crash 

[crash-2016-06-11_15.17.06-client.txt](https://github.com/gildedgames/aether-issues/files/310430/crash-2016-06-11_15.17.06-client.txt)
[crash-2016-06-11_15.20.41-client.txt](https://github.com/gildedgames/aether-issues/files/310431/crash-2016-06-11_15.20.41-client.txt)

**Comment by Collin1971** [comment]
The issue appears to be with Dynamic Surroundings, they're doing some ASM trickery that doesn't seem to like the Aether.

**Comment by Shadowmaster94** [comment]
yeah i thought that might be the case. ill see if updating it to the latest version will fix that.

**Comment by Shadowmaster94** [comment]
updating Dynamic Surroundings to the latest one seemed to have fixed the issue :) thanks for your help
