### ISSUE TITLE
Multiple Bugs - JEI Incompatibility, Portals not spawning, and crash with Skyroot Axe when chopping a Skyroot tree

### ISSUE THREAD

**Issue by ghost** [gildedgames/aether-issues#663]
1.) When in the standard inventory screen with the Aether II UI, the buttons and search bar for JEI(Just enough items) are unable to be clicked. When in other inventories, such as the furnace or crafting table, this problem is not present.
2.) When I first spawned into the Aether via a glowstone portal from the overworld, a portal didn't spawn in the Aether, so I have no way of returning other than falling back to the overworld, if that still is a feature.
3.) Link to the crashlog - http://pastebin.com/hKhUVG14

**Comment by jellysquid3** [comment]
This issue tracker is for the 1.7 version of the Aether only.

Please report issues for the indev version here: https://git.gildedgames.com/GildedGames/Aether-II/issues
