### ISSUE TITLE
game keeps on crashing 

### ISSUE THREAD

**Issue by djpj3000** [gildedgames/aether-issues#664]
https://www.youtube.com/watch?v=IX8sbn2mSuA
my game KEEPS ON CRASHING EACH TIME I BREAK THIS BLOCK, yes, I have tried to avoid this block, but each time, there is another block that crashes my game, can someone help me please ps, it also crashes  when it gets opened

**Comment by jellysquid3** [comment]
This issue tracker is for the 1.7 version of the Aether only.

Please report issues for the indev version here: https://git.gildedgames.com/GildedGames/Aether-II/issues
