### ISSUE TITLE
Crafting Bugs

### ISSUE THREAD

**Issue by Nyodex** [gildedgames/aether-issues#667]
So I have installed JEI with the Aether II to help me with the new recipes.  I noticed now that you cannot craft the Light Gummy Swet, any of the Overworld material Gloves, Orange Lollipops, Sentry Stone Walls, or any of the Divine blocks (Stairs, slab, etc).  You can even craft an Orange with a similar recipe to the Blueberry Lollipop.  You also cannot smelt Quicksoil into Quicksoil Glass (Maybe that's intentional, but I haven't seen any other ways to get it).  I hope this helps! :)

**Comment by jellysquid3** [comment]
This issue tracker is not for the indev releases. To report an issue with indev releases, use our issue tracker at https://git.gildedgames.com/GildedGames/Aether-II/issues.
