### ISSUE TITLE
Crashing when i try to create a Portal ?

### ISSUE THREAD

**Issue by Seiten3** [gildedgames/aether-issues#671]
Hello Guys, 

i can't play this Mod because it always just crashes when i try to build a Portal (Glowstone and Water).

Why ? Anybody a Solution ?
Iam playing Life in the Woods, and added this Mod to the Pack. Other Mod do well, but this one crashing.
Here is the Log file:  (Minecraft 1.7.10)

http://pastebin.com/muc9pUi4

Thanks.

**Comment by Jonathing** [comment]
Your "Life in the Woods" modpack is currently running an outdated version of forge. The version of forge you're using has no idea what to do with the bucket after you use it on the glowstone portal frame. You can update your forge version at the [Minecraft Forge downloads page](http://files.minecraftforge.net/).

**Comment by jellysquid3** [comment]
Please update Forge to build 1558.
