### ISSUE TITLE
Crossbows crash game when fired (1.10.2)

### ISSUE THREAD

**Issue by xXTheChaoticOneXx** [gildedgames/aether-issues#675]
The game allows the user to load any crossbow but when you attempt to fire them the game crashes
(will add crash report in next part)

**Comment by jellysquid3** [comment]
This issue tracker is not for issues pertaining to the indev releases (1.10 or newer) of the Aether. You can find the new issue tracker [here](https://git.gildedgames.com/GildedGames/Aether-II/issues), or via the in-game bug report tab in your inventory.
